import{state,$,arr,esc}from'./state.js';
import{classToolOutcome}from'./class-tool-mechanics.js?v=20260831-class-tools1';

let initialized=false,rendering=false;
function klass(){return(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class)||null}
function ensureChoices(){if(!state.c)return{};state.c.choices=state.c.choices||{};if(!state.c.choices.classTools||typeof state.c.choices.classTools!=='object'||Array.isArray(state.c.choices.classTools))state.c.choices.classTools={};return state.c.choices.classTools}
function ensureCard(){let card=$('class-tools-card');if(card)return card;const grid=document.querySelector('[data-wizard-panel="classe"] .step-grid');if(!grid)return null;const skill=$('classe-escolhas')?.closest('.card');card=document.createElement('section');card.id='class-tools-card';card.className='card';card.hidden=true;card.innerHTML='<h3>Ferramentas da Classe</h3><p class="section-note">Proficiências e escolhas concedidas pela classe.</p><div id="class-tool-choices"></div>';if(skill)skill.after(card);else grid.prepend(card);card.addEventListener('change',onChange);return card}
function syncPending(outcome){const box=$('pending');if(!box)return;box.querySelectorAll('[data-class-tool-pending]').forEach(x=>x.remove());if(!outcome.pending.length)return;box.className='status warning';let ul=box.querySelector('ul');if(!ul){box.innerHTML='<strong>Escolhas pendentes</strong><ul></ul>';ul=box.querySelector('ul')}for(const group of outcome.pending){const li=document.createElement('li');li.dataset.classToolPending='1';li.textContent=`Escolha ${group.remaining} opção(ões) de ${group.label.toLowerCase()} da classe.`;ul.appendChild(li)}}
function render(){if(rendering||!state.c)return;rendering=true;try{const card=ensureCard();if(!card)return;const k=klass(),input=ensureChoices(),outcome=classToolOutcome(k,input);state.c.choices.classTools=outcome.choices;const hasRule=outcome.fixed.length||outcome.rule.choices.length;card.hidden=!hasRule;const box=$('class-tool-choices');if(!hasRule){if(box)box.innerHTML='';syncPending(outcome);return}let html='';if(outcome.fixed.length)html+=`<p><strong>Proficiências fixas:</strong> ${outcome.fixed.map(x=>`<span class="pill">${esc(x)}</span>`).join(' ')}</p>`;for(const group of outcome.rule.choices){const chosen=arr(outcome.choices[group.id]),remaining=Math.max(0,group.choose-chosen.length);html+=`<fieldset data-class-tool-group="${esc(group.id)}"><legend>${esc(group.label)} — escolha ${remaining}</legend><div class="check-grid">${group.options.map(option=>{const checked=chosen.includes(option),disabled=!checked&&remaining===0;return`<label class="check"><input class="class-tool-choice" type="checkbox" data-group="${esc(group.id)}" value="${esc(option)}" ${checked?'checked':''} ${disabled?'disabled':''}>${esc(option)}</label>`}).join('')}</div></fieldset>`}if(box)box.innerHTML=html;syncPending(outcome)}finally{rendering=false}}
function onChange(e){const input=e.target.closest('.class-tool-choice');if(!input)return;const k=klass(),current=ensureChoices(),rule=classToolOutcome(k,current).rule,group=rule.choices.find(x=>x.id===input.dataset.group);if(!group)return;const values=arr(current[group.id]).filter(x=>group.options.includes(x));if(input.checked){if(values.length>=group.choose){input.checked=false;return}current[group.id]=[...new Set([...values,input.value])].slice(0,group.choose)}else current[group.id]=values.filter(x=>x!==input.value);render();document.dispatchEvent(new CustomEvent('hub:class-tools-changed'));$('nome')?.dispatchEvent(new Event('input'))}
function bind(){
 $('classe')?.addEventListener('change',()=>queueMicrotask(render));
 $('new-character')?.addEventListener('click',()=>queueMicrotask(render));
 for(const event of['hub:class-context-changed','hub:class-tools-changed'])document.addEventListener(event,()=>queueMicrotask(render));
 const pending=$('pending');if(pending)new MutationObserver(()=>{const out=classToolOutcome(klass(),ensureChoices());if(out.pending.length&&!pending.querySelector('[data-class-tool-pending]'))queueMicrotask(()=>syncPending(out))}).observe(pending,{childList:true,subtree:true})
}
export function initClassToolUi(){if(initialized)return;initialized=true;ensureChoices();ensureCard();bind();render()}
