import{state,$,arr,esc}from'./state.js';
import{loadInvocations}from'./invocation-catalog.js?v=20260831-warlock-invocations2';
import{sanitizeWarlockInvocations,invocationChoicePool,invocationEligibleOptions,invocationPrerequisiteResult}from'./invocation-mechanics.js?v=20260831-tasha-metamagic1';

let initialized=false,loading=null,rendering=false;
function klass(){return(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class)||null}
function ensureState(){state.c.choices=state.c.choices||{};state.c.choices.warlockInvocations=state.c.choices.warlockInvocations||{slots:[]};return state.c.choices.warlockInvocations}
function ensureCard(){let card=$('warlock-invocations-card');if(card)return card;const grid=document.querySelector('[data-wizard-panel="classe"] .step-grid');if(!grid)return null;card=document.createElement('section');card.id='warlock-invocations-card';card.className='card';card.hidden=true;card.innerHTML='<h3>Invocações Místicas</h3><p class="section-note">Escolhas oficiais do Bruxo 2024. Pré-requisitos e repetições são validados automaticamente.</p><div id="warlock-invocation-choices"></div>';const tools=$('class-tools-card');if(tools)tools.after(card);else grid.appendChild(card);card.addEventListener('change',onChange);return card}
async function ensureCatalog(){if(arr(state.catalogs.invocations).length===28&&Object.keys(state.catalogs.invocationProgression||{}).length>=20)return true;if(loading)return loading;loading=loadInvocations().then(data=>{state.catalogs.invocations=data.items;state.catalogs.invocationProgression=data.progression;document.dispatchEvent(new CustomEvent('hub:warlock-invocation-catalog-ready'));return true}).catch(error=>{state.warnings.push(`Invocações do Bruxo: ${error.message||error}`);const card=ensureCard(),box=$('warlock-invocation-choices');if(card){card.hidden=false;if(box)box.innerHTML=`<div class="status warning">Catálogo de Invocações indisponível: ${esc(error.message||error)}</div>`}return false}).finally(()=>{loading=null});return loading}
function labelFor(entity){return entity?.nome||entity?.name||entity?.originalName||entity?.id||''}
function simpleChoiceSelect(slot,inv,kind,rows,current){return`<label>${esc(kind)}<select class="warlock-invocation-choice" data-slot="${slot}" data-kind="${esc(kind)}"><option value="">Selecione</option>${arr(rows).map(x=>`<option value="${esc(x.id)}" ${x.id===current?'selected':''}>${esc(labelFor(x))}</option>`).join('')}</select></label>`}
function renderChoice(slot,inv,choice){const type=inv?.escolha?.tipo;if(!type)return'';const pool=invocationChoicePool(inv);if(type==='cantrip_bruxo_dano'||type==='cantrip_bruxo_dano_alcance'||type==='cantrip_bruxo_ataque')return simpleChoiceSelect(slot,inv,'Truque de Bruxo',pool,choice?.cantripId);if(type==='arma_pacto')return simpleChoiceSelect(slot,inv,'Arma de Pacto',pool,choice?.weaponId);if(type==='talento_origem')return simpleChoiceSelect(slot,inv,'Talento de Origem',pool,choice?.featId);if(type==='pact_tome_spells'){const can=arr(pool.cantrips),rit=arr(pool.rituals),chosenCan=arr(choice?.cantrips),chosenRit=arr(choice?.rituals);return`<div class="choice-grid"><label>3 truques<select multiple size="7" class="warlock-tome-choice" data-slot="${slot}" data-kind="cantrips">${can.map(s=>`<option value="${esc(s.id)}" ${chosenCan.includes(s.id)?'selected':''}>${esc(labelFor(s))}</option>`).join('')}</select></label><label>2 rituais de 1º nível<select multiple size="7" class="warlock-tome-choice" data-slot="${slot}" data-kind="rituals">${rit.map(s=>`<option value="${esc(s.id)}" ${chosenRit.includes(s.id)?'selected':''}>${esc(labelFor(s))}</option>`).join('')}</select></label></div>`}return''}
function syncPending(outcome){const box=$('pending');if(!box)return;box.querySelectorAll('[data-warlock-invocation-pending]').forEach(x=>x.remove());if(!outcome.pending.length)return;box.className='status warning';let ul=box.querySelector('ul');if(!ul){box.innerHTML='<strong>Escolhas pendentes</strong><ul></ul>';ul=box.querySelector('ul')}for(const row of outcome.pending){const li=document.createElement('li');li.dataset.warlockInvocationPending='1';li.textContent=row.message;ul.appendChild(li)}}
function render(){if(rendering||!state.c)return;rendering=true;try{const card=ensureCard();if(!card)return;const k=klass();if(k?.slug!=='warlock'){ensureState().slots=[];card.hidden=true;syncPending({pending:[]});return}if(arr(state.catalogs.invocations).length!==28){card.hidden=false;const box=$('warlock-invocation-choices');if(box)box.innerHTML='<p class="muted">Carregando catálogo oficial de Invocações…</p>';ensureCatalog().then(ok=>{if(ok){render();refreshSheet()}});return}const outcome=sanitizeWarlockInvocations(),slots=outcome.slots,selectedIds=slots.map(x=>x.id).filter(Boolean),eligible=invocationEligibleOptions({consumer:'class',slots}),selectedCounts={};for(const row of slots)if(row.id)selectedCounts[row.id]=(selectedCounts[row.id]||0)+1;card.hidden=false;let html=`<p class="mini"><strong>Invocações:</strong> ${outcome.selected.length}/${outcome.limit}.</p>`;for(let i=0;i<outcome.limit;i++){const row=slots[i]||{id:'',choice:null},current=state.catalogs.invocations.find(x=>x.id===row.id)||null,options=state.catalogs.invocations.filter(inv=>eligible.some(x=>x.id===inv.id)||inv.id===row.id).filter(inv=>inv.repeatable||!selectedCounts[inv.id]||inv.id===row.id),choiceHtml=current?renderChoice(i,current,row.choice):'';html+=`<fieldset class="invocation-slot"><legend>Invocação ${i+1}</legend><label>Invocação Mística<select class="warlock-invocation-select" data-slot="${i}"><option value="">Selecione</option>${options.map(inv=>{const check=invocationPrerequisiteResult(inv,{consumer:'class',selectedIds}),note=check.ok?'':` — ${check.reasons.join(', ')}`;return`<option value="${esc(inv.id)}" ${inv.id===row.id?'selected':''}>${esc(inv.nome+note)}</option>`}).join('')}</select></label>${choiceHtml}</fieldset>`}const box=$('warlock-invocation-choices');if(box)box.innerHTML=html;syncPending(outcome)}finally{rendering=false}}
function refreshSheet(){document.dispatchEvent(new CustomEvent('hub:warlock-invocations-changed'));$('nome')?.dispatchEvent(new Event('input'))}
function onChange(e){const slot=Number(e.target?.dataset?.slot);if(!Number.isInteger(slot)||slot<0)return;const data=ensureState(),rows=arr(data.slots);while(rows.length<=slot)rows.push({id:'',choice:null});if(e.target.matches('.warlock-invocation-select')){rows[slot]={id:e.target.value||'',choice:null}}else if(e.target.matches('.warlock-invocation-choice')){const inv=state.catalogs.invocations.find(x=>x.id===rows[slot]?.id);if(!inv)return;const type=inv.escolha?.tipo,value=e.target.value||'';if(type==='arma_pacto')rows[slot].choice=value?{weaponId:value}:null;else if(type==='talento_origem')rows[slot].choice=value?{featId:value}:null;else rows[slot].choice=value?{cantripId:value}:null}else if(e.target.matches('.warlock-tome-choice')){const inv=state.catalogs.invocations.find(x=>x.id===rows[slot]?.id);if(inv?.escolha?.tipo!=='pact_tome_spells')return;const choice=rows[slot].choice&&typeof rows[slot].choice==='object'?rows[slot].choice:{cantrips:[],rituals:[]},values=[...e.target.selectedOptions].map(x=>x.value),kind=e.target.dataset.kind;if(kind==='cantrips')choice.cantrips=values.slice(0,3);else choice.rituals=values.slice(0,2);rows[slot].choice=choice}else return;data.slots=rows;sanitizeWarlockInvocations();render();refreshSheet()}
function bind(){$('classe')?.addEventListener('change',()=>queueMicrotask(render));$('nivel')?.addEventListener('change',()=>queueMicrotask(render));$('new-character')?.addEventListener('click',()=>queueMicrotask(render));for(const event of['hub:class-context-changed','hub:spell-selection-changed','hub:progression-context-changed','hub:warlock-invocation-catalog-ready'])document.addEventListener(event,()=>queueMicrotask(render))}
export function initInvocationUi(){if(initialized)return;initialized=true;ensureState();ensureCard();bind();ensureCatalog().then(()=>render());render()}
