import{state,$,arr,esc}from'./state.js';
import{loadMetamagic}from'./metamagic-catalog.js?v=20260831-tasha-metamagic1';
import{sanitizeSorcererMetamagic}from'./metamagic-mechanics.js?v=20260831-tasha-metamagic1';

let initialized=false,loading=null,rendering=false;
function klass(){return(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class)||null}
function ensureState(){state.c.choices=state.c.choices||{};state.c.choices.sorcererMetamagic=state.c.choices.sorcererMetamagic||{options:[]};return state.c.choices.sorcererMetamagic}
function ensureCard(){let card=$('sorcerer-metamagic-card');if(card)return card;const grid=document.querySelector('[data-wizard-panel="classe"] .step-grid');if(!grid)return null;card=document.createElement('section');card.id='sorcerer-metamagic-card';card.className='card';card.hidden=true;card.innerHTML='<h3>Metamagia</h3><p class="section-note">Opções oficiais do Feiticeiro 2024. A quantidade aumenta nos níveis 10 e 17.</p><div id="sorcerer-metamagic-choices"></div>';const inv=$('warlock-invocations-card');if(inv)inv.after(card);else grid.appendChild(card);card.addEventListener('change',onChange);return card}
async function ensureCatalog(){if(arr(state.catalogs.metamagic).length===10&&Object.keys(state.catalogs.metamagicProgression||{}).length>=20)return true;if(loading)return loading;loading=loadMetamagic().then(data=>{state.catalogs.metamagic=data.items;state.catalogs.metamagicProgression=data.progression;document.dispatchEvent(new CustomEvent('hub:metamagic-catalog-ready'));return true}).catch(error=>{state.warnings.push(`Metamagia do Feiticeiro: ${error.message||error}`);const card=ensureCard(),box=$('sorcerer-metamagic-choices');if(card){card.hidden=false;if(box)box.innerHTML=`<div class="status warning">Catálogo de Metamagia indisponível: ${esc(error.message||error)}</div>`}return false}).finally(()=>{loading=null});return loading}
function syncPending(outcome){const box=$('pending');if(!box)return;box.querySelectorAll('[data-sorcerer-metamagic-pending]').forEach(x=>x.remove());if(!outcome.pending.length)return;box.className='status warning';let ul=box.querySelector('ul');if(!ul){box.innerHTML='<strong>Escolhas pendentes</strong><ul></ul>';ul=box.querySelector('ul')}for(const row of outcome.pending){const li=document.createElement('li');li.dataset.sorcererMetamagicPending='1';li.textContent=row.message;ul.appendChild(li)}}
function render(){if(rendering||!state.c)return;rendering=true;try{const card=ensureCard();if(!card)return;const k=klass();if(k?.slug!=='sorcerer'){ensureState().options=[];card.hidden=true;syncPending({pending:[]});return}if(arr(state.catalogs.metamagic).length!==10){card.hidden=false;const box=$('sorcerer-metamagic-choices');if(box)box.innerHTML='<p class="muted">Carregando catálogo oficial de Metamagia…</p>';ensureCatalog().then(ok=>{if(ok){render();refreshSheet()}});return}const outcome=sanitizeSorcererMetamagic(),ids=outcome.ids,selected=new Set(ids.filter(Boolean));card.hidden=outcome.limit===0;const box=$('sorcerer-metamagic-choices');if(outcome.limit===0){if(box)box.innerHTML='<p class="mini">Metamagia é adquirida no nível 2.</p>';syncPending(outcome);return}if(box)box.innerHTML=`<p class="mini"><strong>Opções:</strong> ${outcome.options.length}/${outcome.limit}.</p><div class="choice-grid">${Array.from({length:outcome.limit},(_,i)=>{const current=ids[i]||'';return`<label>Metamagia ${i+1}<select class="sorcerer-metamagic-select" data-slot="${i}"><option value="">Selecione</option>${state.catalogs.metamagic.map(opt=>`<option value="${esc(opt.id)}" ${opt.id===current?'selected':''} ${selected.has(opt.id)&&opt.id!==current?'disabled':''}>${esc(opt.nome)} · ${esc(String(opt.custo))} PF</option>`).join('')}</select></label>`}).join('')}</div>`;syncPending(outcome)}finally{rendering=false}}
function refreshSheet(){document.dispatchEvent(new CustomEvent('hub:sorcerer-metamagic-changed'));$('nome')?.dispatchEvent(new Event('input'))}
function onChange(e){const select=e.target.closest('.sorcerer-metamagic-select');if(!select)return;const slot=Number(select.dataset.slot),data=ensureState(),values=arr(data.options).slice();while(values.length<=slot)values.push(null);values[slot]=select.value||null;data.options=values;sanitizeSorcererMetamagic();render();refreshSheet()}
function bind(){$('classe')?.addEventListener('change',()=>queueMicrotask(render));$('nivel')?.addEventListener('change',()=>queueMicrotask(render));$('new-character')?.addEventListener('click',()=>queueMicrotask(render));for(const event of['hub:class-context-changed','hub:progression-context-changed','hub:metamagic-catalog-ready'])document.addEventListener(event,()=>queueMicrotask(render))}
export function initMetamagicUi(){if(initialized)return;initialized=true;ensureState();ensureCard();bind();ensureCatalog().then(()=>render());render()}
