import{state,AB,ABKEY,arr,num,uniq,fold,mod,pb}from'./state.js';
export const item=(k,id)=>state.catalogs[k].find(x=>x.id===id)||null;
export const compatible=k=>state.catalogs[k].filter(x=>x.ruleset===state.c.ruleset);
export function selected(){return{klass:item('classes',state.c.refs.class),species:item('species',state.c.refs.species),bg:item('backgrounds',state.c.refs.background),sub:item('subclasses',state.c.refs.subclass)}}
function bgBonus(bg){const o=Object.fromEntries(AB.map(a=>[a,0])),ch=state.c.choices.background;if(!bg||bg.ruleset!=='5.5e')return o;if(ch.abilityMode==='1+1+1')for(const a of bg.abilities.slice(0,3))o[a]+=1;else{if(bg.abilities.includes(ch.plus2))o[ch.plus2]+=2;if(bg.abilities.includes(ch.plus1)&&ch.plus1!==ch.plus2)o[ch.plus1]+=1}return o}
function spBonus(sp,line){const o=Object.fromEntries(AB.map(a=>[a,0]));for(const b of [...arr(sp?.abilityBonuses),...arr(line?.abilityBonuses)]){const a=ABKEY[b.ability]||b.ability||b.atributo;if(o[a]!=null)o[a]+=num(b.bonus??b.valor??1)}return o}
function featNames(klass,bg,level){const n=[];if(bg?.feat?.name)n.push(bg.feat.name);arr(klass?.featSlots).filter(l=>l<=level).forEach((l,i)=>{const f=item('feats',state.c.choices.feats[`slot-${l}-${i}`]);if(f)n.push(f.name)});return n}
function featEffect(n,level,pbonus){const f=n.map(fold);return{initiative:f.some(x=>x==='alert'||x==='alerta')?pbonus:0,hp:f.some(x=>['tough','durao','duravel'].includes(x))?2*level:0}}
function armorAC(a,dex){if(!a)return 10+dex;const s=String(a.ca||''),base=num((s.match(/\d+/)||['10'])[0]);if(/modificador de Destreza|Dexterity/i.test(s))return base+(a.categoria==='Média'?Math.min(2,dex):dex);return base}
export function trainedArmor(k,a){if(!a)return true;const p=fold([...arr(k?.proficiencies),...arr(k?.proficienciesRaw)].join(' '));if(a.categoria==='Leve')return/light armor|armadura leve|all armor|todas as armaduras/.test(p);if(a.categoria==='Média')return/medium armor|armadura media|all armor|todas as armaduras/.test(p);if(a.categoria==='Pesada')return/heavy armor|armadura pesada|all armor|todas as armaduras/.test(p);return true}
export const shieldTraining=k=>/shield|escudo/.test(fold([...arr(k?.proficiencies),...arr(k?.proficienciesRaw)].join(' ')));
function weaponProf(k,w){if(!w||!k)return false;const p=fold([...k.proficiencies,...k.proficienciesRaw].join(' ')),c=fold(w.categoria);if(c.includes('simples')&&/simple weapon|arma simples/.test(p))return true;if(c.includes('marcial')&&/martial weapon|arma marcial/.test(p))return true;return p.includes(fold(w.nome))||p.includes(fold(w.nome_original))}
function spellProgress(k,l){const r=arr(k?.levels).find(x=>num(x.level)===l),s=r?.spellcasting||r?.class_specific?.spellcasting||{},slots=[];for(let i=1;i<=9;i++){const v=num(s[`spell_slots_level_${i}`]);if(v)slots.push(`${i}º: ${v}`)}return{cantrips:num(s.cantrips_known??s.cantrips),prepared:num(s.spells_prepared??s.prepared_spells??s.spells_known),slots}}
function hpTotal(k,l,con,fe){if(!k)return null;let hp=k.hitDie+con;if(l>1){if(state.c.choices.class.hpMode==='average'){const a=Math.floor(k.hitDie/2)+1;hp+=(l-1)*(a+con)}else for(let n=2;n<=l;n++){const r=num(state.c.choices.class.hpRolls[n]);if(!r)return null;hp+=Math.max(1,Math.min(k.hitDie,r))+con}}return Math.max(l,hp+fe.hp)}
export function subclassLevel(k){if(!k)return 99;if(k.ruleset==='5.5e')return 3;return({cleric:1,sorcerer:1,warlock:1,druid:2,wizard:2}[k.slug]||3)}
export function derive(){const{klass,species,bg,sub}=selected(),level=Math.max(1,Math.min(20,num(state.c.choices.class.level)||1)),pbonus=pb(level),lineage=species?.lineages?.find(x=>x.name===state.c.choices.species.lineage)||null,bb=bgBonus(bg),sb=spBonus(species,lineage),scores={};for(const a of AB)scores[a]=Math.min(20,num(state.c.baseAbilities[a])+bb[a]+sb[a]);const skills=uniq([...(bg?.skills||[]),...arr(state.c.choices.class.skills)]),tools=uniq([...(bg?.tools||[]),state.c.choices.background.toolChoice].filter(Boolean)),feats=featNames(klass,bg,level),fe=featEffect(feats,level,pbonus),armor=item('armors',state.c.choices.equipment.armor),weapon=item('weapons',state.c.choices.equipment.weapon),dex=mod(scores.Destreza),str=mod(scores.Força),wis=mod(scores.Sabedoria),con=mod(scores.Constituição);let speed=species?.speed||30;if(armor?.forca_minima&&scores.Força<num(armor.forca_minima))speed-=10;const wAbility=weapon?(/distância/.test(weapon.categoria)?'Destreza':arr(weapon.propriedades).some(x=>/finesse/i.test(x))?(dex>=str?'Destreza':'Força'):'Força'):null,wmod=wAbility?mod(scores[wAbility]):0,wprof=weaponProf(klass,weapon),spell=spellProgress(klass,level),spellMod=klass?.spellAbility?mod(scores[klass.spellAbility]):null,shieldBonus=state.c.choices.equipment.shield&&shieldTraining(klass)?2:0;return{klass,species,bg,sub,level,pbonus,lineage,bb,sb,scores,skills,tools,feats,armor,weapon,ac:armorAC(armor,dex)+shieldBonus,speed,wAbility,wprof,attack:weapon?wmod+(wprof?pbonus:0):null,hp:hpTotal(klass,level,con,fe),spell,spellDC:spellMod==null?null:8+pbonus+spellMod,spellAttack:spellMod==null?null:pbonus+spellMod,initiative:dex+fe.initiative,passive:10+wis+(skills.includes('Percepção')?pbonus:0),speciesTraits:[...(species?.traits||[]),...(lineage?.traits||[])],classFeatures:arr(klass?.features).filter(f=>f.level<=level)}}
export function resetIncompatible(){for(const[ref,k]of[['class','classes'],['species','species'],['background','backgrounds'],['subclass','subclasses']]){const x=item(k,state.c.refs[ref]);if(x&&x.ruleset!==state.c.ruleset)state.c.refs[ref]=null}state.c.choices.class.skills=[];state.c.choices.feats={};state.c.choices.equipment={armor:null,shield:false,weapon:null}}
