import{state,AB,ABKEY,arr,num,uniq,fold,mod,pb}from'./state.js';
export const item=(k,id)=>state.catalogs[k].find(x=>x.id===id)||null;
export const compatible=k=>state.catalogs[k].filter(x=>!x.ruleset||x.ruleset==='5.5e');
export function selected(){return{klass:item('classes',state.c.refs.class),species:item('species',state.c.refs.species),bg:item('backgrounds',state.c.refs.background),sub:item('subclasses',state.c.refs.subclass)}}
function bgBonus(bg){const o=Object.fromEntries(AB.map(a=>[a,0])),ch=state.c.choices.background;if(!bg)return o;if(ch.abilityMode==='1+1+1'){for(const a of bg.abilities.slice(0,3))o[a]+=1}else{if(bg.abilities.includes(ch.plus2))o[ch.plus2]+=2;if(bg.abilities.includes(ch.plus1)&&ch.plus1!==ch.plus2)o[ch.plus1]+=1}return o}
function spBonus(sp,line){const o=Object.fromEntries(AB.map(a=>[a,0]));for(const b of [...arr(sp?.abilityBonuses),...arr(line?.abilityBonuses)]){const a=ABKEY[b.ability]||b.ability||b.atributo;if(o[a]!=null)o[a]+=num(b.bonus??b.valor??1)}return o}
function featNames(klass,bg,level){const n=[];if(bg?.feat?.name)n.push(bg.feat.name);arr(klass?.featSlots).filter(l=>l<=level).forEach((l,i)=>{const f=item('feats',state.c.choices.feats[`slot-${l}-${i}`]);if(f)n.push(f.name)});return n}
function featEffect(n,level,pbonus){const f=n.map(fold);return{initiative:f.some(x=>x==='alert'||x==='alerta')?pbonus:0,hp:f.some(x=>['tough','durao','duravel'].includes(x))?2*level:0}}
function armorAC(a,dex){if(!a)return 10+dex;const s=String(a.ca||''),base=num((s.match(/\d+/)||['10'])[0]);if(/modificador de Destreza|Dexterity/i.test(s))return base+(a.categoria==='Média'?Math.min(2,dex):dex);return base}
export function trainedArmor(k,a){if(!a)return true;const p=fold([...arr(k?.proficiencies),...arr(k?.proficienciesRaw)].join(' '));if(a.categoria==='Leve')return/light armor|armadura leve|all armor|todas as armaduras/.test(p);if(a.categoria==='Média')return/medium armor|armadura media|all armor|todas as armaduras/.test(p);if(a.categoria==='Pesada')return/heavy armor|armadura pesada|all armor|todas as armaduras/.test(p);return true}
export const shieldTraining=k=>/shield|escudo/.test(fold([...arr(k?.proficiencies),...arr(k?.proficienciesRaw)].join(' ')));
function weaponProf(k,w){if(!w||!k)return false;const p=fold([...arr(k.proficiencies),...arr(k.proficienciesRaw)].join(' ')),c=fold(w.categoria);if(c.includes('simples')&&/simple weapon|arma simples/.test(p))return true;if(c.includes('marcial')&&/martial weapon|arma marcial/.test(p))return true;return p.includes(fold(w.nome))||p.includes(fold(w.nome_original))}
export function spellProgress(k,l){const r=arr(k?.levels).find(x=>num(x.level)===l),s=r?.spellcasting||r?.class_specific?.spellcasting||{},slots=[];let maxLevel=0;for(let i=1;i<=9;i++){const v=num(s[`spell_slots_level_${i}`]);if(v){slots.push({level:i,count:v});maxLevel=Math.max(maxLevel,i)}}const arcanumLevels=k?.slug==='warlock'?[6,7,8,9].filter((_,i)=>l>=[11,13,15,17][i]):[];return{cantrips:num(s.cantrips_known??s.cantrips),prepared:num(s.spells_prepared??s.prepared_spells??s.magias_preparadas??s.spells_known),slots,maxLevel,arcanumLevels}}
function classSpellMatch(k,s){const names=[k?.name,k?.slug==='artificer'?'Artífice':null].filter(Boolean).map(fold);return arr(s.classes).some(c=>names.includes(fold(c)))}
export function spellOptions(k,l){const progress=spellProgress(k,l);if(!k?.spellAbility||(!progress.maxLevel&&!progress.arcanumLevels.length))return{progress,cantrips:[],leveled:[],arcanum:{}};const all=state.catalogs.spells.filter(s=>classSpellMatch(k,s)),cantrips=all.filter(s=>s.level===0),leveled=all.filter(s=>s.level>0&&s.level<=progress.maxLevel),arcanum=Object.fromEntries(progress.arcanumLevels.map(level=>[level,all.filter(s=>s.level===level)]));return{progress,cantrips,leveled,arcanum}}
function hpTotal(k,l,con,fe){if(!k)return null;const perLevel=Math.max(1,k.hitDie+con);return Math.max(l,perLevel*l+fe.hp)}
export function subclassLevel(k){return k?3:99}
export function derive(){const{klass,species,bg,sub}=selected(),level=Math.max(1,Math.min(20,num(state.c.choices.class.level)||1)),pbonus=pb(level),lineage=species?.lineages?.find(x=>x.name===state.c.choices.species.lineage)||null,bb=bgBonus(bg),sb=spBonus(species,lineage),scores={};for(const a of AB)scores[a]=Math.min(20,num(state.c.baseAbilities[a])+bb[a]+sb[a]);const skills=uniq([...(bg?.skills||[]),...arr(state.c.choices.class.skills)]),tools=uniq([...(bg?.tools||[]),state.c.choices.background.toolChoice].filter(Boolean)),feats=featNames(klass,bg,level),fe=featEffect(feats,level,pbonus),armor=item('armors',state.c.choices.equipment.armor),weapon=item('weapons',state.c.choices.equipment.weapon),dex=mod(scores.Destreza),str=mod(scores.Força),wis=mod(scores.Sabedoria),con=mod(scores.Constituição);let speed=species?.speed||30;if(armor?.forca_minima&&scores.Força<num(armor.forca_minima))speed-=10;const wAbility=weapon?(/distância/.test(weapon.categoria)?'Destreza':arr(weapon.propriedades).some(x=>/finesse/i.test(x))?(dex>=str?'Destreza':'Força'):'Força'):null,wmod=wAbility?mod(scores[wAbility]):0,wprof=weaponProf(klass,weapon),spell=spellProgress(klass,level),spellMod=klass?.spellAbility?mod(scores[klass.spellAbility]):null,shieldBonus=state.c.choices.equipment.shield&&shieldTraining(klass)?2:0,spellSel=state.c.choices.spells||{cantrips:[],leveled:[],arcanum:{}};return{klass,species,bg,sub,level,pbonus,lineage,bb,sb,scores,skills,tools,feats,armor,weapon,ac:armorAC(armor,dex)+shieldBonus,speed,wAbility,wprof,attack:weapon?wmod+(wprof?pbonus:0):null,hp:hpTotal(klass,level,con,fe),spell,spellDC:spellMod==null?null:8+pbonus+spellMod,spellAttack:spellMod==null?null:pbonus+spellMod,selectedSpells:{cantrips:arr(spellSel.cantrips).map(id=>item('spells',id)).filter(Boolean),leveled:arr(spellSel.leveled).map(id=>item('spells',id)).filter(Boolean),arcanum:Object.fromEntries(Object.entries(spellSel.arcanum||{}).map(([l,id])=>[l,item('spells',id)]).filter(([,x])=>x))},initiative:dex+fe.initiative,passive:10+wis+(skills.includes('Percepção')?pbonus:0),speciesTraits:[...(species?.traits||[]),...(lineage?.traits||[])],classFeatures:arr(klass?.features).filter(f=>f.level<=level)}}
export function sanitizeSelections(){const c=state.c,{klass}=selected(),level=Math.max(1,Math.min(20,num(c.choices.class.level)||1)),opts=spellOptions(klass,level),canIds=new Set(opts.cantrips.map(x=>x.id)),levIds=new Set(opts.leveled.map(x=>x.id));c.choices.spells=c.choices.spells||{cantrips:[],leveled:[],arcanum:{}};c.choices.spells.cantrips=arr(c.choices.spells.cantrips).filter(id=>canIds.has(id)).slice(0,opts.progress.cantrips);c.choices.spells.leveled=arr(c.choices.spells.leveled).filter(id=>levIds.has(id)).slice(0,opts.progress.prepared);const arc={};for(const l of opts.progress.arcanumLevels){const id=c.choices.spells.arcanum?.[l];if(id&&opts.arcanum[l]?.some(x=>x.id===id))arc[l]=id}c.choices.spells.arcanum=arc;for(const[ref,k]of[['class','classes'],['species','species'],['background','backgrounds'],['subclass','subclasses']]){const x=item(k,c.refs[ref]);if(x&&x.ruleset&&x.ruleset!=='5.5e')c.refs[ref]=null}}
