import * as base from './rules-base.js?v=20260824-race-variants1';
import{state,AB,arr,num,fold,uniq,mod}from'./state.js';
import{isCompatible55}from'./compatibility.js?v=20260823-character-builder26';
import{applyBarbarianSubclassMechanics}from'./barbarian-subclass-mechanics.js?v=20260827-barbarian-subclasses1';
import{applyArtificerSubclassMechanics}from'./artificer-subclass-mechanics.js?v=20260827-artificer-subclasses1';
import{applyBardSubclassMechanics}from'./bard-subclass-mechanics.js?v=20260827-bard-subclasses1';
import{applyDruidSubclassMechanics}from'./druid-subclass-mechanics.js?v=20260827-druid-subclasses1';
import{applyFighterSubclassMechanics}from'./fighter-subclass-mechanics.js?v=20260827-fighter-subclasses1';
import{applyFighterSubclassRuleDetails}from'./fighter-subclass-details.js?v=20260827-fighter-subclasses1';
import{applyMonkSubclassMechanics}from'./monk-subclass-mechanics.js?v=20260827-monk-subclasses1';
import{applyMonkSubclassRuleDetails}from'./monk-subclass-details.js?v=20260827-monk-subclasses1';
import{applyPaladinSubclassMechanics}from'./paladin-subclass-mechanics.js?v=20260827-paladin-subclasses1';
import{applyPaladinSubclassRuleDetails}from'./paladin-subclass-details.js?v=20260827-paladin-subclasses1';
import{applyRangerSubclassMechanics}from'./ranger-subclass-mechanics.js?v=20260827-ranger-subclasses1';
import{applyRangerSubclassRuleDetails}from'./ranger-subclass-details.js?v=20260827-ranger-subclasses1';
import{applyRogueSubclassMechanics}from'./rogue-subclass-mechanics.js?v=20260827-rogue-subclasses1';
import{applySorcererSubclassMechanics}from'./sorcerer-subclass-mechanics.js?v=20260828-sorcerer-subclasses1';
import{syncSorcererSpellAccess}from'./sorcerer-spell-access.js?v=20260828-sorcerer-subclasses1';
import{applyWarlockSubclassMechanics}from'./warlock-subclass-mechanics.js?v=20260828-warlock-subclasses1';
import{applyWizardSubclassMechanics}from'./wizard-subclass-mechanics.js?v=20260828-wizard-subclasses2';
import{deriveSkillCheckMechanics}from'./skill-check-mechanics.js?v=20260831-skill-checks1';
import{invocationOutcome,sanitizeWarlockInvocations}from'./invocation-mechanics.js?v=20260901-normative-v1';
import{metamagicOutcome,sanitizeSorcererMetamagic}from'./metamagic-mechanics.js?v=20260901-normative-v1';
import{classToolOutcome,sanitizeClassToolChoices}from'./class-tool-mechanics.js?v=20260902-block10-1';
import{applyTashaFeatEffects,sanitizeTashaFeatChoices}from'./tasha-feat-mechanics.js?v=20260902-block10-1';
import{ownedEquipment}from'./equipment-ownership.js?v=20260902-block10-magic-items1';
import{applyMagicItemPersistentEffects}from'../character-sheet-magic-item-state.js?v=20260902-block10-magic-items1';
export * from './rules-base.js?v=20260824-race-variants1';

export const HOUSE_FEAT_LEVELS=[1,3,6,9,12,15,18];
export const HOUSE_ABILITY_LEVELS=[4,8,12,16,20];
const STANDARD_CLASS_FEAT_LEVELS=new Set([4,8,12,16,19]);
const clone=v=>v==null?v:structuredClone(v);
const featByName=name=>state.catalogs.feats.find(f=>fold(f.name)===fold(name))||null;
const featById=id=>state.catalogs.feats.find(f=>f.id===id)||null;
function stableFeatSlot(entry){return entry.kind==='house'?`house-${entry.level}`:`class-extra-${entry.level}-${entry.order||0}`}
function prepareClasses(){for(const klass of state.catalogs.classes||[]){if(!Array.isArray(klass._houseOriginalFeatSlots))klass._houseOriginalFeatSlots=[...arr(klass.featSlots).map(num).filter(Boolean)];const extras=klass._houseOriginalFeatSlots.filter(level=>!STANDARD_CLASS_FEAT_LEVELS.has(num(level))),progression=[...HOUSE_FEAT_LEVELS.map(level=>({level,kind:'house'})),...extras.map((level,order)=>({level:num(level),kind:'class-extra',order}))].sort((a,b)=>a.level-b.level||(a.kind==='house'?-1:1)||(a.order||0)-(b.order||0));klass._houseFeatProgression=progression.map((entry,index)=>({...entry,index,slot:stableFeatSlot(entry),legacySlot:`slot-${entry.level}-${index}`}));klass.featSlots=progression.map(entry=>entry.level)}}
function migrateSelectedProgressionSlots(){const klass=(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class);if(!klass||!state.c?.choices)return;const choices=state.c.choices.feats||(state.c.choices.feats={}),mechanics=state.c.choices.featMechanics||(state.c.choices.featMechanics={});for(const entry of arr(klass._houseFeatProgression)){if(choices[entry.slot]==null&&choices[entry.legacySlot]!=null)choices[entry.slot]=choices[entry.legacySlot];const oldKey=`class:${entry.legacySlot}`,newKey=`class:${entry.slot}`;if(mechanics[newKey]==null&&mechanics[oldKey]!=null)mechanics[newKey]=mechanics[oldKey]}}
function prepareBackgroundCatalogs(){for(const bg of state.catalogs.backgrounds||[]){if(!Object.prototype.hasOwnProperty.call(bg,'_houseOriginalFeat'))bg._houseOriginalFeat=clone(bg.feat||null);if(!Array.isArray(bg._houseOriginalAbilities))bg._houseOriginalAbilities=[...arr(bg.abilities)];bg.abilities=[...AB];bg.feat=clone(bg._houseOriginalFeat)}const bg=(state.catalogs.backgrounds||[]).find(x=>x.id===state.c?.refs?.background);if(!bg||!state.c?.choices)return;const chosen=featById(state.c.choices.background?.originFeat);bg.feat=chosen?.category==='Origem'?{name:chosen.name,choice:''}:null}
export function initializeHouseBackgroundChoices(){const bg=(state.catalogs.backgrounds||[]).find(x=>x.id===state.c?.refs?.background);if(!bg||!state.c?.choices)return;const ch=state.c.choices.background||(state.c.choices.background={});ch.abilityMode='2+1';ch.plusOnes=[];if(!AB.includes(ch.plus2))ch.plus2=AB[0];if(!AB.includes(ch.plus1)||ch.plus1===ch.plus2)ch.plus1=AB.find(a=>a!==ch.plus2)||AB[1];if(!Object.prototype.hasOwnProperty.call(ch,'originFeat')){const original=featByName(bg._houseOriginalFeat?.name);ch.originFeat=original?.category==='Origem'?original.id:null}prepareBackgroundCatalogs()}
function restoreSpeciesBonuses(){for(const species of state.catalogs.species||[]){if(!Array.isArray(species._houseOriginalAbilityBonuses))species._houseOriginalAbilityBonuses=clone(arr(species.abilityBonuses));species.abilityBonuses=clone(species._houseOriginalAbilityBonuses)||[]}}
function applyHouseAbilityBonuses(){restoreSpeciesBonuses();if(!state.c?.choices)return;const level=Math.max(1,Math.min(20,num(state.c.choices.class?.level)||1)),choices=state.c.choices.houseAbilities||(state.c.choices.houseAbilities={}),species=(state.catalogs.species||[]).find(x=>x.id===state.c.refs?.species);if(!species)return;for(const milestone of HOUSE_ABILITY_LEVELS){if(milestone>level)continue;const ability=choices[String(milestone)]||choices[milestone];if(AB.includes(ability))species.abilityBonuses.push({ability,bonus:1,source:'Regra da Casa',level:milestone})}}
export function applyHouseRules(){if(!state.c||!state.catalogs)return;prepareClasses();migrateSelectedProgressionSlots();prepareBackgroundCatalogs();applyHouseAbilityBonuses()}
export function compatible(k){return(state.catalogs[k]||[]).filter(isCompatible55)}
export function selected(){applyHouseRules();syncSorcererSpellAccess();return base.selected()}
function selectedSubclassName(){const sub=(state.catalogs.subclasses||[]).find(x=>x.id===state.c?.refs?.subclass);return fold(sub?.mechanics?.name||sub?.name)}
export function trainedArmor(k,a){if(base.trainedArmor(k,a))return true;if(!a)return true;const category=fold(a.categoria),name=selectedSubclassName();if(k?.slug==='artificer'&&category==='pesada')return name==='armorer'||name==='armeiro';if(k?.slug==='bard'&&category==='media')return['college of valor','colegio do valor','college of swords','colegio das espadas'].includes(name);if(k?.slug==='warlock'&&category==='media')return name==='the hexblade';if(k?.slug==='wizard'&&category==='leve')return name==='bladesinging';return false}
export function shieldTraining(k){if(base.shieldTraining(k))return true;const name=selectedSubclassName();if(k?.slug==='bard')return name==='college of valor'||name==='colegio do valor';if(k?.slug==='warlock')return name==='the hexblade';return false}
function currentLineagePackage(){const species=(state.catalogs.species||[]).find(x=>x.id===state.c?.refs?.species)||null,lineage=species?.lineages?.find(x=>x.name===state.c?.choices?.species?.lineage)||null;return{species,lineage}}
function withLineagePackage(fn){const{species,lineage}=currentLineagePackage();if(!species||!lineage)return fn();const replaceAll=!!lineage.replaceBaseTraits,replaceNames=new Set(arr(lineage.replaceTraitNames).map(fold));if(!replaceAll&&!replaceNames.size)return fn();const originalSpeciesTraits=species.traits,originalLineageTraits=lineage.traits,originalSpeed=species.speed,originalSizes=species.sizes;if(replaceAll){species.traits=arr(lineage.traits);lineage.traits=[]}else species.traits=arr(species.traits).filter(t=>!replaceNames.has(fold(t?.originalName||t?.name||''))&&!replaceNames.has(fold(t?.name||'')));if(num(lineage.speed))species.speed=num(lineage.speed);if(arr(lineage.sizes).length)species.sizes=[...lineage.sizes];try{return fn()}finally{species.traits=originalSpeciesTraits;lineage.traits=originalLineageTraits;species.speed=originalSpeed;species.sizes=originalSizes}}
function withLegacyCompatibility(fn){const changed=[];for(const key of['species','backgrounds','subclasses','feats'])for(const x of state.catalogs[key]||[])if(x.ruleset==='5e'&&isCompatible55(x)){changed.push(x);x.ruleset='5.5e'}try{return fn()}finally{for(const x of changed)x.ruleset='5e'}}
function withSupplementalOriginFeats(fn){const grants=arr(invocationOutcome().originFeatIds),klass=(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class);if(!grants.length||!klass||!state.c?.choices)return fn();const progression=klass._houseFeatProgression,choices=state.c.choices.feats||(state.c.choices.feats={}),saved={};klass._houseFeatProgression=[...arr(progression)];grants.forEach((id,index)=>{const slot=`supplemental-origin-${index}`;saved[slot]=Object.prototype.hasOwnProperty.call(choices,slot)?choices[slot]:undefined;choices[slot]=id;klass._houseFeatProgression.push({level:1,kind:'invocation',slot,index,source:'Invocação Mística · Lessons of the First Ones'})});try{return fn()}finally{klass._houseFeatProgression=progression;for(const[id,value]of Object.entries(saved)){if(value===undefined)delete choices[id];else choices[id]=value}}}
export function speciesTraitChoiceDefs(speciesArg=null,lineageArg=null){applyHouseRules();return withLineagePackage(()=>base.speciesTraitChoiceDefs(speciesArg,lineageArg))}
export function sanitizeSpeciesTraitChoices(){applyHouseRules();return withLineagePackage(()=>base.sanitizeSpeciesTraitChoices())}
export function sanitizeSelections(){applyHouseRules();syncSorcererSpellAccess();const result=withLineagePackage(()=>withLegacyCompatibility(()=>base.sanitizeSelections()));sanitizeWarlockInvocations();sanitizeSorcererMetamagic();const klass=(state.catalogs.classes||[]).find(x=>x.id===state.c?.refs?.class)||null;state.c.choices.classTools=sanitizeClassToolChoices(klass,state.c.choices.classTools||{});sanitizeTashaFeatChoices();applyHouseRules();return result}
function isReplacedClassFeat(feature){if(!STANDARD_CLASS_FEAT_LEVELS.has(num(feature?.level)))return false;const name=fold(feature?.name||'');return/ability score improvement|melhoria.*atribut|aumento.*atribut/.test(name)}
function sourceForInstance(inst,klass){if(inst.key==='background')return'Talento de Origem · Antecedente';if(!inst.key?.startsWith('class:'))return inst.source;const slot=inst.key.slice(6),entry=arr(klass?._houseFeatProgression).find(x=>x.slot===slot);if(!entry)return inst.source;if(entry.kind==='invocation')return entry.source||'Invocação Mística · Lessons of the First Ones';return entry.kind==='house'?`Regra da Casa · nível ${entry.level}`:`Classe · nível ${entry.level} · talento adicional`}
function applyLineagePackageEffects(d){const fixed=arr(d.lineage?.fixedSkills);if(fixed.length){d.skills=uniq([...arr(d.skills),...fixed]);d.expertiseSkills=uniq(arr(d.expertiseSkills).filter(x=>d.skills.includes(x)));d.passive=10+mod(d.scores.Sabedoria)+(d.skills.includes('Percepção')?d.pbonus:0)+(d.expertiseSkills.includes('Percepção')?d.pbonus:0)}const ability=d.lineage?.spellAbilityFixed;if(ability&&!d.speciesSpellAbility&&d.scores?.[ability]!=null){const m=mod(d.scores[ability]);d.speciesSpellAbility=ability;d.speciesSpellDC=8+d.pbonus+m;d.speciesSpellAttack=d.pbonus+m}return d}
function applyInvocationEffects(d){const outcome=invocationOutcome();d.invocationMechanics=outcome;d.invocations=outcome.selected.map(x=>({slot:x.slot,id:x.invocation.id,name:x.invocation.nome,choice:x.choice}));d.invocationSpells=outcome.spellGrants;d.invocationFlags=outcome.flags;d.cantripInvocationModifiers=outcome.cantripModifiers;d.invocationSenses={...outcome.senses};d.waterBreathing=!!outcome.waterBreathing;if(outcome.swimEqualSpeed)d.swimSpeed=d.speed;d.pactWeaponAttacks=outcome.pactWeaponAttacks;if(d.weapon&&outcome.pactWeaponId===d.weapon.id){d.wprof=true;if(outcome.pactWeaponUsesCharisma){d.wAbility='Carisma';d.attack=mod(d.scores.Carisma)+d.pbonus}d.pactWeaponDamageTypes=[...outcome.pactWeaponDamageTypes]}return d}
function applyMetamagicEffects(d){const outcome=metamagicOutcome();d.metamagicClass=outcome;d.metamagicOptions=uniq([...arr(d.metamagicOptions),...outcome.options.map(x=>x.option.id)]);d.sorceryPoints=outcome.sorceryPoints;return d}
function applyClassToolEffects(d){const outcome=classToolOutcome(d.klass,state.c.choices?.classTools||{});d.classToolMechanics=outcome;d.tools=uniq([...arr(d.tools),...arr(outcome.tools)]);return d}
export function applyBarbarianCoreMechanics(d){if(d?.klass?.slug!=='barbarian')return d;const l=num(d.level),unarmored=!d.armor,heavy=fold(d?.armor?.categoria||'').includes('pesada'),shield=state.c?.choices?.equipment?.shield?2:0,mechanics={unarmoredDefense:false,attacksPerAttackAction:Math.max(1,num(d.attacksPerAttackAction)||1),fastMovement:0,initiativeAdvantage:false,primalChampion:false};if(unarmored){const candidate=10+mod(d.scores?.Destreza)+mod(d.scores?.Constituição)+shield;d.ac=Math.max(num(d.ac),candidate);mechanics.unarmoredDefense=true;mechanics.unarmoredDefenseAC=candidate}if(l>=5){d.attacksPerAttackAction=Math.max(mechanics.attacksPerAttackAction,2);mechanics.attacksPerAttackAction=d.attacksPerAttackAction;if(!heavy){d.speed=num(d.speed)+10;mechanics.fastMovement=10}}if(l>=7){d.initiativeAdvantage=true;mechanics.initiativeAdvantage=true}if(l>=20){const oldStr=mod(d.scores?.Força),oldCon=mod(d.scores?.Constituição);d.scores.Força=Math.min(25,num(d.scores.Força)+4);d.scores.Constituição=Math.min(25,num(d.scores.Constituição)+4);const strDelta=mod(d.scores.Força)-oldStr,conDelta=mod(d.scores.Constituição)-oldCon;if(d.wAbility==='Força'&&d.attack!=null)d.attack=num(d.attack)+strDelta;if(d.hp!=null)d.hp=num(d.hp)+conDelta*l;if(unarmored){const candidate=10+mod(d.scores?.Destreza)+mod(d.scores?.Constituição)+shield;d.ac=Math.max(num(d.ac),candidate);mechanics.unarmoredDefenseAC=candidate}mechanics.primalChampion={strength:d.scores.Força,constitution:d.scores.Constituição,strengthModifierDelta:strDelta,constitutionModifierDelta:conDelta}}d.barbarianCoreMechanics=mechanics;return d}
export function derive(){applyHouseRules();syncSorcererSpellAccess();let d=applyLineagePackageEffects(withLineagePackage(()=>withSupplementalOriginFeats(()=>base.derive())));d=applyInvocationEffects(d);d=applyMetamagicEffects(d);d=applyClassToolEffects(d);d=applyTashaFeatEffects(d);d=applyBarbarianCoreMechanics(d);applyBarbarianSubclassMechanics(d);applyArtificerSubclassMechanics(d);applyBardSubclassMechanics(d);applyDruidSubclassMechanics(d);applyFighterSubclassMechanics(d);applyFighterSubclassRuleDetails(d);applyMonkSubclassMechanics(d);applyMonkSubclassRuleDetails(d);applyPaladinSubclassMechanics(d);applyPaladinSubclassRuleDetails(d);applyRangerSubclassMechanics(d);applyRangerSubclassRuleDetails(d);applyRogueSubclassMechanics(d);applySorcererSubclassMechanics(d);applyWarlockSubclassMechanics(d);applyWizardSubclassMechanics(d);d.classFeatures=arr(d.classFeatures).filter(feature=>!isReplacedClassFeat(feature));d.houseFeatProgression=arr(d.klass?._houseFeatProgression).filter(entry=>entry.level<=d.level).map(entry=>({...entry}));const choices=state.c.choices.houseAbilities||{};d.houseAbilityProgression=HOUSE_ABILITY_LEVELS.filter(level=>level<=d.level).map(level=>({level,ability:choices[String(level)]||choices[level]||null}));if(d.featMechanics){d.featMechanics.instances=arr(d.featMechanics.instances).map(inst=>({...inst,source:sourceForInstance(inst,d.klass)}));d.featMechanics.houseAbilityProgression=d.houseAbilityProgression}d=applyMagicItemPersistentEffects(d,state.c,ownedEquipment({includeCampaign:false}).all);const skillChecks=deriveSkillCheckMechanics(d);d.skillChecks=skillChecks.checks;d.jackOfAllTrades=skillChecks.jackOfAllTrades;d.passive=skillChecks.passivePerception;return d}
/* Compatibilidade das auditorias mecânicas do módulo-base:
subclassLevel trainedArmor spellProgress spellOptions k.hitDie+con
speciesTraitChoiceDefs sanitizeSpeciesTraitChoices spellCreditState
*/