import{state,arr,num,slug,json}from'./state.js';
const BASE='https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/main/data';
const REMOTE=[['XPHB',`${BASE}/spells/spells-xphb.json`,20240917],['XGE',`${BASE}/spells/spells-xge.json`,20171121],['TCE',`${BASE}/spells/spells-tce.json`,20201117],['FRHoF',`${BASE}/spells/spells-frhof.json`,20251101],['EFA',`${BASE}/spells/spells-efa.json`,20251209]];
const LOOKUP=`${BASE}/generated/gendata-spell-source-lookup.json`;
const SCHOOL={A:'Abjuração',C:'Conjuração',D:'Adivinhação',E:'Encantamento',V:'Evocação',I:'Ilusão',N:'Necromancia',T:'Transmutação'};
const CLASS_PT={Artificer:'Artífice',Bard:'Bardo',Cleric:'Clérigo',Druid:'Druida',Paladin:'Paladino',Ranger:'Patrulheiro',Sorcerer:'Feiticeiro',Warlock:'Bruxo',Wizard:'Mago',Fighter:'Guerreiro',Rogue:'Ladino',Monk:'Monge',Barbarian:'Bárbaro'};
const META={XPHB:{source:"Player's Handbook (2024)",ruleset:'5.5e',revision:2024},XGE:{source:"Xanathar's Guide to Everything",ruleset:'5e',revision:2014},TCE:{source:"Tasha's Cauldron of Everything",ruleset:'5e',revision:2014},FRHoF:{source:'Forgotten Realms: Heroes of Faerûn',ruleset:'5.5e',revision:2024},EFA:{source:'Eberron: Forge of the Artificer',ruleset:'5.5e',revision:2024}};
const key=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,' ').trim().toLowerCase();
function normalize(x){return{id:`magias:2024:${x.id||slug(x.nome_original||x.nome||x.name)}`,name:x.nome||x.nome_original||x.name,originalName:x.nome_original||x.name||x.nome,level:num(x.nivel??x.level),school:x.escola||x.school||'',classes:arr(x.classes_base||x.classes),source:x.fonte||x.source||'',description:x.descricao||'',concentration:!!x.concentracao,ritual:!!x.ritual,ruleset:x.ruleset||'',revision:x.revisao_core??x.revision??null,effectType:x.tipo_efeito||x.effectType||'',damageType:x.tipo_dano||x.damageType||'',range:typeof(x.alcance??x.range)==='string'?(x.alcance??x.range):'',attackSave:x.ataque_salvaguarda||x.attackSave||''}}
function lookupClasses(lookup,source,name){const roots=[lookup?.[String(source||'').toLowerCase()]?.[String(name||'').toLowerCase()],lookup?.phb?.[String(name||'').toLowerCase()]].filter(Boolean),found=new Set;for(const node of roots)for(const bucket of['class','classVariant'])for(const cmap of Object.values(node?.[bucket]||{}))if(cmap&&typeof cmap==='object')for(const cls of Object.keys(cmap))found.add(CLASS_PT[cls]||cls);return[...found]}
async function remoteConsolidated(){const[sourceData,lookup,local]=await Promise.all([Promise.all(REMOTE.map(async([src,url,priority])=>[src,priority,await json(url)])),json(LOOKUP),json('dados/magias-suplementos-locais.json').catch(()=>({fontes:{},itens:[]}))]),groups=new Map;for(const[src,priority,data]of sourceData)for(const s of arr(data.spell)){const k=key(s.name);if(!groups.has(k))groups.set(k,[]);groups.get(k).push({src,priority,s})}const out=[];for(const rows of groups.values()){rows.sort((a,b)=>b.priority-a.priority);const{src,s}=rows[0],meta=META[src];out.push(normalize({name:s.name,level:s.level,school:SCHOOL[s.school]||s.school,classes:lookupClasses(lookup,src,s.name),source:meta.source,ruleset:meta.ruleset,revision:meta.revision,concentracao:arr(s.duration).some(d=>d?.concentration),ritual:!!s.meta?.ritual}))}const official=new Set(out.map(x=>key(x.originalName)));for(const x of arr(local.itens)){if(official.has(key(x.nome_original||x.nome)))continue;out.push(normalize(x))}return out.sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,'pt-BR'))}
export async function loadSpells(){try{const d=await json('dados/magias-catalogo.json?v=20260821-unified1'),items=arr(d.itens).map(normalize);if(!items.length)throw new Error('catálogo consolidado vazio');return items.sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,'pt-BR'))}catch(e){state.warnings.push(`Catálogo consolidado local indisponível: ${e.message}. Usando a mesma consolidação remota da Biblioteca.`);try{return await remoteConsolidated()}catch(remoteError){state.warnings.push(`Consolidação remota de Magias: ${remoteError.message}`);const d=await json('dados/magias-srd.json').catch(()=>({itens:[]}));return arr(d.itens).map(normalize).sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,'pt-BR'))}}}
