export const KEY='hub-rpg:characters:v2',LEGACY_KEY='hub-rpg:characters:v1',V='20260821-character-builder2',PIN='bfd3db4bcc31699cce703b46feb9af3f0ff08999';
export const RAW24=`https://raw.githubusercontent.com/5e-bits/5e-database/${PIN}/src/2024/en`,RAW14=`https://raw.githubusercontent.com/5e-bits/5e-database/${PIN}/src/2014/en`;
export const AB=['Força','Destreza','Constituição','Inteligência','Sabedoria','Carisma'];
export const ABKEY={STR:'Força',DEX:'Destreza',CON:'Constituição',INT:'Inteligência',WIS:'Sabedoria',CHA:'Carisma',Strength:'Força',Dexterity:'Destreza',Constitution:'Constituição',Intelligence:'Inteligência',Wisdom:'Sabedoria',Charisma:'Carisma'};
export const SKILL_AB={'Acrobacia':'Destreza','Adestrar Animais':'Sabedoria','Arcanismo':'Inteligência','Atletismo':'Força','Atuação':'Carisma','Enganação':'Carisma','Furtividade':'Destreza','História':'Inteligência','Intimidação':'Carisma','Intuição':'Sabedoria','Investigação':'Inteligência','Medicina':'Sabedoria','Natureza':'Inteligência','Percepção':'Sabedoria','Persuasão':'Carisma','Prestidigitação':'Destreza','Religião':'Inteligência','Sobrevivência':'Sabedoria'};
export const CLASS_SLUGS=['barbarian','bard','cleric','druid','fighter','monk','paladin','ranger','rogue','sorcerer','warlock','wizard'];
export const LOCFILES={barbarian:'barbaro',bard:'bardo',cleric:'clerigo',druid:'druida',fighter:'guerreiro',monk:'monge',paladin:'paladino',ranger:'patrulheiro',rogue:'ladino',sorcerer:'feiticeiro',warlock:'bruxo',wizard:'mago'};
export const BGFILES=['dados/antecedentes-srd-5.2.1.json','dados/antecedentes-abertos-adicionais.json','dados/antecedentes-pdf-phb-2024.json','dados/antecedentes-pdf-forge-2025.json','dados/antecedentes-pdf-heroes-2025.json','dados/antecedentes-pdf-quickstone-2024.json'];
export const SPFILES=['dados/especies-pdf-phb-2024.json','dados/especies-pdf-forge-2025.json','dados/especies-pdf-quickstone-2024.json','dados/especies-pdf-motm-2022.json'];
export const state={catalogs:{classes:[],species:[],backgrounds:[],subclasses:[],feats:[],armors:[],weapons:[]},c:null,warnings:[],G:{},LOCSP:{}};
export const $=id=>document.getElementById(id),arr=v=>Array.isArray(v)?v:[],num=v=>Number.isFinite(Number(v))?Number(v):0,uniq=a=>[...new Set(a.filter(Boolean))];
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const fold=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),slug=s=>fold(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const mod=s=>Math.floor((num(s)-10)/2),sign=n=>`${n>=0?'+':''}${n}`,pb=l=>2+Math.floor((Math.max(1,num(l))-1)/4);
export async function json(u){const r=await fetch(`${u}${u.includes('?')?'&':'?'}v=${V}`,{cache:'no-store'});if(!r.ok)throw new Error(`${u}: HTTP ${r.status}`);return r.json()}
export function t(v){if(v==null)return'';let s=String(v);for(const d of [state.G.classes,state.G.atributos,state.G.pericias,state.G.condicoes,state.G.danos,state.G.tamanhos,state.G.tipos_criatura,state.G.acoes,state.G.regras,state.G.armas,state.G.armaduras])for(const[k,val]of Object.entries(d||{}))s=s.replace(new RegExp(`\\b${k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'g'),val);return ABKEY[s]||s}
function uid(){return crypto?.randomUUID?.()||`pc-${Date.now()}-${Math.random().toString(16).slice(2)}`}
export function blank(){return{schema:'hub-rpg/personagem/v2',id:uid(),name:'',ruleset:'5.5e',refs:{class:null,species:null,background:null,subclass:null},refSnapshots:{},baseAbilities:Object.fromEntries(AB.map(a=>[a,10])),choices:{class:{level:1,skills:[],hpMode:'average',hpRolls:{}},species:{size:null,lineage:null},background:{abilityMode:'2+1',plus2:null,plus1:null,equipment:'A',toolChoice:''},feats:{},equipment:{armor:null,shield:false,weapon:null}},updatedAt:new Date().toISOString()}}
export function read(){try{const a=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(a))return a;const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');return Array.isArray(old)?old:[]}catch{return[]}}
export function write(a){localStorage.setItem(KEY,JSON.stringify(a))}
export function loadCharacter(){const id=new URLSearchParams(location.search).get('id'),saved=id?read().find(x=>x.id===id):null,c=saved?structuredClone(saved):blank();c.schema='hub-rpg/personagem/v2';c.ruleset=c.ruleset||'5.5e';c.refs={class:null,species:null,background:null,subclass:null,...(c.refs||{})};c.refSnapshots=c.refSnapshots||{};c.baseAbilities={...Object.fromEntries(AB.map(a=>[a,10])),...(c.baseAbilities||{})};c.choices=c.choices||{};c.choices.class={level:1,skills:[],hpMode:'average',hpRolls:{},...(c.choices.class||{})};c.choices.species={size:null,lineage:null,...(c.choices.species||{})};c.choices.background={abilityMode:'2+1',plus2:null,plus1:null,equipment:'A',toolChoice:'',...(c.choices.background||{})};c.choices.feats=c.choices.feats||{};c.choices.equipment={armor:null,shield:false,weapon:null,...(c.choices.equipment||{})};return c}
