import{state,$,arr,num,esc}from'./state.js';
import{ARTISAN_TOOLS}from'./class-tool-mechanics.js?v=20260831-class-tools1';
import{loadInvocations}from'./invocation-catalog.js?v=20260831-warlock-invocations2';
import{loadMetamagic}from'./metamagic-catalog.js?v=20260831-tasha-metamagic1';
import{invocationChoicePool,invocationEligibleOptions}from'./invocation-mechanics.js?v=20260831-tasha-metamagic1';
import{activeTashaFeatInstances,artificerInitiateSpellPool,FIGHTING_STYLE_NAMES,sanitizeTashaFeatChoices,tashaFeatMissingChoices}from'./tasha-feat-mechanics.js?v=20260831-tasha-metamagic1';

let initialized=false,rendering=false,scheduled=false,loading=null;
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;render()})}
function store(){state.c.choices.tashaFeatMechanics=state.c.choices.tashaFeatMechanics||{};return state.c.choices.tashaFeatMechanics}
function featCard(box,key){return[...box.querySelectorAll('[data-feat-instance-card]')].find(card=>card.dataset.featInstanceCard===key)||null}
function option(value,label,current,disabled=false){return`<option value="${esc(value)}" ${value===current?'selected':''} ${disabled?'disabled':''}>${esc(label)}</option>`}
function labelFor(x){return x?.nome||x?.name||x?.originalName||x?.id||''}
async function ensureCatalogs(){if(loading)return loading;const jobs=[];if(arr(state.catalogs.invocations).length!==28)jobs.push(loadInvocations().then(d=>{state.catalogs.invocations=d.items;state.catalogs.invocationProgression=d.progression}));if(arr(state.catalogs.metamagic).length!==10)jobs.push(loadMetamagic().then(d=>{state.catalogs.metamagic=d.items;state.catalogs.metamagicProgression=d.progression}));if(!jobs.length)return true;loading=Promise.all(jobs).then(()=>true).catch(error=>{state.warnings.push(`Talentos Tasha: ${error.message||error}`);return false}).finally(()=>{loading=null});return loading}
function simpleSelect(label,field,instance,rows,current){return`<label class="trait-choice"><strong>${esc(label)}</strong><select data-tasha-simple="${esc(field)}" data-instance="${esc(instance)}"><option value="">Selecione</option>${arr(rows).map(x=>option(x.id,labelFor(x),current)).join('')}</select></label>`}
function renderArtificer(inst,data){const can=artificerInitiateSpellPool(0),lvl=artificerInitiateSpellPool(1);return`<div data-tasha-feat-control="${esc(inst.key)}"><label class="trait-choice"><strong>Ferramenta de artesão</strong><select data-tasha-simple="tool" data-instance="${esc(inst.key)}"><option value="">Selecione</option>${ARTISAN_TOOLS.map(x=>option(x,x,data.tool)).join('')}</select></label>${simpleSelect('Truque de Artífice','cantripId',inst.key,can,data.cantripId)}${simpleSelect('Magia de 1º nível de Artífice','spellId',inst.key,lvl,data.spellId)}</div>`}
function invocationChoiceHtml(instance,inv,choice){const type=inv?.escolha?.tipo;if(!type)return'';const pool=invocationChoicePool(inv);if(['cantrip_bruxo_dano','cantrip_bruxo_dano_alcance','cantrip_bruxo_ataque'].includes(type))return simpleSelect('Truque de Bruxo','invocation.cantripId',instance,pool,choice?.cantripId);if(type==='arma_pacto')return simpleSelect('Arma de Pacto','invocation.weaponId',instance,pool,choice?.weaponId);if(type==='talento_origem')return simpleSelect('Talento de Origem','invocation.featId',instance,pool,choice?.featId);if(type==='pact_tome_spells'){const chosenCan=arr(choice?.cantrips),chosenRit=arr(choice?.rituals);return`<div class="choice-grid"><label>3 truques<select multiple size="7" data-tasha-invocation-list="cantrips" data-instance="${esc(instance)}">${arr(pool.cantrips).map(x=>option(x.id,labelFor(x),chosenCan.includes(x.id)?x.id:'' )).join('').replaceAll('selected>','selected>')}</select></label><label>2 rituais de 1º nível<select multiple size="7" data-tasha-invocation-list="rituals" data-instance="${esc(instance)}">${arr(pool.rituals).map(x=>`<option value="${esc(x.id)}" ${chosenRit.includes(x.id)?'selected':''}>${esc(labelFor(x))}</option>`).join('')}</select></label></div>`}return''}
function renderEldritch(inst,data){const slot=data.invocation||{id:'',choice:null},eligible=invocationEligibleOptions({consumer:'feat',slots:[slot]}),current=state.catalogs.invocations.find(x=>x.id===slot.id)||null,options=state.catalogs.invocations.filter(x=>eligible.some(y=>y.id===x.id)||x.id===slot.id);return`<div data-tasha-feat-control="${esc(inst.key)}"><label class="trait-choice"><strong>Invocação Mística</strong><select data-tasha-simple="invocation.id" data-instance="${esc(inst.key)}"><option value="">Selecione</option>${options.map(x=>option(x.id,x.nome,slot.id)).join('')}</select></label>${current?invocationChoiceHtml(inst.key,current,slot.choice):''}</div>`}
function renderFighting(inst,data){return`<div data-tasha-feat-control="${esc(inst.key)}"><label class="trait-choice"><strong>Estilo de Luta</strong><select data-tasha-simple="style" data-instance="${esc(inst.key)}"><option value="">Selecione</option>${FIGHTING_STYLE_NAMES.map(x=>option(x,x,data.style)).join('')}</select></label></div>`}
function renderMetamagic(inst,data){const ids=arr(data.metamagicIds),chosen=new Set(ids.filter(Boolean));return`<div data-tasha-feat-control="${esc(inst.key)}"><strong>Metamagia</strong><div class="choice-grid">${[0,1].map(i=>`<label>Opção ${i+1}<select data-tasha-metamagic="${i}" data-instance="${esc(inst.key)}"><option value="">Selecione</option>${state.catalogs.metamagic.map(x=>option(x.id,`${x.nome} · ${x.custo} PF`,ids[i]||'',chosen.has(x.id)&&ids[i]!==x.id)).join('')}</select></label>`).join('')}</div></div>`}
function syncPending(){const box=$('pending');if(!box)return;box.querySelectorAll('[data-tasha-feat-pending]').forEach(x=>x.remove());const missing=tashaFeatMissingChoices();if(!missing.length)return;box.className='status warning';let ul=box.querySelector('ul');if(!ul){box.innerHTML='<strong>Escolhas pendentes</strong><ul></ul>';ul=box.querySelector('ul')}for(const text of missing){const li=document.createElement('li');li.dataset.tashaFeatPending='1';li.textContent=text;ul.appendChild(li)}}
function render(){if(rendering||!state.c)return;const box=$('talentos-escolhas');if(!box)return;rendering=true;try{for(const old of box.querySelectorAll('[data-tasha-feat-control]'))old.remove();sanitizeTashaFeatChoices();const data=store();for(const inst of activeTashaFeatInstances()){if(inst.feat.name==='Gunner')continue;const card=featCard(box,inst.key);if(!card)continue;let html='';if(inst.feat.name==='Artificer Initiate')html=renderArtificer(inst,data[inst.key]||{});else if(inst.feat.name==='Eldritch Adept')html=renderEldritch(inst,data[inst.key]||{});else if(inst.feat.name==='Fighting Initiate')html=renderFighting(inst,data[inst.key]||{});else if(inst.feat.name==='Metamagic Adept')html=renderMetamagic(inst,data[inst.key]||{});if(html)card.insertAdjacentHTML('beforeend',html)}syncPending()}finally{rendering=false}}
function refresh(){sanitizeTashaFeatChoices();$('nome')?.dispatchEvent(new Event('input'));document.dispatchEvent(new CustomEvent('hub:tasha-feat-mechanics-changed'));schedule()}
function setPath(instance,path,value){const data=store(),row=data[instance]||(data[instance]={});if(path==='tool'||path==='cantripId'||path==='spellId'||path==='style')row[path]=value||null;else if(path==='invocation.id'){row.invocation={id:value||'',choice:null}}else if(path.startsWith('invocation.')){row.invocation=row.invocation||{id:'',choice:null};row.invocation.choice=row.invocation.choice||{};row.invocation.choice[path.split('.')[1]]=value||null}}
function onChange(e){const instance=e.target?.dataset?.instance;if(!instance)return;if(e.target.dataset.tashaSimple){setPath(instance,e.target.dataset.tashaSimple,e.target.value);refresh();return}if(e.target.dataset.tashaMetamagic!=null){const data=store(),row=data[instance]||(data[instance]={}),ids=arr(row.metamagicIds).slice(),index=num(e.target.dataset.tashaMetamagic);ids[index]=e.target.value||null;row.metamagicIds=ids;refresh();return}if(e.target.dataset.tashaInvocationList){const data=store(),row=data[instance]||(data[instance]={});row.invocation=row.invocation||{id:'',choice:{}};row.invocation.choice=row.invocation.choice||{};row.invocation.choice[e.target.dataset.tashaInvocationList]=[...e.target.selectedOptions].map(x=>x.value).slice(0,e.target.dataset.tashaInvocationList==='cantrips'?3:2);refresh()}}
export function initTashaFeatUi(){if(initialized)return;initialized=true;const box=$('talentos-escolhas');if(!box)return;box.addEventListener('change',onChange);new MutationObserver(()=>{if(!rendering)schedule()}).observe(box,{childList:true,subtree:true});const pending=$('pending');if(pending)new MutationObserver(()=>{if(!rendering)queueMicrotask(syncPending)}).observe(pending,{childList:true,subtree:true});for(const event of['hub:progression-context-changed','hub:origin-context-changed','hub:class-feature-feat-changed','hub:spell-selection-changed','hub:warlock-invocation-catalog-ready','hub:metamagic-catalog-ready'])document.addEventListener(event,schedule);ensureCatalogs().then(()=>schedule());schedule()}
