import{state,$,esc,fold,json}from'./state.js';

let DATA=null,rendering=false,queued=false;
const choice=()=>state.c?.choices?.species||(state.c.choices.species={size:null,lineage:null});
const currentSpecies=()=>state.catalogs.species.find(x=>x.id===state.c?.refs?.species)||null;
const isTiefling=()=>fold(currentSpecies()?.name)==='tiefling';
const byId=(rows,id)=>rows?.find(x=>x.id===id)||null;

function groups(rows){const map=new Map;for(const row of rows||[]){const key=row.grupo||'Outras';if(!map.has(key))map.set(key,[]);map.get(key).push(row)}return[...map.entries()]}
function mechanicalOptions(current){return`<option value="">Selecione</option>`+groups(DATA?.mecanicas).map(([group,rows])=>`<optgroup label="${esc(group)}">${rows.map(x=>`<option value="${esc(x.id)}" ${x.id===current?'selected':''}>${esc(x.nome)}${x.ruleset==='5e'?' · legado 5e':''}</option>`).join('')}</optgroup>`).join('')}
function eberronOptions(current){return`<option value="">Nenhuma / outro cenário</option>`+(DATA?.eberron||[]).map(x=>`<option value="${esc(x.id)}" ${x.id===current?'selected':''}>${esc(x.nome)}</option>`).join('')}
function mechanicSummary(v){if(!v)return'<p class="mini">Escolha um legado ou variante mecânica.</p>';const rows=[v.resistencia?`<p><strong>Resistência:</strong> ${esc(v.resistencia)}</p>`:'',v.nivel1?`<p><strong>Nível 1:</strong> ${esc(v.nivel1)}</p>`:'',v.nivel3&&v.nivel3!=='—'?`<p><strong>Nível 3:</strong> ${esc(v.nivel3)}</p>`:'',v.nivel5&&v.nivel5!=='—'?`<p><strong>Nível 5:</strong> ${esc(v.nivel5)}</p>`:'',v.atributo_conjuracao&&v.atributo_conjuracao!=='—'?`<p><strong>Conjuração:</strong> ${esc(v.atributo_conjuracao)}</p>`:'',v.nota_compatibilidade?`<p class="mini">${esc(v.nota_compatibilidade)}</p>`:''].join('');return`<div class="preview-block"><strong>${esc(v.nome)}${v.ruleset==='5e'?' — legado compatível':''}</strong>${rows}</div>`}
function originSummary(v){return v?`<div class="preview-block"><strong>Origem de Eberron: ${esc(v.nome)}</strong><p>${esc(v.descricao)}</p><p class="mini">Origem narrativa: não substitui o legado mecânico escolhido acima.</p></div>`:''}
function renderSheet(){const host=$('species-features');if(!host)return;host.querySelector('[data-tiefling-sheet]')?.remove();if(!isTiefling())return;const c=choice(),mech=byId(DATA?.mecanicas,c.tieflingVariant),origin=byId(DATA?.eberron,c.tieflingOrigin);if(!mech&&!origin)return;const wrap=document.createElement('div');wrap.dataset.tieflingSheet='';wrap.className='feature';wrap.innerHTML=`<p><strong>Legado / variante:</strong> ${mech?esc(mech.nome):'—'}</p>${mech?`<p>${esc([mech.nivel1,mech.nivel3!=='—'?mech.nivel3:'',mech.nivel5!=='—'?mech.nivel5:''].filter(Boolean).join(' '))}</p>`:''}${origin?`<p><strong>Eberron:</strong> ${esc(origin.nome)} — ${esc(origin.descricao)}</p>`:''}`;host.prepend(wrap)}
function render(){if(rendering||!DATA)return;rendering=true;try{const box=$('especie-escolhas');if(!box)return;box.querySelector('[data-tiefling-controls]')?.remove();if(!isTiefling()){renderSheet();return}const c=choice(),mech=byId(DATA.mecanicas,c.tieflingVariant),origin=byId(DATA.eberron,c.tieflingOrigin),wrap=document.createElement('fieldset');wrap.dataset.tieflingControls='';wrap.innerHTML=`<legend>Legado / variante de Tiefling</legend><label>Legado ou variante mecânica<select data-tiefling-mechanic>${mechanicalOptions(c.tieflingVariant)}</select></label><label>Origem de Eberron (opcional)<select data-tiefling-origin>${eberronOptions(c.tieflingOrigin)}</select></label>${mechanicSummary(mech)}${originSummary(origin)}`;box.appendChild(wrap);renderSheet()}finally{rendering=false}}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;render()})}
function bind(){const box=$('especie-escolhas');box?.addEventListener('change',e=>{if(e.target.matches('[data-tiefling-mechanic]')){choice().tieflingVariant=e.target.value||null;render();return}if(e.target.matches('[data-tiefling-origin]')){choice().tieflingOrigin=e.target.value||null;render()}});const species=$('especie');species?.addEventListener('change',()=>queueMicrotask(schedule));if(species)new MutationObserver(schedule).observe(species,{childList:true,subtree:true});$('nivel')?.addEventListener('change',()=>queueMicrotask(schedule));$('new-character')?.addEventListener('click',()=>queueMicrotask(schedule));setTimeout(schedule,500);setTimeout(schedule,2500)}
export async function initTieflingUi(){try{DATA=await json('dados/tiefling-variantes.json')}catch(error){console.error('[tiefling-ui]',error);return}render();bind()}
