export const ADVENTURE_KEY='hub-rpg:adventures:v1';
export const ADVENTURE_SCHEMA='hub-rpg/adventure/v1';
export const ADVENTURE_STATUS=Object.freeze(['planned','active','completed','archived']);
export const SCENE_STATUS=Object.freeze(['planned','active','completed','skipped']);
export const CLUE_STATUS=Object.freeze(['hidden','discovered','resolved']);
export const TREASURE_STATUS=Object.freeze(['planned','found','claimed']);
const ADV_STATUS=new Set(ADVENTURE_STATUS),SCN_STATUS=new Set(SCENE_STATUS),CLUE_ST=new Set(CLUE_STATUS),TREASURE_ST=new Set(TREASURE_STATUS);
const text=v=>String(v??'').trim();
const arr=v=>Array.isArray(v)?v:[];
const now=()=>new Date().toISOString();
const uniq=v=>[...new Set(arr(v).map(text).filter(Boolean))];
const uid=prefix=>globalThis.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const copy=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function stamp(row={},prefix){return{id:text(row.id)||uid(prefix),createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
function sanitizeChapter(row={},index=0){return{...stamp(row,'chapter'),title:text(row.title)||`Capítulo ${index+1}`,arc:String(row.arc??''),status:['planned','active','completed'].includes(row.status)?row.status:'planned',summary:String(row.summary??''),notes:String(row.notes??''),order:Math.max(1,Math.floor(Number(row.order)||index+1))}}
function sanitizeLocation(row={}){return{...stamp(row,'location'),name:text(row.name)||'Local',type:String(row.type??''),description:String(row.description??''),notes:String(row.notes??'')}}
function sanitizeNpc(row={}){return{...stamp(row,'npc'),name:text(row.name)||'NPC',role:String(row.role??''),description:String(row.description??''),notes:String(row.notes??''),monsterId:text(row.monsterId)||null,source:String(row.source??'')}}
function sanitizeClue(row={}){return{...stamp(row,'clue'),title:text(row.title)||'Pista',text:String(row.text??''),status:CLUE_ST.has(row.status)?row.status:'hidden',notes:String(row.notes??'')}}
function sanitizeHandout(row={}){return{...stamp(row,'handout'),title:text(row.title)||'Handout',type:['text','link'].includes(row.type)?row.type:'text',content:String(row.content??''),url:String(row.url??''),revealed:row.revealed===true,notes:String(row.notes??'')}}
function sanitizeTreasure(row={}){return{...stamp(row,'treasure'),name:text(row.name)||'Tesouro',description:String(row.description??''),quantity:Math.max(1,Math.floor(Number(row.quantity)||1)),status:TREASURE_ST.has(row.status)?row.status:'planned',notes:String(row.notes??'')}}
function sanitizeScene(row={},index=0){const encounter=copy(row.encounterRef);return{...stamp(row,'scene'),chapterId:text(row.chapterId)||null,title:text(row.title)||`Cena ${index+1}`,status:SCN_STATUS.has(row.status)?row.status:'planned',locationId:text(row.locationId)||null,npcIds:uniq(row.npcIds),clueIds:uniq(row.clueIds),handoutIds:uniq(row.handoutIds),treasureIds:uniq(row.treasureIds),sessionId:text(row.sessionId)||null,encounterRef:{sessionId:text(encounter.sessionId)||null,encounterId:text(encounter.encounterId)||null},objective:String(row.objective??''),description:String(row.description??''),outcome:String(row.outcome??''),notes:String(row.notes??''),order:Math.max(1,Math.floor(Number(row.order)||index+1))}}
export function sanitizeAdventure(row={}){const chapters=arr(row.chapters).map(sanitizeChapter).sort((a,b)=>a.order-b.order||a.title.localeCompare(b.title,'pt-BR')),locations=arr(row.locations).map(sanitizeLocation),npcs=arr(row.npcs).map(sanitizeNpc),clues=arr(row.clues).map(sanitizeClue),handouts=arr(row.handouts).map(sanitizeHandout),treasures=arr(row.treasures).map(sanitizeTreasure),chapterIds=new Set(chapters.map(x=>x.id)),locationIds=new Set(locations.map(x=>x.id)),npcIds=new Set(npcs.map(x=>x.id)),clueIds=new Set(clues.map(x=>x.id)),handoutIds=new Set(handouts.map(x=>x.id)),treasureIds=new Set(treasures.map(x=>x.id)),scenes=arr(row.scenes).map(sanitizeScene).map(scene=>({...scene,chapterId:chapterIds.has(scene.chapterId)?scene.chapterId:null,locationId:locationIds.has(scene.locationId)?scene.locationId:null,npcIds:scene.npcIds.filter(id=>npcIds.has(id)),clueIds:scene.clueIds.filter(id=>clueIds.has(id)),handoutIds:scene.handoutIds.filter(id=>handoutIds.has(id)),treasureIds:scene.treasureIds.filter(id=>treasureIds.has(id))})).sort((a,b)=>a.order-b.order||a.title.localeCompare(b.title,'pt-BR'));let activeSceneId=text(row.activeSceneId)||null;const activeScenes=scenes.filter(x=>x.status==='active');if(activeSceneId&&!scenes.some(x=>x.id===activeSceneId&&x.status==='active'))activeSceneId=null;if(!activeSceneId&&activeScenes.length)activeSceneId=activeScenes[0].id;for(const scene of scenes)if(scene.status==='active'&&scene.id!==activeSceneId)scene.status='planned';let currentChapterId=text(row.currentChapterId)||null;if(currentChapterId&&!chapterIds.has(currentChapterId))currentChapterId=null;const activeScene=scenes.find(x=>x.id===activeSceneId);if(activeScene?.chapterId)currentChapterId=activeScene.chapterId;return{schema:ADVENTURE_SCHEMA,...stamp(row,'adventure'),campaignId:text(row.campaignId)||null,title:text(row.title)||'Nova Aventura',status:ADV_STATUS.has(row.status)?row.status:'planned',arc:String(row.arc??''),pitch:String(row.pitch??''),objective:String(row.objective??''),summary:String(row.summary??''),dmNotes:String(row.dmNotes??''),chapters,scenes,locations,npcs,clues,handouts,treasures,currentChapterId,activeSceneId}}
export function readAdventures(storage=globalThis.localStorage){if(!storage)return[];try{return arr(JSON.parse(storage.getItem(ADVENTURE_KEY)||'[]')).map(sanitizeAdventure)}catch{return[]}}
export function writeAdventures(list,storage=globalThis.localStorage){const clean=arr(list).map(sanitizeAdventure);if(storage)storage.setItem(ADVENTURE_KEY,JSON.stringify(clean));return clean}
export function adventureById(list=[],adventureId){const id=text(adventureId);return arr(list).map(sanitizeAdventure).find(a=>a.id===id)||null}
export function adventuresForCampaign(list=[],campaignId){const id=text(campaignId);return arr(list).map(sanitizeAdventure).filter(a=>a.campaignId===id)}
export function createAdventure(list=[],data={}){const campaignId=text(data.campaignId);if(!campaignId)return{ok:false,reason:'Selecione uma Campanha.',list:arr(list).map(sanitizeAdventure)};const adventure=sanitizeAdventure({...data,id:data.id||uid('adventure'),campaignId,createdAt:now(),updatedAt:now()});return{ok:true,list:[...arr(list).map(sanitizeAdventure),adventure],adventure}}
export function updateAdventure(list=[],adventureId,patch={}){const id=text(adventureId);let adventure=null,found=false;const next=arr(list).map(row=>{const old=sanitizeAdventure(row);if(old.id!==id)return old;found=true;adventure=sanitizeAdventure({...old,...patch,id:old.id,campaignId:old.campaignId,createdAt:old.createdAt,updatedAt:now()});return adventure});return found?{ok:true,list:next,adventure}:{ok:false,reason:'Aventura não encontrada.',list:arr(list).map(sanitizeAdventure)}}
export function removeAdventure(list=[],adventureId){const id=text(adventureId),base=arr(list).map(sanitizeAdventure),next=base.filter(x=>x.id!==id);return next.length===base.length?{ok:false,reason:'Aventura não encontrada.',list:base}:{ok:true,list:next}}
export function removeAdventuresForCampaign(list=[],campaignId){const id=text(campaignId);return arr(list).map(sanitizeAdventure).filter(x=>x.campaignId!==id)}
function mutate(list,adventureId,fn){const adventure=adventureById(list,adventureId);if(!adventure)return{ok:false,reason:'Aventura não encontrada.',list:arr(list).map(sanitizeAdventure)};const value=fn(adventure);if(value?.ok===false)return{...value,list:arr(list).map(sanitizeAdventure)};adventure.updatedAt=now();const clean=sanitizeAdventure(adventure);return{ok:true,list:arr(list).map(row=>row.id===clean.id?clean:sanitizeAdventure(row)),adventure:clean,...(value||{})}}
function addEntity(list,adventureId,key,data,sanitizer,prefix){return mutate(list,adventureId,adventure=>{const entity=sanitizer({...data,id:data?.id||uid(prefix),createdAt:now(),updatedAt:now()},adventure[key].length);adventure[key].push(entity);return{entity}})}
export const addAdventureChapter=(list,id,data={})=>addEntity(list,id,'chapters',data,sanitizeChapter,'chapter');
export const addAdventureLocation=(list,id,data={})=>addEntity(list,id,'locations',data,sanitizeLocation,'location');
export const addAdventureNpc=(list,id,data={})=>addEntity(list,id,'npcs',data,sanitizeNpc,'npc');
export const addAdventureClue=(list,id,data={})=>addEntity(list,id,'clues',data,sanitizeClue,'clue');
export const addAdventureHandout=(list,id,data={})=>addEntity(list,id,'handouts',data,sanitizeHandout,'handout');
export const addAdventureTreasure=(list,id,data={})=>addEntity(list,id,'treasures',data,sanitizeTreasure,'treasure');
export const addAdventureScene=(list,id,data={})=>addEntity(list,id,'scenes',data,sanitizeScene,'scene');
export function updateAdventureEntity(list,adventureId,key,entityId,patch={}){const sanitizers={chapters:sanitizeChapter,scenes:sanitizeScene,locations:sanitizeLocation,npcs:sanitizeNpc,clues:sanitizeClue,handouts:sanitizeHandout,treasures:sanitizeTreasure},sanitize=sanitizers[key];if(!sanitize)return{ok:false,reason:'Coleção de aventura inválida.',list:arr(list).map(sanitizeAdventure)};return mutate(list,adventureId,adventure=>{const index=adventure[key].findIndex(x=>x.id===text(entityId));if(index<0)return{ok:false,reason:'Registro não encontrado.'};const old=adventure[key][index];adventure[key][index]=sanitize({...old,...patch,id:old.id,createdAt:old.createdAt,updatedAt:now()},index);return{entity:adventure[key][index]}})}
export function removeAdventureEntity(list,adventureId,key,entityId){const id=text(entityId);return mutate(list,adventureId,adventure=>{if(!['chapters','scenes','locations','npcs','clues','handouts','treasures'].includes(key))return{ok:false,reason:'Coleção de aventura inválida.'};const before=adventure[key].length;adventure[key]=adventure[key].filter(x=>x.id!==id);if(before===adventure[key].length)return{ok:false,reason:'Registro não encontrado.'};if(key==='chapters')for(const scene of adventure.scenes)if(scene.chapterId===id)scene.chapterId=null;if(key==='locations')for(const scene of adventure.scenes)if(scene.locationId===id)scene.locationId=null;if(key==='npcs')for(const scene of adventure.scenes)scene.npcIds=scene.npcIds.filter(x=>x!==id);if(key==='clues')for(const scene of adventure.scenes)scene.clueIds=scene.clueIds.filter(x=>x!==id);if(key==='handouts')for(const scene of adventure.scenes)scene.handoutIds=scene.handoutIds.filter(x=>x!==id);if(key==='treasures')for(const scene of adventure.scenes)scene.treasureIds=scene.treasureIds.filter(x=>x!==id);if(key==='scenes'&&adventure.activeSceneId===id)adventure.activeSceneId=null;return{}})}
export function startAdventureScene(list,adventureId,sceneId){return mutate(list,adventureId,adventure=>{const scene=adventure.scenes.find(x=>x.id===text(sceneId));if(!scene)return{ok:false,reason:'Cena não encontrada.'};const other=adventure.scenes.find(x=>x.status==='active'&&x.id!==scene.id);if(other)return{ok:false,reason:`Conclua a cena ativa (${other.title}) antes de iniciar outra.`};scene.status='active';scene.updatedAt=now();adventure.status='active';adventure.activeSceneId=scene.id;adventure.currentChapterId=scene.chapterId||adventure.currentChapterId;if(scene.chapterId){const chapter=adventure.chapters.find(x=>x.id===scene.chapterId);if(chapter&&chapter.status==='planned')chapter.status='active'}return{scene}})}
export function completeAdventureScene(list,adventureId,sceneId,patch={}){return mutate(list,adventureId,adventure=>{const scene=adventure.scenes.find(x=>x.id===text(sceneId));if(!scene)return{ok:false,reason:'Cena não encontrada.'};Object.assign(scene,patch,{status:'completed',updatedAt:now()});if(adventure.activeSceneId===scene.id)adventure.activeSceneId=null;return{scene}})}
export function skipAdventureScene(list,adventureId,sceneId){return mutate(list,adventureId,adventure=>{const scene=adventure.scenes.find(x=>x.id===text(sceneId));if(!scene)return{ok:false,reason:'Cena não encontrada.'};scene.status='skipped';scene.updatedAt=now();if(adventure.activeSceneId===scene.id)adventure.activeSceneId=null;return{scene}})}
export function setAdventureClueStatus(list,adventureId,clueId,status){if(!CLUE_ST.has(status))return{ok:false,reason:'Status de pista inválido.',list:arr(list).map(sanitizeAdventure)};return updateAdventureEntity(list,adventureId,'clues',clueId,{status})}
export function setAdventureHandoutRevealed(list,adventureId,handoutId,revealed=true){return updateAdventureEntity(list,adventureId,'handouts',handoutId,{revealed:!!revealed})}
export function setAdventureTreasureStatus(list,adventureId,treasureId,status){if(!TREASURE_ST.has(status))return{ok:false,reason:'Status de tesouro inválido.',list:arr(list).map(sanitizeAdventure)};return updateAdventureEntity(list,adventureId,'treasures',treasureId,{status})}
export function linkSceneToSession(list,adventureId,sceneId,sessionId){return updateAdventureEntity(list,adventureId,'scenes',sceneId,{sessionId:text(sessionId)||null})}
export function linkSceneToEncounter(list,adventureId,sceneId,{sessionId,encounterId}={}){const sid=text(sessionId),eid=text(encounterId);return updateAdventureEntity(list,adventureId,'scenes',sceneId,{sessionId:sid||null,encounterRef:{sessionId:sid||null,encounterId:eid||null}})}
export function adventureContextForSession(list=[],campaignId,sessionId){const cid=text(campaignId),sid=text(sessionId);return adventuresForCampaign(list,cid).flatMap(adventure=>adventure.scenes.filter(scene=>scene.sessionId===sid||scene.encounterRef?.sessionId===sid).map(scene=>({adventureId:adventure.id,adventureTitle:adventure.title,adventureStatus:adventure.status,scene}))) }
