(()=>{
'use strict';
const KEY='teias.personagem.rascunho.v1',MOD='antecedentes';
const A=()=>window.HubAntecedentes||{}, itens=()=>Array.isArray(A().getItens?.())?A().getItens():[];
const arr=v=>Array.isArray(v)?v:[], esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const talento=t=>A().talentoTexto?.(t)||t?.nome||'—', ferramenta=d=>A().ferramentaTexto?.(d)||arr(d?.ferramentas).join(', ')||'—';
function vazio(){return{schema:'hub-rpg/personagem-rascunho/v1',atualizado_em:null,selecoes:{},ficha_derivada:{}}}
function ler(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');return s&&typeof s==='object'&&!Array.isArray(s)?{...s,selecoes:s.selecoes&&typeof s.selecoes==='object'?s.selecoes:{}}:vazio()}catch{return vazio()}}
function uniq(a){return[...new Map(arr(a).filter(Boolean).map(v=>[String(v).trim().toLocaleLowerCase('pt-BR'),String(v).trim()])).values()]}
function derivar(sel){
 const f={atributos:{},pericias:[],ferramentas:[],idiomas:[],talentos:[],caracteristicas:[],equipamentos:[],pendencias:[]};
 const add=(dest,v)=>{if(v&&!dest.some(x=>String(x.nome||x).localeCompare(String(v.nome||v),'pt-BR',{sensitivity:'base'})===0))dest.push(v)};
 for(const[m,s]of Object.entries(sel||{})){
  const c=s?.contribuicoes||{};
  for(const[k,v]of Object.entries(c.atributos||{}))f.atributos[k]=(f.atributos[k]||0)+(Number(v)||0);
  arr(c.pericias).forEach(v=>add(f.pericias,v)); arr(c.ferramentas).forEach(v=>add(f.ferramentas,v)); arr(c.idiomas).forEach(v=>add(f.idiomas,v));
  arr(c.talentos).forEach(v=>add(f.talentos,{...(typeof v==='string'?{nome:v}:v),origem_modulo:m}));
  arr(c.caracteristicas).forEach(v=>add(f.caracteristicas,{...(typeof v==='string'?{nome:v}:v),origem_modulo:m}));
  arr(c.equipamentos).forEach(v=>f.equipamentos.push({...v,origem_modulo:m})); arr(s?.pendencias).forEach(v=>f.pendencias.push({modulo:m,descricao:String(v)}));
 }
 return f;
}
function gravar(selecao){const s=ler();s.selecoes={...(s.selecoes||{}),[MOD]:selecao};s.atualizado_em=new Date().toISOString();s.ficha_derivada=derivar(s.selecoes);localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('teias:personagem-atualizado',{detail:{modulo:MOD,selecao,estado:s}}));return s}
function remover(){const s=ler(),x={...(s.selecoes||{})};delete x[MOD];s.selecoes=x;s.atualizado_em=new Date().toISOString();s.ficha_derivada=derivar(x);localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('teias:personagem-atualizado',{detail:{modulo:MOD,selecao:null,estado:s}}))}
const atual=()=>ler().selecoes?.[MOD]||null, dados=x=>x?.mecanica?.dados_especificos||{}, ruleset=(x,d)=>x?.compatibilidade?.ruleset||x?.fonte?.ruleset||d?.modelo_de_antecedente||'';
function equipLabel(o){if(o?.texto)return o.texto;return arr(o?.itens).map(i=>A().itemTexto?.(i)||`${i?.quantidade||1}× ${i?.nome||'Item'}`).join(', ')}
function resumo(x,d,r){const l=[];if(r==='5.5e'){l.push(`<li><b>Atributos:</b> ${esc(arr(d.atributos_elegiveis).join(', ')||'—')}</li>`);if(d.talento_origem)l.push(`<li><b>Talento de Origem:</b> ${esc(talento(d.talento_origem))}</li>`)}if(arr(d.pericias).length)l.push(`<li><b>Perícias:</b> ${esc(d.pericias.join(', '))}</li>`);if(d.ferramenta_escolha||arr(d.ferramentas).length)l.push(`<li><b>Ferramentas:</b> ${esc(ferramenta(d))}</li>`);if(arr(d.idiomas).length)l.push(`<li><b>Idiomas:</b> ${esc(d.idiomas.join(', '))}</li>`);if(d.caracteristica?.nome)l.push(`<li><b>Característica:</b> ${esc(d.caracteristica.nome)}</li>`);if(arr(d.equipamento_inicial?.opcoes).length)l.push('<li><b>Equipamento:</b> pacote escolhido abaixo</li>');return l.join('')}
function painel(x){
 const d=dados(x),r=ruleset(x,d),salvo=atual()?.id===x.id?(atual().configuracao||{}):{},abs=arr(d.atributos_elegiveis),ops=arr(d.equipamento_inicial?.opcoes),escA=s=>abs.map(a=>`<option value="${esc(a)}" ${s===a?'selected':''}>${esc(a)}</option>`).join('');
 let html=`<section class="taf" data-id="${esc(x.id)}"><div class="taf-head"><div><h3>Aplicar à ficha do personagem</h3><p>Esta seleção altera somente Antecedentes. As escolhas dos outros módulos são preservadas.</p></div><span data-selected ${atual()?.id===x.id?'':'hidden'}>Selecionado</span></div><div class="taf-prev"><b>Será aplicado à ficha:</b><ul>${resumo(x,d,r)}</ul></div><form class="taf-form" data-id="${esc(x.id)}">`;
 if(r==='5.5e'&&abs.length){const m=salvo.modo_atributos||'';html+=`<fieldset><legend>Aumentos de atributo</legend><label><input type="radio" name="am-${esc(x.slug)}" value="triplo" ${m==='triplo'?'checked':''}> +1 nos três atributos</label><label><input type="radio" name="am-${esc(x.slug)}" value="duplo" ${m==='duplo'?'checked':''}> +2 em um e +1 em outro</label><div class="taf-attrs" ${m==='duplo'?'':'hidden'}><label>+2<select data-plus2><option value="">Escolha...</option>${escA(salvo.atributo_mais2||'')}</select></label><label>+1<select data-plus1><option value="">Escolha...</option>${escA(salvo.atributo_mais1||'')}</select></label></div></fieldset>`}
 if(d.ferramenta_escolha){const ab=arr(d.ferramenta_escolha.opcoes_abertas),sv=salvo.ferramenta_escolhida||'';html+=ab.length?`<label class="taf-box">${esc(d.ferramenta_escolha.categoria||'Ferramenta')}<select data-tool><option value="">Escolha...</option>${ab.map(v=>`<option value="${esc(v)}" ${sv===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`:`<label class="taf-box">${esc(d.ferramenta_escolha.categoria||'Ferramenta')}<input data-tool value="${esc(sv)}" placeholder="Informe a ferramenta escolhida"></label>`}
 if(ops.length){const group=`equip-${x.slug}`,sv=salvo.equipamento_opcao||((ops.length===1&&ops[0]?.id)?String(ops[0].id):'');html+=`<fieldset><legend>Equipamento inicial</legend>${ops.map(o=>{const id=String(o?.id??'A');return`<label><input type="radio" name="${esc(group)}" data-equip value="${esc(id)}" ${sv===id?'checked':''}> <b>Opção ${esc(id)}</b> — ${esc(equipLabel(o))}</label>`}).join('')}</fieldset>`}
 const escolhas=arr(x?.mecanica?.escolhas).filter(c=>c?.nome&&c.nome!==d.ferramenta_escolha?.categoria),gen=salvo.escolhas_abertas||{};
 if(escolhas.length)html+=`<fieldset><legend>Outras escolhas</legend>${escolhas.map(c=>{const nome=String(c.nome),oo=arr(c.opcoes);return oo.length?`<label class="taf-box">${esc(nome)}<select data-choice="${esc(nome)}"><option value="">Escolha...</option>${oo.map(v=>{const z=typeof v==='string'?v:(v?.nome||v?.name||v?.valor||'');return`<option value="${esc(z)}" ${gen[nome]===z?'selected':''}>${esc(z)}</option>`}).join('')}</select></label>`:`<label class="taf-box">${esc(nome)}<input data-choice="${esc(nome)}" value="${esc(gen[nome]||'')}" placeholder="Registre sua escolha"></label>`}).join('')}</fieldset>`;
 return html+`<div class="taf-actions"><button type="submit">${atual()?.id===x.id?'Atualizar antecedente':'Selecionar antecedente'}</button><button type="button" data-remove ${atual()?.id===x.id?'':'hidden'}>Remover da ficha</button><span data-status></span></div></form></section>`;
}
function config(form,d){const g={};form.querySelectorAll('[data-choice]').forEach(e=>g[e.dataset.choice]=String(e.value||'').trim());return{modo_atributos:form.querySelector('input[name^="am-"]:checked')?.value||'',atributo_mais2:form.querySelector('[data-plus2]')?.value||'',atributo_mais1:form.querySelector('[data-plus1]')?.value||'',ferramenta_escolhida:String(form.querySelector('[data-tool]')?.value||'').trim(),equipamento_opcao:form.querySelector('[data-equip]:checked')?.value||((arr(d.equipamento_inicial?.opcoes).length===1&&d.equipamento_inicial.opcoes[0]?.id)?String(d.equipamento_inicial.opcoes[0].id):''),escolhas_abertas:g}}
function montar(x,form){
 const d=dados(x),r=ruleset(x,d),c=config(form,d),p=[],at={};
 if(r==='5.5e'&&arr(d.atributos_elegiveis).length){if(c.modo_atributos==='triplo')arr(d.atributos_elegiveis).forEach(a=>at[a]=1);else if(c.modo_atributos==='duplo'){if(!c.atributo_mais2||!c.atributo_mais1)p.push('Escolher os atributos que recebem +2 e +1.');else if(c.atributo_mais2===c.atributo_mais1)p.push('Os aumentos +2 e +1 devem ir para atributos diferentes.');else{at[c.atributo_mais2]=2;at[c.atributo_mais1]=1}}else p.push('Escolher a distribuição dos aumentos de atributo.')}
 const ferr=arr(d.ferramentas).slice();if(d.ferramenta_escolha){if(c.ferramenta_escolhida)ferr.push(c.ferramenta_escolhida);else p.push(`Escolher ${d.ferramenta_escolha.categoria||'ferramenta'}.`)}
 const ops=arr(d.equipamento_inicial?.opcoes),eo=ops.find(o=>String(o?.id??'A')===String(c.equipamento_opcao||''))||null;if(ops.length&&!eo)p.push('Escolher o equipamento inicial.');for(const[n,v]of Object.entries(c.escolhas_abertas))if(!v)p.push(`Registrar a escolha: ${n}.`);
 return{modulo:MOD,id:x.id,nome:x.nome,nome_original:x.nome_original||x.nome,ruleset:r,fonte:{titulo:x.fonte?.titulo||'',ano:x.fonte?.ano||null},configuracao:c,contribuicoes:{atributos:at,atributos_elegiveis:arr(d.atributos_elegiveis),pericias:arr(d.pericias),ferramentas:uniq(ferr),idiomas:arr(d.idiomas),talentos:d.talento_origem?[{nome:talento(d.talento_origem),tipo:'Talento de Origem'}]:[],caracteristicas:d.caracteristica?[{nome:d.caracteristica.nome,descricao:d.caracteristica.descricao||'',tipo:'Característica de Antecedente'}]:[],equipamentos:eo?[{opcao:String(eo.id??'A'),itens:arr(eo.itens).map(i=>({...i})),texto:eo.texto||equipLabel(eo)}]:[],escolhas_abertas:{...c.escolhas_abertas}},pendencias:p,atualizado_em:new Date().toISOString()};
}
function estadoUI(){const c=atual(),box=document.getElementById('taf-global');if(box)box.innerHTML=c?`<b>Antecedente na ficha:</b> ${esc(c.nome)}${arr(c.pendencias).length?` · ${c.pendencias.length} escolha(s) pendente(s)`:' · completo'}`:'<b>Antecedente na ficha:</b> nenhum selecionado.';document.querySelectorAll('.taf').forEach(p=>{const on=c?.id===p.dataset.id;p.classList.toggle('is-selected',on);const s=p.querySelector('[data-selected]'),r=p.querySelector('[data-remove]'),b=p.querySelector('button[type="submit"]');if(s)s.hidden=!on;if(r)r.hidden=!on;if(b)b.textContent=on?'Atualizar antecedente':'Selecionar antecedente'})}
function estilo(){if(document.getElementById('taf-style'))return;const s=document.createElement('style');s.id='taf-style';s.textContent='.taf-global,.taf-prev,.taf-box,.taf fieldset{border:1px solid #8884;border-radius:9px;padding:10px 12px;margin:10px 0}.taf{border-top:1px solid #8884;margin-top:16px;padding-top:14px}.taf-head{display:flex;justify-content:space-between;gap:12px}.taf-head h3{margin:0 0 4px}.taf-head p{margin:0;opacity:.78}.taf-head [data-selected]{border:1px solid #8886;border-radius:999px;padding:3px 8px;height:max-content;font-size:.8rem}.taf-form{display:grid;gap:8px}.taf fieldset{display:grid;gap:7px}.taf-box{display:grid;gap:4px}.taf-attrs{display:grid;grid-template-columns:1fr 1fr;gap:8px}.taf-attrs label{display:grid;gap:4px}.taf-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.taf-actions button{font:inherit;padding:9px 12px;border:1px solid #8887;border-radius:8px;background:transparent;color:inherit;cursor:pointer}.taf-actions [data-status]{opacity:.75;font-size:.9rem}.taf.is-selected{outline:1px solid #8885;outline-offset:7px;border-radius:6px}@media(max-width:650px){.taf-head{display:block}.taf-attrs{grid-template-columns:1fr}}';document.head.appendChild(s)}
let busy=false;function aplicar(){if(busy||!itens().length)return;const lista=document.getElementById('lista');if(!lista)return;busy=true;try{estilo();if(!document.getElementById('taf-global')){const e=document.createElement('section');e.id='taf-global';e.className='taf-global';const c=document.querySelector('.controles');(c?.parentNode||document.body).insertBefore(e,c||null)}lista.querySelectorAll('details.antecedente').forEach(det=>{if(det.querySelector('.taf'))return;const x=itens().find(i=>i.slug===det.id),corpo=det.querySelector('.corpo');if(x&&corpo)corpo.insertAdjacentHTML('beforeend',painel(x))});estadoUI()}finally{busy=false}}
document.addEventListener('change',e=>{const f=e.target.closest?.('.taf-form');if(!f)return;const pair=f.querySelector('.taf-attrs'),m=f.querySelector('input[name^="am-"]:checked')?.value;if(pair)pair.hidden=m!=='duplo';const x=itens().find(i=>i.id===f.dataset.id);if(atual()?.id===x?.id){gravar(montar(x,f));estadoUI()}});
document.addEventListener('submit',e=>{const f=e.target.closest?.('.taf-form');if(!f)return;e.preventDefault();const x=itens().find(i=>i.id===f.dataset.id);if(!x)return;const s=montar(x,f);gravar(s);estadoUI();const z=f.querySelector('[data-status]');if(z)z.textContent=s.pendencias.length?`Salvo. Restam ${s.pendencias.length} escolha(s).`:'Aplicado à ficha.'});
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-remove]');if(!b)return;remover();estadoUI()});
const start=()=>{aplicar();const l=document.getElementById('lista');if(l)new MutationObserver(()=>queueMicrotask(aplicar)).observe(l,{childList:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('storage',e=>{if(e.key===KEY)estadoUI()});
})();
