import{createBackupPackage,serializeBackup,backupFilename,validateBackupPackage,restoreBackup,readPortableData,readRecoverySnapshot,restoreRecoverySnapshot,clearRecoverySnapshot}from'./backup-engine.js?v=20260902-backup1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pendingPackage=null;
function feedback(message,ok=true){const box=$('backup-feedback');if(!box)return;box.hidden=false;box.className=`status ${ok?'ok':'warning'}`;box.textContent=message}
function metrics(){try{const data=readPortableData();$('portable-metrics').innerHTML=`<div class="metric"><span>Personagens</span><strong>${data.characters.length}</strong></div><div class="metric"><span>Campanhas</span><strong>${data.campaigns.length}</strong></div><div class="metric"><span>Aventuras</span><strong>${data.adventures.length}</strong></div>`}catch(error){$('portable-metrics').innerHTML=`<div class="status warning">${esc(error.message)}</div>`}}
function recovery(){const pkg=readRecoverySnapshot(),status=$('recovery-status'),restore=$('restore-recovery'),clear=$('clear-recovery');if(pkg){status.innerHTML=`Disponível · ${esc(pkg.createdAt)} · ${pkg.manifest.characters.count} personagem(ns), ${pkg.manifest.campaigns.count} campanha(s), ${pkg.manifest.adventures.count} aventura(s).`;restore.disabled=false;clear.disabled=false}else{status.textContent='Nenhum snapshot de recuperação disponível.';restore.disabled=true;clear.disabled=true}}
function downloadPackage(){try{const pkg=createBackupPackage(),blob=new Blob([serializeBackup(pkg)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=backupFilename();document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);feedback('Backup exportado com checksum e manifesto.',true)}catch(error){feedback(error.message,false)}}
async function selectFile(event){pendingPackage=null;$('restore-backup').disabled=true;const preview=$('backup-preview'),file=event.target.files?.[0];preview.hidden=true;if(!file)return;try{const text=await file.text(),validated=validateBackupPackage(text);pendingPackage=validated.package;preview.hidden=false;preview.className='status ok';preview.innerHTML=`<strong>Backup válido.</strong><br><span class="mini">Criado em ${esc(validated.package.createdAt)} · checksum ${esc(validated.package.integrity.checksum)}</span><div class="grid" style="margin-top:8px"><div class="metric"><span>Personagens</span><strong>${validated.manifest.characters.count}</strong></div><div class="metric"><span>Campanhas</span><strong>${validated.manifest.campaigns.count}</strong></div><div class="metric"><span>Aventuras</span><strong>${validated.manifest.adventures.count}</strong></div></div>`;$('restore-backup').disabled=false;feedback('Arquivo validado. Escolha o modo e confirme a restauração.',true)}catch(error){preview.hidden=false;preview.className='status warning';preview.textContent=error.message;feedback('O arquivo não foi aceito.',false)}}
function modeChanged(){const replacing=$('restore-mode').value==='replace';$('replace-confirm').hidden=!replacing;if(!replacing)$('replace-confirm-text').value=''}
function restoreSelected(){if(!pendingPackage)return feedback('Selecione um backup válido.',false);const mode=$('restore-mode').value;if(mode==='replace'&&$('replace-confirm-text').value.trim()!=='SUBSTITUIR')return feedback('Digite SUBSTITUIR para confirmar a substituição completa.',false);try{const result=restoreBackup(pendingPackage,{mode});feedback(`Restauração concluída: ${result.counts.characters} personagem(ns), ${result.counts.campaigns} campanha(s) e ${result.counts.adventures} aventura(s).`,true);pendingPackage=null;$('backup-file').value='';$('backup-preview').hidden=true;$('restore-backup').disabled=true;$('replace-confirm-text').value='';metrics();recovery()}catch(error){feedback(error.message,false);metrics();recovery()}}
function undo(){if(!confirm('Restaurar o estado capturado antes da última importação?'))return;try{const result=restoreRecoverySnapshot();feedback(`Snapshot restaurado: ${result.counts.characters} personagem(ns), ${result.counts.campaigns} campanha(s), ${result.counts.adventures} aventura(s).`,true);metrics();recovery()}catch(error){feedback(error.message,false)}}
function clear(){if(!confirm('Descartar o snapshot local de recuperação?'))return;clearRecoverySnapshot();feedback('Snapshot de recuperação descartado.',true);recovery()}
function init(){metrics();recovery();$('export-backup')?.addEventListener('click',downloadPackage);$('backup-file')?.addEventListener('change',selectFile);$('restore-mode')?.addEventListener('change',modeChanged);$('restore-backup')?.addEventListener('click',restoreSelected);$('restore-recovery')?.addEventListener('click',undo);$('clear-recovery')?.addEventListener('click',clear);modeChanged()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
