import{CAMPAIGN_KEY,readCampaigns,writeCampaigns,createCampaign,updateCampaign,removeCampaign}from'./campaign-state.js?v=20260901-campaign1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let campaigns=[];
function persist(list){campaigns=writeCampaigns(list);render()}
function statusLabel(status){return({active:'Ativa',paused:'Pausada',finished:'Encerrada'}[status]||status)}
function card(c){const active=c.sessions.find(s=>s.id===c.activeSessionId),completed=c.sessions.filter(s=>s.status==='completed').length;return`<article class="campaign-card"><div><h2>${esc(c.name)}</h2><div><span class="badge ${esc(c.status)}">${esc(statusLabel(c.status))}</span><span class="badge">${esc(c.system)}</span></div><p class="mini">${esc(c.setting||'Cenário não informado')}${c.dmName?` · Mestre: ${esc(c.dmName)}`:''}</p><p class="mini">${c.members.length} participante(s) · ${completed}/${c.sessions.length} sessão(ões) concluída(s)${active?` · <strong>em jogo: ${esc(active.title)}</strong>`:''}</p></div><div class="row-actions"><a class="btn" href="mesa.html?id=${encodeURIComponent(c.id)}">Abrir Mesa</a>${c.status==='active'?`<button type="button" class="secondary" data-status="paused" data-id="${esc(c.id)}">Pausar</button>`:`<button type="button" class="secondary" data-status="active" data-id="${esc(c.id)}">Ativar</button>`}${c.status!=='finished'?`<button type="button" class="secondary" data-status="finished" data-id="${esc(c.id)}">Encerrar</button>`:''}<button type="button" class="danger" data-delete="${esc(c.id)}">Excluir</button></div></article>`}
function render(){const box=$('campaign-list');if(!box)return;const ordered=[...campaigns].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));box.innerHTML=ordered.length?`<div class="list">${ordered.map(card).join('')}</div>`:'<div class="empty">Nenhuma campanha criada. Crie a primeira Mesa acima.</div>';box.querySelectorAll('[data-status]').forEach(button=>button.addEventListener('click',()=>{const result=updateCampaign(campaigns,button.dataset.id,{status:button.dataset.status});if(result.ok)persist(result.list)}));box.querySelectorAll('[data-delete]').forEach(button=>button.addEventListener('click',()=>{if(!confirm('Excluir esta campanha? Os personagens não serão excluídos.'))return;const result=removeCampaign(campaigns,button.dataset.delete);if(result.ok)persist(result.list)}))}
function create(){const name=$('campaign-name')?.value.trim();if(!name)return;const result=createCampaign(campaigns,{name,dmName:$('campaign-dm')?.value,setting:$('campaign-setting')?.value,description:$('campaign-description')?.value});if(!result.ok)return;writeCampaigns(result.list);location.href=`mesa.html?id=${encodeURIComponent(result.campaign.id)}`}
function init(){campaigns=readCampaigns();$('create-campaign')?.addEventListener('click',create);$('campaign-name')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();create()}});render();const note=$('storage-note');if(note)note.textContent=`Persistência local · ${CAMPAIGN_KEY}`}
init();
