import{sanitizeEncounterSessionFields}from'./encounter-state.js?v=20260924-session-encounters1';

export const CAMPAIGN_KEY='hub-rpg:campaigns:v1';
export const CAMPAIGN_SCHEMA='hub-rpg/campaign/v1';
export const STANDALONE_SESSION_KEY='hub-rpg:sessions:v1';
const CAMPAIGN_STATUS=new Set(['planned','active','paused','finished']);
const SESSION_STATUS=new Set(['planned','active','completed','cancelled']);
const SESSION_SCENE_STATUS=new Set(['planned','active','completed','skipped']);
const MEMBER_ROLES=new Set(['dm','player']);
const text=v=>String(v??'').trim();
const arr=v=>Array.isArray(v)?v:[];
const now=()=>new Date().toISOString();
export function campaignUid(prefix='cmp'){return globalThis.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
function sanitizeMember(row={}){return{id:text(row.id)||campaignUid('member'),username:text(row.username).toLowerCase(),name:text(row.name)||'Participante',role:MEMBER_ROLES.has(row.role)?row.role:'player',characterId:text(row.characterId)||null,notes:String(row.notes??''),active:row.active!==false}}
function sanitizeSessionScene(row={},index=0){return{id:text(row.id)||campaignUid('session-scene'),title:text(row.title)||`Cena ${index+1}`,status:SESSION_SCENE_STATUS.has(row.status)?row.status:'planned',order:Math.max(1,Math.floor(Number(row.order)||index+1)),adventureSceneId:text(row.adventureSceneId)||null,locationId:text(row.locationId)||null,npcIds:[...new Set(arr(row.npcIds).map(text).filter(Boolean))],missionIds:[...new Set(arr(row.missionIds).map(text).filter(Boolean))],clueIds:[...new Set(arr(row.clueIds).map(text).filter(Boolean))],handoutIds:[...new Set(arr(row.handoutIds).map(text).filter(Boolean))],treasureIds:[...new Set(arr(row.treasureIds).map(text).filter(Boolean))],encounterId:text(row.encounterId)||null,description:String(row.description??''),notes:String(row.notes??''),createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
export function sanitizeSession(row={},index=0){const status=SESSION_STATUS.has(row.status)?row.status:'planned',encounterFields=sanitizeEncounterSessionFields(row),scenes=arr(row.scenes).map(sanitizeSessionScene).sort((a,b)=>a.order-b.order||a.title.localeCompare(b.title,'pt-BR')),sceneIds=new Set(scenes.map(s=>s.id));for(const encounter of encounterFields.encounters)if(encounter.sessionSceneId&&!sceneIds.has(encounter.sessionSceneId))encounter.sessionSceneId=null;let activeSceneId=text(row.activeSceneId)||null;if(activeSceneId&&!scenes.some(s=>s.id===activeSceneId&&s.status==='active'))activeSceneId=null;if(!activeSceneId){const active=scenes.find(s=>s.status==='active');if(active)activeSceneId=active.id}return{id:text(row.id)||campaignUid('session'),number:Math.max(1,Math.floor(Number(row.number)||index+1)),title:text(row.title)||`Sessão ${Math.max(1,Math.floor(Number(row.number)||index+1))}`,date:text(row.date),status,adventureId:text(row.adventureId)||null,location:String(row.location??''),objective:String(row.objective??''),summary:String(row.summary??''),sharedNotes:String(row.sharedNotes??''),dmNotes:String(row.dmNotes??''),finalSummary:String(row.finalSummary??''),quickLog:String(row.quickLog??''),participantUsernames:[...new Set(arr(row.participantUsernames).map(v=>text(v).toLowerCase()).filter(Boolean))],participantCharacterIds:[...new Set(arr(row.participantCharacterIds).map(text).filter(Boolean))],scenes,activeSceneId,...encounterFields,createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
function sanitizeCampaignNpc(row={}){return{id:text(row.id)||campaignUid('npc'),name:text(row.name)||'NPC',role:String(row.role??''),faction:String(row.faction??''),relationship:String(row.relationship??''),status:String(row.status??''),currentLocationId:text(row.currentLocationId)||null,portraitUrl:String(row.portraitUrl??''),monsterId:text(row.monsterId)||null,source:String(row.source??''),description:String(row.description??''),notes:String(row.notes??''),createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
function sanitizeCampaignLocation(row={}){return{id:text(row.id)||campaignUid('location'),name:text(row.name)||'Local',type:String(row.type??''),imageUrl:String(row.imageUrl??''),description:String(row.description??''),state:String(row.state??''),notes:String(row.notes??''),createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
export function sanitizeCampaign(row={}){const sessions=arr(row.sessions).map(sanitizeSession);let activeSessionId=text(row.activeSessionId)||null;const active=sessions.filter(s=>s.status==='active');if(activeSessionId&&!sessions.some(s=>s.id===activeSessionId&&s.status==='active'))activeSessionId=null;if(!activeSessionId&&active.length)activeSessionId=active[0].id;for(const session of sessions)if(session.status==='active'&&session.id!==activeSessionId)session.status='planned';return{schema:CAMPAIGN_SCHEMA,id:text(row.id)||campaignUid(),name:text(row.name)||'Nova Campanha',status:CAMPAIGN_STATUS.has(row.status)?row.status:'active',system:text(row.system)||'D&D 5.5e',setting:String(row.setting??''),description:String(row.description??''),coverImageUrl:String(row.coverImageUrl??row.coverUrl??''),historySummary:String(row.historySummary??''),importantNpcs:String(row.importantNpcs??''),importantLocations:String(row.importantLocations??''),activeMissions:String(row.activeMissions??''),campaignMaterials:String(row.campaignMaterials??''),timeline:String(row.timeline??''),dmName:String(row.dmName??''),schedule:String(row.schedule??''),currentArc:String(row.currentArc??''),currentLocation:String(row.currentLocation??''),partyGoal:String(row.partyGoal??''),sharedNotes:String(row.sharedNotes??''),dmNotes:String(row.dmNotes??''),partyTreasure:String(row.partyTreasure??''),npcs:arr(row.npcs).map(sanitizeCampaignNpc),locations:arr(row.locations).map(sanitizeCampaignLocation),members:arr(row.members).map(sanitizeMember),sessions,activeSessionId,createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
export function readCampaigns(storage=globalThis.localStorage){if(!storage)return[];try{const raw=JSON.parse(storage.getItem(CAMPAIGN_KEY)||'[]');return arr(raw).map(sanitizeCampaign)}catch{return[]}}
export function writeCampaigns(list,storage=globalThis.localStorage){const clean=arr(list).map(sanitizeCampaign);if(storage)storage.setItem(CAMPAIGN_KEY,JSON.stringify(clean));return clean}
export function readStandaloneSessions(storage=globalThis.localStorage){if(!storage)return[];try{const raw=JSON.parse(storage.getItem(STANDALONE_SESSION_KEY)||'[]');return arr(raw).map(sanitizeSession)}catch{return[]}}
export function writeStandaloneSessions(list,storage=globalThis.localStorage){const clean=arr(list).map(sanitizeSession);if(storage)storage.setItem(STANDALONE_SESSION_KEY,JSON.stringify(clean));return clean}
export function createStandaloneSession(list=[],data={}){const base=arr(list).map(sanitizeSession),maxNumber=base.reduce((m,s)=>Math.max(m,s.number),0),session=sanitizeSession({...data,id:data.id||campaignUid('session'),number:data.number||maxNumber+1,createdAt:now(),updatedAt:now()},maxNumber);return{ok:true,list:[...base,session],session}}
export function updateStandaloneSession(list=[],sessionId,patch={}){const id=text(sessionId);let session=null,found=false;const next=arr(list).map((row,index)=>{const current=sanitizeSession(row,index);if(current.id!==id)return current;found=true;session=sanitizeSession({...current,...patch,id:current.id,createdAt:current.createdAt,updatedAt:now()},index);return session});return found?{ok:true,list:next,session}:{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeSession)}}
export function removeStandaloneSession(list=[],sessionId){const id=text(sessionId),base=arr(list).map(sanitizeSession),next=base.filter(s=>s.id!==id);return next.length===base.length?{ok:false,reason:'Sessão não encontrada.',list:base}:{ok:true,list:next}}
export function addSessionScene(session,data={}){if(!session)return{ok:false,reason:'Sessão não encontrada.'};const scenes=arr(session.scenes).map(sanitizeSessionScene),maxOrder=scenes.reduce((m,s)=>Math.max(m,s.order),0),scene=sanitizeSessionScene({...data,id:data.id||campaignUid('session-scene'),order:data.order||maxOrder+1,createdAt:now(),updatedAt:now()},maxOrder);session.scenes=[...scenes,scene];session.updatedAt=now();return{ok:true,session,scene}}
export function updateSessionScene(session,sceneId,patch={}){if(!session)return{ok:false,reason:'Sessão não encontrada.'};const id=text(sceneId),index=arr(session.scenes).findIndex(s=>s.id===id);if(index<0)return{ok:false,reason:'Cena da sessão não encontrada.'};session.scenes[index]=sanitizeSessionScene({...session.scenes[index],...patch,id,createdAt:session.scenes[index].createdAt,updatedAt:now()},index);session.updatedAt=now();return{ok:true,session,scene:session.scenes[index]}}
export function removeSessionScene(session,sceneId){if(!session)return{ok:false,reason:'Sessão não encontrada.'};const id=text(sceneId),before=arr(session.scenes).length;session.scenes=arr(session.scenes).filter(s=>s.id!==id);if(session.scenes.length===before)return{ok:false,reason:'Cena da sessão não encontrada.'};if(session.activeSceneId===id)session.activeSceneId=null;for(const encounter of arr(session.encounters))if(encounter.sessionSceneId===id)encounter.sessionSceneId=null;session.updatedAt=now();return{ok:true,session}}
export function createCampaign(list=[],data={}){const campaign=sanitizeCampaign({...data,id:data.id||campaignUid(),createdAt:now(),updatedAt:now()}),next=[...arr(list).map(sanitizeCampaign),campaign];return{ok:true,list:next,campaign}}
export function updateCampaign(list=[],campaignId,patch={}){const id=text(campaignId);let campaign=null,found=false;const next=arr(list).map(row=>{const c=sanitizeCampaign(row);if(c.id!==id)return c;found=true;campaign=sanitizeCampaign({...c,...patch,id:c.id,createdAt:c.createdAt,updatedAt:now()});return campaign});return found?{ok:true,list:next,campaign}:{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)}}
export function removeCampaign(list=[],campaignId){const id=text(campaignId),base=arr(list).map(sanitizeCampaign),next=base.filter(c=>c.id!==id);return next.length===base.length?{ok:false,reason:'Campanha não encontrada.',list:base}:{ok:true,list:next}}
export function campaignById(list=[],campaignId){const id=text(campaignId);return arr(list).map(sanitizeCampaign).find(c=>c.id===id)||null}
export function findCampaignForCharacter(list=[],characterId){const id=text(characterId);if(!id)return null;for(const campaign of arr(list).map(sanitizeCampaign)){const member=campaign.members.find(m=>m.characterId===id);if(member)return{campaign,member}}return null}
export function addCampaignMember(list=[],campaignId,data={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const member=sanitizeMember({...data,id:data.id||campaignUid('member')});campaign.members.push(member);campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,member}}
export function updateCampaignMember(list=[],campaignId,memberId,patch={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const index=campaign.members.findIndex(m=>m.id===text(memberId));if(index<0)return{ok:false,reason:'Participante não encontrado.',list:arr(list).map(sanitizeCampaign)};campaign.members[index]=sanitizeMember({...campaign.members[index],...patch,id:campaign.members[index].id});campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,member:campaign.members[index]}}
export function removeCampaignMember(list=[],campaignId,memberId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const before=campaign.members.length;campaign.members=campaign.members.filter(m=>m.id!==text(memberId));if(campaign.members.length===before)return{ok:false,reason:'Participante não encontrado.',list:arr(list).map(sanitizeCampaign)};campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign}}
export function assignCharacterToMember(list=[],campaignId,memberId,characterId){const targetCampaignId=text(campaignId),targetMemberId=text(memberId),charId=text(characterId);if(!charId)return{ok:false,reason:'Selecione um personagem.',list:arr(list).map(sanitizeCampaign)};const clean=arr(list).map(sanitizeCampaign),target=clean.find(c=>c.id===targetCampaignId),member=target?.members.find(m=>m.id===targetMemberId);if(!target||!member)return{ok:false,reason:'Mesa ou participante não encontrado.',list:clean};let movedFrom=null;for(const campaign of clean)for(const row of campaign.members)if(row.characterId===charId){if(campaign.id!==targetCampaignId||row.id!==targetMemberId)movedFrom={campaignId:campaign.id,campaignName:campaign.name,memberId:row.id};row.characterId=null;campaign.updatedAt=now()}member.characterId=charId;target.updatedAt=now();return{ok:true,list:clean,campaign:target,member,movedFrom}}
export function unassignCharacterFromMember(list=[],campaignId,memberId){return updateCampaignMember(list,campaignId,memberId,{characterId:null})}
export function addCampaignSession(list=[],campaignId,data={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const maxNumber=campaign.sessions.reduce((m,s)=>Math.max(m,s.number),0),session=sanitizeSession({...data,id:data.id||campaignUid('session'),number:data.number||maxNumber+1,createdAt:now(),updatedAt:now()},maxNumber);campaign.sessions.push(session);campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session}}
export function updateCampaignSession(list=[],campaignId,sessionId,patch={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const index=campaign.sessions.findIndex(s=>s.id===text(sessionId));if(index<0)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};campaign.sessions[index]=sanitizeSession({...campaign.sessions[index],...patch,id:campaign.sessions[index].id,createdAt:campaign.sessions[index].createdAt,updatedAt:now()},index);if(campaign.activeSessionId===campaign.sessions[index].id&&campaign.sessions[index].status!=='active')campaign.activeSessionId=null;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session:campaign.sessions[index]}}
export function startCampaignSession(list=[],campaignId,sessionId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const session=campaign.sessions.find(s=>s.id===text(sessionId));if(!session)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};const other=campaign.sessions.find(s=>s.status==='active'&&s.id!==session.id);if(other)return{ok:false,reason:`Finalize a sessão ativa (${other.title}) antes de iniciar outra.`,list:arr(list).map(sanitizeCampaign)};session.status='active';session.updatedAt=now();campaign.activeSessionId=session.id;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session}}
export function finishCampaignSession(list=[],campaignId,sessionId,patch={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const session=campaign.sessions.find(s=>s.id===text(sessionId));if(!session)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};const activeEncounter=session.encounters?.find(e=>e.status==='active')||null;if(session.activeEncounterId||activeEncounter)return{ok:false,reason:`Finalize o encontro ativo (${activeEncounter?.title||'encontro em andamento'}) antes de concluir a sessão.`,list:arr(list).map(sanitizeCampaign)};const result=updateCampaignSession(list,campaignId,sessionId,{...patch,status:'completed'});if(!result.ok)return result;result.campaign.activeSessionId=null;result.campaign.updatedAt=now();result.list=result.list.map(row=>row.id===result.campaign.id?result.campaign:row);return result}
export function cancelCampaignSession(list=[],campaignId,sessionId){return updateCampaignSession(list,campaignId,sessionId,{status:'cancelled'})}
export function removeCampaignSession(list=[],campaignId,sessionId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const id=text(sessionId),before=campaign.sessions.length;campaign.sessions=campaign.sessions.filter(s=>s.id!==id);if(campaign.sessions.length===before)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};if(campaign.activeSessionId===id)campaign.activeSessionId=null;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign}}
export function campaignContextForCharacter(list=[],characterId){const found=findCampaignForCharacter(list,characterId);if(!found)return null;const activeSession=found.campaign.sessions.find(s=>s.id===found.campaign.activeSessionId)||null;return{...found,activeSession}}
export function allCampaignSessions(list=[]){return arr(list).map(sanitizeCampaign).flatMap(campaign=>campaign.sessions.map(session=>({campaignId:campaign.id,campaignName:campaign.name,...session}))).sort((a,b)=>String(b.date||b.updatedAt).localeCompare(String(a.date||a.updatedAt))||b.number-a.number)}
function mutateCampaignEntity(list=[],campaignId,key,entityId,patch,remove=false){
 const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};
 const sanitize=key==='npcs'?sanitizeCampaignNpc:key==='locations'?sanitizeCampaignLocation:null;if(!sanitize)return{ok:false,reason:'Coleção inválida.',list:arr(list).map(sanitizeCampaign)};
 if(remove){const before=campaign[key].length;campaign[key]=campaign[key].filter(row=>row.id!==text(entityId));if(before===campaign[key].length)return{ok:false,reason:'Registro não encontrado.',list:arr(list).map(sanitizeCampaign)};campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign}}
 const index=campaign[key].findIndex(row=>row.id===text(entityId));if(index<0)return{ok:false,reason:'Registro não encontrado.',list:arr(list).map(sanitizeCampaign)};
 const old=campaign[key][index];campaign[key][index]=sanitize({...old,...patch,id:old.id,createdAt:old.createdAt,updatedAt:now()});campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,entity:campaign[key][index]}
}
function addCampaignEntity(list=[],campaignId,key,data={}){
 const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};
 const sanitize=key==='npcs'?sanitizeCampaignNpc:key==='locations'?sanitizeCampaignLocation:null;if(!sanitize)return{ok:false,reason:'Coleção inválida.',list:arr(list).map(sanitizeCampaign)};
 const entity=sanitize({...data,id:data.id||campaignUid(key==='npcs'?'npc':'location'),createdAt:now(),updatedAt:now()});campaign[key].push(entity);campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,entity}
}
export const addCampaignNpc=(list,id,data={})=>addCampaignEntity(list,id,'npcs',data);
export const updateCampaignNpc=(list,id,entityId,patch={})=>mutateCampaignEntity(list,id,'npcs',entityId,patch);
export const removeCampaignNpc=(list,id,entityId)=>mutateCampaignEntity(list,id,'npcs',entityId,{},true);
export const addCampaignLocation=(list,id,data={})=>addCampaignEntity(list,id,'locations',data);
export const updateCampaignLocation=(list,id,entityId,patch={})=>mutateCampaignEntity(list,id,'locations',entityId,patch);
export function removeCampaignLocation(list,id,entityId){const result=mutateCampaignEntity(list,id,'locations',entityId,{},true);if(!result.ok)return result;for(const npc of result.campaign.npcs)if(npc.currentLocationId===text(entityId))npc.currentLocationId=null;result.campaign.updatedAt=now();return result}
