import{readCampaigns,writeCampaigns,createCampaign,updateCampaign,removeCampaign,campaignUid}from'./campaign-state.js?v=20260925-media1';
import{readAdventures,writeAdventures,removeAdventuresForCampaign}from'./adventure-state.js?v=20260925-media1';
import{uploadImage,deleteImage,persistCampaignMediaState,imageElementHtml,imagePickerHtml,bindImagePicker,hydrateMediaImages}from'./image-media.js?v=20260925-media2';
import{playerMode,sharedCampaignRows}from'./collaboration-view.js?v=20260917-player-catalog1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DM_NAME='Rafael',SYSTEM_NAME='D&D 5.5e';
let campaigns=[],readOnly=false,pendingCoverFile=null;
function persist(list){campaigns=writeCampaigns(list);render()}
function statusLabel(status){return({planned:'Planejada',active:'Em andamento',paused:'Pausada',finished:'Concluída'}[status]||status)}
function card(c){const sessions=Array.isArray(c.sessions)?c.sessions:[],active=sessions.find(s=>s.id===c.activeSessionId),linked=(c.members||[]).filter(m=>m.characterId).length,cover=imageElementHtml(c.coverImage,c.coverImageUrl,{className:'campaign-card-cover',alt:''});return`<article class='campaign-card'><div class='campaign-card-main'>${cover}<div><h2>${esc(c.name)}</h2><div><span class='badge ${esc(c.status)}'>${esc(statusLabel(c.status))}</span>${readOnly?'<span class="badge">Somente leitura</span>':''}</div>${c.description?`<p>${esc(c.description)}</p>`:''}<p class='mini'>${(c.members||[]).length} jogador(es) · ${linked} personagem(ns) · ${sessions.length} sessão(ões)${active?` · <strong>em andamento: ${esc(active.title)}</strong>`:''}</p></div></div><div class='row-actions'><a class='btn' href='mesa.html?id=${encodeURIComponent(c.id)}'>Abrir campanha</a>${readOnly?'':`${c.status==='active'?`<button type='button' class='secondary' data-status='paused' data-id='${esc(c.id)}'>Pausar</button>`:`<button type='button' class='secondary' data-status='active' data-id='${esc(c.id)}'>Iniciar</button>`}${c.status!=='finished'?`<button type='button' class='secondary' data-status='finished' data-id='${esc(c.id)}'>Concluir</button>`:''}<button type='button' class='danger' data-delete='${esc(c.id)}'>Excluir</button>`}</div></article>`}
function render(){const box=$('campaign-list');if(!box)return;const ordered=[...campaigns].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));box.innerHTML=ordered.length?`<div class="list">${ordered.map(card).join('')}</div>`:`<div class="empty">${readOnly?'Nenhuma Mesa atribuída.':'Nenhuma campanha criada.'}</div>`;if(readOnly)return;box.querySelectorAll('[data-status]').forEach(button=>button.addEventListener('click',()=>{const result=updateCampaign(campaigns,button.dataset.id,{status:button.dataset.status});if(result.ok)persist(result.list)}));box.querySelectorAll('[data-delete]').forEach(button=>button.addEventListener('click',()=>{if(!confirm('Excluir esta campanha? Os personagens não serão excluídos. As aventuras vinculadas a esta campanha também serão removidas.'))return;const campaignId=button.dataset.delete,target=campaigns.find(row=>row.id===campaignId),linkedAdventures=readAdventures().filter(row=>row.campaignId===campaignId),result=removeCampaign(campaigns,campaignId);if(result.ok){writeAdventures(removeAdventuresForCampaign(readAdventures(),campaignId));persist(result.list);[target?.coverImage,...(target?.sessions||[]).map(row=>row.coverImage),...linkedAdventures.map(row=>row.coverImage)].filter(Boolean).forEach(media=>deleteImage(media).catch(()=>{}))}}));hydrateMediaImages(box).catch(()=>{})}
async function create(){if(readOnly)return;const name=$('campaign-name')?.value.trim();if(!name)return;const id=campaignUid(),note=$('storage-note'),before=campaigns;let published=false,media=null,baseList=null;try{const base=createCampaign(campaigns,{id,name,system:SYSTEM_NAME,dmName:DM_NAME,status:$('campaign-status')?.value||'planned',coverImage:null,coverImageUrl:'',description:$('campaign-description')?.value});if(!base.ok)return;baseList=base.list;campaigns=writeCampaigns(baseList);if(note)note.textContent='Salvando campanha...';await persistCampaignMediaState(id);published=true;if(pendingCoverFile){if(note)note.textContent='Salvando imagem...';media=await uploadImage({campaignId:id,entityType:'campaign',entityId:id,file:pendingCoverFile});const linked=updateCampaign(campaigns,id,{coverImage:media,coverImageUrl:''});if(!linked.ok)throw new Error(linked.reason);campaigns=writeCampaigns(linked.list);try{await persistCampaignMediaState(id)}catch(error){campaigns=writeCampaigns(baseList);await persistCampaignMediaState(id).catch(()=>{});await deleteImage(media).catch(()=>{});media=null;throw error}}location.href=`mesa.html?id=${encodeURIComponent(id)}`}catch(error){if(!published)campaigns=writeCampaigns(before);if(media)await deleteImage(media).catch(()=>{});if(note)note.textContent=error?.message||'Não foi possível salvar a campanha e a imagem.'}}
function normalizeLocalCampaigns(){const list=readCampaigns();if(!list.some(c=>c.dmName!==DM_NAME))return list;return writeCampaigns(list.map(c=>c.dmName===DM_NAME?c:{...c,dmName:DM_NAME}))}
function loadVisibleCampaigns(){readOnly=playerMode();campaigns=readOnly?sharedCampaignRows().map(row=>row.campaign):normalizeLocalCampaigns();const createCard=$('campaign-create-card');if(createCard)createCard.hidden=readOnly;const note=$('storage-note');if(note)note.textContent=readOnly?'Somente leitura.':''}
function refreshFromRemote(event){event.detail?.claim?.();loadVisibleCampaigns();render()}
function init(){loadVisibleCampaigns();if(!readOnly){const holder=$('campaign-cover-picker');if(holder){holder.innerHTML=imagePickerHtml({});bindImagePicker(holder.querySelector('[data-image-picker]'),{onSelect:async file=>{pendingCoverFile=file},onRemove:async()=>{pendingCoverFile=null},onError:error=>{const note=$('storage-note');if(note)note.textContent=error?.message||'Não foi possível usar esta imagem.'}})}$('create-campaign')?.addEventListener('click',create);$('campaign-name')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();create()}})}render();window.addEventListener('hub-rpg:remote-updated',refreshFromRemote)}
init();