import{sanitizeEncounterSessionFields}from'./encounter-state.js?v=20260902-encounters1';

export const CAMPAIGN_KEY='hub-rpg:campaigns:v1';
export const CAMPAIGN_SCHEMA='hub-rpg/campaign/v1';
const CAMPAIGN_STATUS=new Set(['active','paused','finished']);
const SESSION_STATUS=new Set(['planned','active','completed','cancelled']);
const MEMBER_ROLES=new Set(['dm','player','observer']);
const text=v=>String(v??'').trim();
const arr=v=>Array.isArray(v)?v:[];
const now=()=>new Date().toISOString();
export function campaignUid(prefix='cmp'){return globalThis.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
function sanitizeMember(row={}){return{id:text(row.id)||campaignUid('member'),name:text(row.name)||'Participante',role:MEMBER_ROLES.has(row.role)?row.role:'player',characterId:text(row.characterId)||null,notes:String(row.notes??''),active:row.active!==false}}
function sanitizeSession(row={},index=0){const status=SESSION_STATUS.has(row.status)?row.status:'planned',encounterFields=sanitizeEncounterSessionFields(row);return{id:text(row.id)||campaignUid('session'),number:Math.max(1,Math.floor(Number(row.number)||index+1)),title:text(row.title)||`Sessão ${Math.max(1,Math.floor(Number(row.number)||index+1))}`,date:text(row.date),status,location:String(row.location??''),objective:String(row.objective??''),summary:String(row.summary??''),sharedNotes:String(row.sharedNotes??''),dmNotes:String(row.dmNotes??''),participantCharacterIds:[...new Set(arr(row.participantCharacterIds).map(text).filter(Boolean))],...encounterFields,createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
export function sanitizeCampaign(row={}){const sessions=arr(row.sessions).map(sanitizeSession);let activeSessionId=text(row.activeSessionId)||null;const active=sessions.filter(s=>s.status==='active');if(activeSessionId&&!sessions.some(s=>s.id===activeSessionId&&s.status==='active'))activeSessionId=null;if(!activeSessionId&&active.length)activeSessionId=active[0].id;for(const session of sessions)if(session.status==='active'&&session.id!==activeSessionId)session.status='planned';return{schema:CAMPAIGN_SCHEMA,id:text(row.id)||campaignUid(),name:text(row.name)||'Nova Campanha',status:CAMPAIGN_STATUS.has(row.status)?row.status:'active',system:text(row.system)||'D&D 5.5e',setting:String(row.setting??''),description:String(row.description??''),dmName:String(row.dmName??''),schedule:String(row.schedule??''),currentArc:String(row.currentArc??''),currentLocation:String(row.currentLocation??''),partyGoal:String(row.partyGoal??''),sharedNotes:String(row.sharedNotes??''),dmNotes:String(row.dmNotes??''),partyTreasure:String(row.partyTreasure??''),members:arr(row.members).map(sanitizeMember),sessions,activeSessionId,createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}}
export function readCampaigns(storage=globalThis.localStorage){if(!storage)return[];try{const raw=JSON.parse(storage.getItem(CAMPAIGN_KEY)||'[]');return arr(raw).map(sanitizeCampaign)}catch{return[]}}
export function writeCampaigns(list,storage=globalThis.localStorage){const clean=arr(list).map(sanitizeCampaign);if(storage)storage.setItem(CAMPAIGN_KEY,JSON.stringify(clean));return clean}
export function createCampaign(list=[],data={}){const campaign=sanitizeCampaign({...data,id:data.id||campaignUid(),createdAt:now(),updatedAt:now()}),next=[...arr(list).map(sanitizeCampaign),campaign];return{ok:true,list:next,campaign}}
export function updateCampaign(list=[],campaignId,patch={}){const id=text(campaignId);let campaign=null,found=false;const next=arr(list).map(row=>{const c=sanitizeCampaign(row);if(c.id!==id)return c;found=true;campaign=sanitizeCampaign({...c,...patch,id:c.id,createdAt:c.createdAt,updatedAt:now()});return campaign});return found?{ok:true,list:next,campaign}:{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)}}
export function removeCampaign(list=[],campaignId){const id=text(campaignId),base=arr(list).map(sanitizeCampaign),next=base.filter(c=>c.id!==id);return next.length===base.length?{ok:false,reason:'Campanha não encontrada.',list:base}:{ok:true,list:next}}
export function campaignById(list=[],campaignId){const id=text(campaignId);return arr(list).map(sanitizeCampaign).find(c=>c.id===id)||null}
export function findCampaignForCharacter(list=[],characterId){const id=text(characterId);if(!id)return null;for(const campaign of arr(list).map(sanitizeCampaign)){const member=campaign.members.find(m=>m.characterId===id);if(member)return{campaign,member}}return null}
export function addCampaignMember(list=[],campaignId,data={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const member=sanitizeMember({...data,id:data.id||campaignUid('member')});campaign.members.push(member);campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,member}}
export function updateCampaignMember(list=[],campaignId,memberId,patch={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const index=campaign.members.findIndex(m=>m.id===text(memberId));if(index<0)return{ok:false,reason:'Participante não encontrado.',list:arr(list).map(sanitizeCampaign)};campaign.members[index]=sanitizeMember({...campaign.members[index],...patch,id:campaign.members[index].id});campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,member:campaign.members[index]}}
export function removeCampaignMember(list=[],campaignId,memberId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const before=campaign.members.length;campaign.members=campaign.members.filter(m=>m.id!==text(memberId));if(campaign.members.length===before)return{ok:false,reason:'Participante não encontrado.',list:arr(list).map(sanitizeCampaign)};campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign}}
export function assignCharacterToMember(list=[],campaignId,memberId,characterId){const targetCampaignId=text(campaignId),targetMemberId=text(memberId),charId=text(characterId);if(!charId)return{ok:false,reason:'Selecione um personagem.',list:arr(list).map(sanitizeCampaign)};const clean=arr(list).map(sanitizeCampaign),target=clean.find(c=>c.id===targetCampaignId),member=target?.members.find(m=>m.id===targetMemberId);if(!target||!member)return{ok:false,reason:'Mesa ou participante não encontrado.',list:clean};let movedFrom=null;for(const campaign of clean)for(const row of campaign.members)if(row.characterId===charId){if(campaign.id!==targetCampaignId||row.id!==targetMemberId)movedFrom={campaignId:campaign.id,campaignName:campaign.name,memberId:row.id};row.characterId=null;campaign.updatedAt=now()}member.characterId=charId;target.updatedAt=now();return{ok:true,list:clean,campaign:target,member,movedFrom}}
export function unassignCharacterFromMember(list=[],campaignId,memberId){return updateCampaignMember(list,campaignId,memberId,{characterId:null})}
export function addCampaignSession(list=[],campaignId,data={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const maxNumber=campaign.sessions.reduce((m,s)=>Math.max(m,s.number),0),session=sanitizeSession({...data,id:data.id||campaignUid('session'),number:data.number||maxNumber+1,createdAt:now(),updatedAt:now()},maxNumber);campaign.sessions.push(session);campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session}}
export function updateCampaignSession(list=[],campaignId,sessionId,patch={}){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const index=campaign.sessions.findIndex(s=>s.id===text(sessionId));if(index<0)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};campaign.sessions[index]=sanitizeSession({...campaign.sessions[index],...patch,id:campaign.sessions[index].id,createdAt:campaign.sessions[index].createdAt,updatedAt:now()},index);if(campaign.activeSessionId===campaign.sessions[index].id&&campaign.sessions[index].status!=='active')campaign.activeSessionId=null;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session:campaign.sessions[index]}}
export function startCampaignSession(list=[],campaignId,sessionId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const session=campaign.sessions.find(s=>s.id===text(sessionId));if(!session)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};const other=campaign.sessions.find(s=>s.status==='active'&&s.id!==session.id);if(other)return{ok:false,reason:`Finalize a sessão ativa (${other.title}) antes de iniciar outra.`,list:arr(list).map(sanitizeCampaign)};session.status='active';session.updatedAt=now();campaign.activeSessionId=session.id;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign,session}}
export function finishCampaignSession(list=[],campaignId,sessionId,patch={}){const result=updateCampaignSession(list,campaignId,sessionId,{...patch,status:'completed'});if(!result.ok)return result;result.campaign.activeSessionId=null;result.campaign.updatedAt=now();result.list=result.list.map(row=>row.id===result.campaign.id?result.campaign:row);return result}
export function cancelCampaignSession(list=[],campaignId,sessionId){return updateCampaignSession(list,campaignId,sessionId,{status:'cancelled'})}
export function removeCampaignSession(list=[],campaignId,sessionId){const campaign=campaignById(list,campaignId);if(!campaign)return{ok:false,reason:'Campanha não encontrada.',list:arr(list).map(sanitizeCampaign)};const id=text(sessionId),before=campaign.sessions.length;campaign.sessions=campaign.sessions.filter(s=>s.id!==id);if(campaign.sessions.length===before)return{ok:false,reason:'Sessão não encontrada.',list:arr(list).map(sanitizeCampaign)};if(campaign.activeSessionId===id)campaign.activeSessionId=null;campaign.updatedAt=now();return{ok:true,list:arr(list).map(row=>row.id===campaign.id?campaign:sanitizeCampaign(row)),campaign}}
export function campaignContextForCharacter(list=[],characterId){const found=findCampaignForCharacter(list,characterId);if(!found)return null;const activeSession=found.campaign.sessions.find(s=>s.id===found.campaign.activeSessionId)||null;return{...found,activeSession}}
export function allCampaignSessions(list=[]){return arr(list).map(sanitizeCampaign).flatMap(campaign=>campaign.sessions.map(session=>({campaignId:campaign.id,campaignName:campaign.name,...session}))).sort((a,b)=>String(b.date||b.updatedAt).localeCompare(String(a.date||a.updatedAt))||b.number-a.number)}
