document.body?.classList.add('controles');
const loading=document.getElementById('loading');
const builder=document.getElementById('builder');
const warnings=document.getElementById('load-warnings');
function showBuilder(){if(loading){loading.textContent='';loading.hidden=true}if(builder)builder.hidden=false}
showBuilder();

const NativeMutationObserver=window.MutationObserver;
window.MutationObserver=class HubBuilderMutationObserver extends NativeMutationObserver{
  observe(target,options={}){
    if(target===document.body&&options?.subtree&&options?.characterData)return;
    return super.observe(target,options)
  }
};

function warn(label,error){
  console.error(`[character-builder] ${label}`,error);
  if(!warnings)return;
  warnings.hidden=false;
  const row=document.createElement('div');
  row.innerHTML=`<strong>${label}</strong>${error?`<br>${String(error.message||error)}`:''}`;
  warnings.appendChild(row)
}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fillMenu(id,items,placeholder,value){const el=document.getElementById(id);if(!el)return;const rows=(items||[]).slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'pt-BR'));el.innerHTML=`<option value="">${esc(placeholder)}</option>${rows.map(x=>`<option value="${esc(x.id)}" ${x.id===value?'selected':''}>${esc(x.name)}</option>`).join('')}`}
const ELADRIN_FALLBACK={id:'especies:motm-2022:eladrin',name:'Eladrin',ruleset:'5e',revision:2014,status:'legado_compativel',compatibleWith:['5.5e'],source:'Mordenkainen Presents: Monsters of the Multiverse (2022)',sizes:['Medium'],speed:30,abilityBonuses:[],traits:[{name:'Elf Kin',originalName:'Elf Kin',text:'Também é considerado elfo para pré-requisitos e efeitos que exijam essa ascendência.'},{name:'Darkvision',originalName:'Darkvision',text:'Visão no escuro com alcance de 60 pés.'},{name:'Fey Ancestry',originalName:'Fey Ancestry',text:'Vantagem em salvaguardas para evitar ou encerrar a condição Enfeitiçado.'},{name:'Fey Step',originalName:'Fey Step',text:'Como Ação Bônus, teleporta-se até 30 pés. No nível 3, o efeito adicional depende da estação escolhida: Outono, Inverno, Primavera ou Verão.'},{name:'Keen Senses',originalName:'Keen Senses',text:'Ganha proficiência em Percepção.'},{name:'Trance',originalName:'Trance',text:'Não precisa dormir. Um Descanso Longo pode ser concluído em 4 horas de transe; ao terminá-lo, pode mudar de estação e adquirir temporariamente duas proficiências em armas ou ferramentas até o próximo Descanso Longo.'}]};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
function ensureEladrin(items,character=null){const rows=Array.isArray(items)?[...items]:[],elf=rows.find(x=>['elf','elfo'].includes(norm(x?.name))),standalone=rows.find(x=>norm(x?.name)==='eladrin');if(!elf)return rows;const existing=(elf.lineages||[]).find(x=>norm(x?.name)==='eladrin'),source=standalone||ELADRIN_FALLBACK;if(!existing)elf.lineages=[...(elf.lineages||[]),{name:'Eladrin',replaceBaseTraits:true,packageId:source.id,source:source.source,ruleset:source.ruleset,revision:source.revision,status:source.status,compatibleWith:source.compatibleWith||[],sizes:source.sizes||['Medium'],speed:source.speed||30,traits:(source.traits||[]).map(x=>({...x})),abilityBonuses:source.abilityBonuses||[],fixedSkills:['Percepção']}];if(character?.refs?.species===source.id||character?.refs?.species===ELADRIN_FALLBACK.id){character.refs.species=elf.id;character.choices.species=character.choices.species||{};character.choices.species.lineage='Eladrin'}return rows.filter(x=>norm(x?.name)!=='eladrin')}
function updateCounts(state){const count=document.getElementById('catalog-counts');if(!count)return;const parts=[];if(state.catalogs.classes.length)parts.push(`${state.catalogs.classes.length} classes`);if(state.catalogs.species.length){const lineages=state.catalogs.species.reduce((n,s)=>n+(s.lineages||[]).length,0);parts.push(`${state.catalogs.species.length} raças-base · ${lineages} linhagens/legados`)}if(state.catalogs.backgrounds.length)parts.push(`${state.catalogs.backgrounds.length} antecedentes`);count.textContent=parts.join(' · ')}
function localClassFallback(rows){const names={barbarian:'Bárbaro',bard:'Bardo',cleric:'Clérigo',druid:'Druida',fighter:'Guerreiro',monk:'Monge',paladin:'Paladino',ranger:'Patrulheiro',rogue:'Ladino',sorcerer:'Feiticeiro',warlock:'Bruxo',wizard:'Mago'},skills={'animal handling':'Adestrar Animais',acrobatics:'Acrobacia',arcana:'Arcanismo',athletics:'Atletismo',deception:'Enganação',history:'História',insight:'Intuição',intimidation:'Intimidação',investigation:'Investigação',medicine:'Medicina',nature:'Natureza',perception:'Percepção',performance:'Atuação',persuasion:'Persuasão',religion:'Religião','sleight of hand':'Prestidigitação',stealth:'Furtividade',survival:'Sobrevivência'},ability={STR:'Força',DEX:'Destreza',CON:'Constituição',INT:'Inteligência',WIS:'Sabedoria',CHA:'Carisma'},skillName=v=>skills[String(v||'').replace(/^Skill:\s*/i,'').toLowerCase()]||String(v||'').replace(/^Skill:\s*/i,'');return(rows||[]).map(c=>({id:`classes:srd521:${c.index}`,slug:c.index,name:names[c.index]||c.name,ruleset:'5.5e',revision:2024,status:'atual',source:'Base local SRD 5.2.1',hitDie:Number(c.hit_die)||8,savingThrows:(c.saving_throws||[]).map(x=>ability[x.name]||x.name),proficiencies:(c.proficiencies||[]).map(x=>x.name),proficienciesRaw:(c.proficiencies||[]).map(x=>x.name),skillChoices:(c.proficiency_choices||[]).map(ch=>({choose:Number(ch.choose)||1,options:[...new Set((ch?.from?.options||[]).flatMap(o=>o?.item?.name?[skillName(o.item.name)]:[]))]})).filter(x=>x.options.length),features:[],levels:[],featSlots:[],spellAbility:ability[c.spellcasting?.spellcasting_ability?.name]||''}))}
function restoreMenus(payload){if(!payload?.state)return;const{state,loaded}=payload;loaded.species=ensureEladrin(loaded.species,state.c);state.catalogs.species=ensureEladrin(state.catalogs.species,state.c);for(const key of['classes','species','backgrounds'])if((loaded[key]||[]).length&&(key==='species'||(loaded[key]||[]).length>(state.catalogs[key]||[]).length))state.catalogs[key]=loaded[key];fillMenu('classe',state.catalogs.classes,'Selecione a classe',state.c.refs.class);fillMenu('especie',state.catalogs.species,'Selecione a raça',state.c.refs.species);fillMenu('antecedente',state.catalogs.backgrounds,'Selecione o antecedente',state.c.refs.background);updateCounts(state);showBuilder()}

async function preloadMainMenus(){
  try{
    const[stateMod,catalogMod]=await Promise.all([import('./character-builder/state.js'),import('./character-builder/catalogs.js?v=20260824-race-variants1')]);
    const{state,loadCharacter,json}=stateMod;if(!state.c)state.c=loadCharacter();
    const[g,loc]=await Promise.all([json('dados/localizacao-ptbr-global.json').catch(()=>({})),json('dados/localizacao-ptbr-especies.json').catch(()=>({species:{},lineages:{},traits:{}}))]);state.G=g;state.LOCSP=loc;showBuilder();const loaded={classes:[],species:[],backgrounds:[]};
    const jobs=[{label:'Classes',key:'classes',id:'classe',placeholder:'Selecione a classe',load:()=>catalogMod.loadClasses()},{label:'Raças',key:'species',id:'especie',placeholder:'Selecione a raça',load:()=>catalogMod.loadSpecies()},{label:'Antecedentes',key:'backgrounds',id:'antecedente',placeholder:'Selecione o antecedente',load:()=>catalogMod.loadBackgrounds()}];
    await Promise.all(jobs.map(async job=>{try{let items=await job.load();if(job.key==='species')items=ensureEladrin(items,state.c);if(job.key==='classes'&&(!items||items.filter(x=>x.slug!=='artificer').length<12)){const base=await json('dados/classes-base-2024.json').catch(()=>[]),fallback=localClassFallback(base),extras=(items||[]).filter(x=>x.slug==='artificer'||!fallback.some(f=>f.slug===x.slug));if(fallback.length===12){items=[...fallback,...extras];state.warnings.push('Progressão detalhada das classes-base depende da fonte SRD externa; o catálogo local foi usado para manter as escolhas disponíveis.')}}loaded[job.key]=items||[];if(items?.length)state.catalogs[job.key]=items;fillMenu(job.id,state.catalogs[job.key],job.placeholder,job.key==='classes'?state.c.refs.class:job.key==='species'?state.c.refs.species:state.c.refs.background);updateCounts(state);showBuilder()}catch(error){if(job.key==='species'){const items=ensureEladrin(state.catalogs.species,state.c);state.catalogs.species=items;loaded.species=items;fillMenu('especie',items,'Selecione a raça',state.c.refs.species)}else fillMenu(job.id,state.catalogs[job.key],job.placeholder,null);warn(`${job.label} não puderam ser carregados.`,error);showBuilder()}}));return{state,loaded}
  }catch(error){warn('Falha no carregador independente dos menus principais.',error);showBuilder();return null}
}

async function start(){
  const menuPromise=preloadMainMenus();let core;
  try{core=await import('./character-builder/ui.js?v=20260831-warlock-invocations2');if(typeof core.init!=='function')throw new Error('O módulo principal não exporta init().');const corePromise=core.init();showBuilder();await corePromise;showBuilder()}
  catch(error){warn('Falha ao iniciar o núcleo da Criação de Personagem.',error);const payload=await menuPromise;restoreMenus(payload);return}
  const payload=await menuPromise;restoreMenus(payload);
  const extensions=[['./character-builder/ability-score-ui.js?v=20260824-ability-budget4','initAbilityScoreUi'],['./character-builder/spell-selection-ui.js?v=20260824-character-builder28','initSpellSelectionUi'],['./character-builder/spell-swap-ui.js?v=20260825-spell-swap-visible1','initSpellSwapUi'],['./character-builder/spell-quota-ui.js?v=20260824-character-builder28','initSpellQuotaUi'],['./character-builder/profile-ui.js?v=20260824-character-builder29','initCharacterProfileUi'],['./character-builder/species-trait-ui.js?v=20260824-character-builder30','initSpeciesTraitUi'],['./character-builder/tiefling-ui.js?v=20260824-race-variants1','initTieflingUi'],['./character-builder/species-selection-refinement-ui.js?v=20260824-race-choice1','initSpeciesSelectionRefinementUi'],['./character-builder/class-skill-ui.js?v=20260831-warlock-invocations2','initClassSkillUi'],['./character-builder/house-rules-ui.js?v=20260831-warlock-invocations2','initHouseRulesUi'],['./character-builder/background-special-feat-ui.js?v=20260831-background-special-feat1','initBackgroundSpecialFeatUi'],['./character-builder/feat-ui.js?v=20260824-character-builder28','initFeatUi'],['./character-builder/house-feat-prereq-ui.js?v=20260831-warlock-invocations2','initHouseFeatPrereqUi'],['./character-builder/language-ui.js?v=20260824-character-builder30','initLanguageUi'],['./character-builder/package-b-purchase-ui.js?v=20260831-warlock-invocations2','initPackageBPurchaseUi'],['./character-builder/equipment-ownership-ui.js?v=20260831-warlock-invocations2','initEquipmentOwnershipUi'],['./character-builder/wizard-ui.js?v=20260831-warlock-invocations2','initWizardUi']];
  for(const[path,name]of extensions){try{const mod=await import(path);if(typeof mod[name]==='function')mod[name]();else warn(`Extensão sem inicializador: ${name}.`)}catch(error){warn(`Extensão opcional não carregada: ${name}.`,error)}}showBuilder()
}
start();