import{createFirebaseCollaborationProvider,loadFirebaseConfig}from'./firebase-collaboration-provider.js?v=20260904-collab2';
import{readCampaigns}from'./campaign-state.js?v=20260902-encounters1';
import{read as readCharacters}from'./character-builder/state.js';
import{syncAll,publishLocalCampaign,publishMembershipCharacter}from'./collaboration-sync.js?v=20260902-collab1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let provider=null,user=null,memberships=[],authorizedUsers=[];
function feedback(message,ok=true){const box=$('collab-feedback');box.hidden=false;box.className=`status ${ok?'ok':'warning'}`;box.textContent=message}
function localCampaignOptions(){const campaigns=readCampaigns();return campaigns.length?campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''):'<option value="">Nenhuma Mesa local</option>'}
function fillCampaigns(){$('publish-campaign').innerHTML=localCampaignOptions();if($('membership-campaign'))$('membership-campaign').innerHTML=localCampaignOptions()}
function roleName(role){return({dm:'Mestre',player:'Jogador',observer:'Observador'}[role]||role)}
async function refreshRemote(){if(!user)return;memberships=await provider.listMemberships();const chars=readCharacters();$('membership-list').innerHTML=memberships.length?memberships.map(m=>`<div class="row"><strong>${esc(m.campaignId)}</strong> <span class="badge">${esc(roleName(m.role))}</span><div class="mini">${m.characterId?`Personagem vinculado: ${esc(m.characterId)}`:'Sem personagem online vinculado.'}</div>${m.role==='player'?`<label style="margin-top:7px">Personagem<select data-link-character="${esc(m.campaignId)}"><option value="">— Nenhum —</option>${chars.map(c=>`<option value="${esc(c.id)}" ${c.id===m.characterId?'selected':''}>${esc(c.name||c.id)}</option>`).join('')}</select></label>`:''}</div>`).join(''):'<div class="muted">Nenhuma Mesa online vinculada.</div>';$('membership-list').querySelectorAll('[data-link-character]').forEach(select=>select.addEventListener('change',async()=>{try{if(select.value)await publishMembershipCharacter(provider,select.dataset.linkCharacter,select.value);else await provider.linkMembershipCharacter(select.dataset.linkCharacter,null);feedback('Personagem online da Mesa atualizado.');await refreshRemote()}catch(e){feedback(e.message,false)}}))}
async function refreshAdmin(){if(!user?.isAdmin)return;authorizedUsers=await provider.listAuthorizedUsers();$('authorized-user-list').innerHTML=authorizedUsers.length?authorizedUsers.map(row=>`<div class="row"><strong>${esc(row.username)}</strong> ${row.isAdmin?'<span class="badge">Administrador</span>':''} <span class="badge">${row.active?'Ativo':'Bloqueado'}</span><div class="mini">UID: ${esc(row.uid)}</div><div class="actions" style="margin-top:7px"><button type="button" class="secondary" data-toggle-user="${esc(row.uid)}" data-active="${row.active?'true':'false'}" ${row.uid===user.uid?'disabled':''}>${row.active?'Bloquear':'Reativar'}</button></div></div>`).join(''):'<div class="muted">Nenhum usuário autorizado.</div>';$('membership-user').innerHTML=authorizedUsers.filter(row=>row.active).map(row=>`<option value="${esc(row.uid)}">${esc(row.username)}${row.isAdmin?' · admin':''}</option>`).join('')||'<option value="">Nenhum usuário ativo</option>';$('authorized-user-list').querySelectorAll('[data-toggle-user]').forEach(button=>button.addEventListener('click',async()=>{try{await provider.setAuthorizedUserActive(button.dataset.toggleUser,button.dataset.active!=='true');feedback('Status do usuário atualizado.');await refreshAdmin()}catch(e){feedback(e.message,false)}}))}
function renderAccount(){const connected=!!user;$('account-card').hidden=false;$('login-form').hidden=connected;$('sign-out').hidden=!connected;$('online-tools').hidden=!connected;$('admin-tools').hidden=!connected||!user?.isAdmin;$('account-state').innerHTML=connected?`<strong>${esc(user.username)}</strong> ${user.isAdmin?'<span class="badge">Administrador</span>':''}`:'Não conectado.';if(connected){fillCampaigns();refreshRemote().catch(e=>feedback(e.message,false));if(user.isAdmin)refreshAdmin().catch(e=>feedback(e.message,false))}}
async function login(event){event.preventDefault();const username=$('login-username').value.trim(),password=$('login-password').value;try{const result=await provider.signInUsername({username,password});user=result;$('login-password').value='';renderAccount();feedback('Login realizado.')}catch(e){$('login-password').value='';feedback(e.message,false)}}
async function init(){try{const config=await loadFirebaseConfig();if(!config.configured){$('provider-status').className='status warning';$('provider-status').innerHTML='<strong>Bloco 15 ainda não está conectado ao Firebase real.</strong><br>O Hub usa somente site web no GitHub Pages, Firebase Spark / No-cost, Authentication por usuário e senha e Cloud Firestore.';return}provider=await createFirebaseCollaborationProvider({config});$('provider-status').className='status ok';$('provider-status').textContent=`Sincronização web configurada · projeto ${config.projectId} · login fechado por usuário e senha · Spark / No-cost.`;$('login-form').addEventListener('submit',login);$('sign-out').addEventListener('click',async()=>{await provider.signOut();feedback('Sessão encerrada.')});$('sync-all').addEventListener('click',async()=>{try{$('sync-state').textContent='Sincronizando...';const r=await syncAll(provider);$('sync-state').textContent=`Sincronizado em ${new Date(r.at).toLocaleString('pt-BR')}.`;feedback('Dados pessoais e Mesas autorizadas sincronizados.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('publish-campaign-button').addEventListener('click',async()=>{try{const id=$('publish-campaign').value;if(!id)throw new Error('Selecione uma Mesa local.');await publishLocalCampaign(provider,id);feedback('Mesa publicada/sincronizada como Mestre.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('authorize-user-form').addEventListener('submit',async event=>{event.preventDefault();try{const record=await provider.upsertAuthorizedUser({uid:$('authorize-uid').value.trim(),username:$('authorize-username').value.trim(),active:true,isAdmin:$('authorize-admin').checked});feedback(`Usuário ${record.username} autorizado.`);$('authorize-uid').value='';$('authorize-username').value='';$('authorize-admin').checked=false;await refreshAdmin()}catch(e){feedback(e.message,false)}});$('membership-form').addEventListener('submit',async event=>{event.preventDefault();try{const membership=await provider.upsertMembership({campaignId:$('membership-campaign').value,uid:$('membership-user').value,role:$('membership-role').value});feedback(`${membership.displayName} vinculado à Mesa como ${roleName(membership.role)}.`);await refreshAdmin()}catch(e){feedback(e.message,false)}});provider.onAuthChanged(account=>{user=account;renderAccount()});renderAccount()}catch(e){$('provider-status').className='status warning';$('provider-status').textContent=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
