import{KEY as CHARACTER_KEY,read as readCharacters}from'./character-builder/state.js';
import{readCampaigns,writeCampaigns}from'./campaign-state.js?v=20260910-realtime1';
import{readAdventures,writeAdventures}from'./adventure-state.js?v=20260910-realtime1';
import{COLLAB_CACHE_KEY}from'./storage-registry.js?v=20260902-collab1';
import{mergeNewest}from'./collaboration-model.js?v=20260914-login-context1';
const arr=v=>Array.isArray(v)?v:[],now=()=>new Date().toISOString(),text=v=>String(v??'').trim(),username=v=>text(v).toLowerCase();
function replaceRemote(localRows=[],remoteRows=[]){const map=new Map(arr(localRows).filter(row=>text(row?.id)).map(row=>[text(row.id),row]));for(const row of arr(remoteRows))if(text(row?.id))map.set(text(row.id),row);return[...map.values()]}
function replaceCampaignScope(localRows=[],campaignId,remoteRows=[]){const cid=text(campaignId);return[...arr(localRows).filter(row=>text(row?.campaignId)!==cid),...arr(remoteRows)]}
function emptyCache(){return{schema:'hub-rpg/collaboration-cache/v1',campaigns:{},playerCharacters:{},masterCampaignIds:[],updatedAt:null}}
export function readCollaborationCache(storage=globalThis.localStorage){if(!storage)return emptyCache();try{const value=JSON.parse(storage.getItem(COLLAB_CACHE_KEY)||'{}');return{schema:'hub-rpg/collaboration-cache/v1',campaigns:value?.campaigns&&typeof value.campaigns==='object'?value.campaigns:{},playerCharacters:value?.playerCharacters&&typeof value.playerCharacters==='object'?value.playerCharacters:{},masterCampaignIds:arr(value?.masterCampaignIds).map(text).filter(Boolean),updatedAt:value?.updatedAt||null}}catch{return emptyCache()}}
export function writeCollaborationCache(cache,storage=globalThis.localStorage){const clean={schema:'hub-rpg/collaboration-cache/v1',campaigns:cache?.campaigns&&typeof cache.campaigns==='object'?cache.campaigns:{},playerCharacters:cache?.playerCharacters&&typeof cache.playerCharacters==='object'?cache.playerCharacters:{},masterCampaignIds:arr(cache?.masterCampaignIds).map(text).filter(Boolean),updatedAt:now()};storage?.setItem(COLLAB_CACHE_KEY,JSON.stringify(clean));return clean}
function isPlayerAccount(account,provider){return Boolean(account?.username)&&username(account.username)!==username(provider?.config?.ownerUsername||'rafael')}
function sharedCharacterIds(cache){return new Set(Object.values(cache?.campaigns||{}).flatMap(row=>arr(row?.characterIds)).map(text).filter(Boolean))}
function catalogCharacterIds(cache){return new Set(Object.keys(cache?.playerCharacters||{}).map(text).filter(Boolean))}
function ownsCharacter(character,account){return text(character?.ownerUid)===text(account?.uid)||username(character?.ownerUsername)===username(account?.username)}
export async function syncOwnCharacters(provider,{storage=globalThis.localStorage,memberships=null}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const account=await provider.currentUser(),rows=memberships||await provider.listMemberships(),local=readCharacters(),remote=await provider.listOwnCharacters(),cache=readCollaborationCache(storage);if(!isPlayerAccount(account,provider)){const externalIds=catalogCharacterIds(cache),external=local.filter(character=>externalIds.has(text(character?.id))),localOwn=local.filter(character=>!externalIds.has(text(character?.id))),mergedOwn=mergeNewest(localOwn,remote),merged=replaceRemote(mergedOwn,external);storage.setItem(CHARACTER_KEY,JSON.stringify(merged));for(const character of mergedOwn)await provider.saveOwnCharacter(character);return{characters:merged,ownCharacters:mergedOwn,pushed:mergedOwn.length,remote:remote.length,playerCharacters:external.length}}const sharedIds=sharedCharacterIds(cache),ownAssigned=new Set(rows.filter(m=>m?.active!==false&&m?.role==='player').map(m=>text(m.characterId)).filter(Boolean)),remoteIds=new Set(remote.map(character=>text(character?.id)).filter(Boolean)),localOwn=local.filter(character=>{const id=text(character?.id);return ownAssigned.has(id)||remoteIds.has(id)||ownsCharacter(character,account)}),mergedOwn=mergeNewest(localOwn,remote),readOnly=local.filter(character=>sharedIds.has(text(character?.id))&&!ownsCharacter(character,account)),merged=replaceRemote(mergedOwn,readOnly);storage.setItem(CHARACTER_KEY,JSON.stringify(merged));for(const character of mergedOwn)await provider.saveOwnCharacter(character);return{characters:merged,ownCharacters:mergedOwn,pushed:mergedOwn.length,remote:remote.length,shared:sharedIds.size}}
export async function publishLocalCampaign(provider,campaignId,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const campaign=readCampaigns(storage).find(c=>c.id===campaignId);if(!campaign)throw new Error('Campanha local não encontrada.');const adventures=readAdventures(storage).filter(a=>a.campaignId===campaignId),characters=readCharacters();return provider.saveCampaignBundle(campaign,adventures,characters)}
export async function pullCollaborations(provider,{storage=globalThis.localStorage}={}){
 if(!provider?.configured)throw new Error('Sincronização remota não configurada.');
 const account=await provider.currentUser(),memberships=await provider.listMemberships(),cache=readCollaborationCache(storage),localCampaigns=readCampaigns(storage),localAdventures=readAdventures(storage),playerAccount=isPlayerAccount(account,provider),previousCatalog=catalogCharacterIds(cache),previousShared=sharedCharacterIds(cache);
 let campaigns=playerAccount?[]:localCampaigns,adventures=playerAccount?[]:localAdventures,characters=readCharacters(),linkedIds=new Set(),currentShared=new Set();
 if(playerAccount){const activeIds=new Set(memberships.filter(m=>m?.active!==false&&m?.role==='player').map(m=>text(m.campaignId)).filter(Boolean));for(const id of Object.keys(cache.campaigns))if(!activeIds.has(id))delete cache.campaigns[id];cache.playerCharacters={};cache.masterCampaignIds=[]}
 else{characters=characters.filter(character=>!previousCatalog.has(text(character?.id)));const previousMaster=new Set(arr(cache.masterCampaignIds).map(text)),currentMaster=new Set(memberships.filter(m=>m?.active!==false&&m?.role==='dm').map(m=>text(m.campaignId)).filter(Boolean));campaigns=campaigns.filter(row=>!previousMaster.has(text(row?.id))||currentMaster.has(text(row?.id)));adventures=adventures.filter(row=>!previousMaster.has(text(row?.campaignId))||currentMaster.has(text(row?.campaignId)));cache.masterCampaignIds=[...currentMaster]}
 for(const membership of memberships){
  const bundle=await provider.getCampaignBundle(membership.campaignId);if(!bundle?.payload)continue;
  const linked=await provider.listCampaignCharacters(membership.campaignId);for(const character of linked)if(text(character?.id))linkedIds.add(text(character.id));
  if(bundle.mode==='private'){
   const remoteCampaign=bundle.payload.campaign,remoteAdventures=arr(bundle.payload.adventures);campaigns=replaceRemote(campaigns,[remoteCampaign]);adventures=replaceCampaignScope(adventures,membership.campaignId,remoteAdventures);characters=replaceRemote(characters,linked)
  }else{
   const ownId=text(membership.characterId),ownRemote=linked.filter(c=>text(c?.id)===ownId),readOnlyRemote=linked.filter(c=>text(c?.id)!==ownId);cache.campaigns[membership.campaignId]={membership,payload:bundle.payload,characterIds:linked.map(c=>text(c?.id)).filter(Boolean),characters:linked,updatedAt:now()};for(const c of linked)if(text(c?.id))currentShared.add(text(c.id));campaigns=replaceRemote(campaigns,[bundle.payload.campaign]);adventures=replaceCampaignScope(adventures,membership.campaignId,arr(bundle.payload.revealedAdventures));characters=mergeNewest(characters,ownRemote);characters=replaceRemote(characters,readOnlyRemote)
  }
 }
 if(playerAccount){characters=characters.filter(character=>{const id=text(character?.id);if(!previousShared.has(id))return true;if(currentShared.has(id))return true;return ownsCharacter(character,account)})}
 if(!playerAccount&&typeof provider.listPlayerCharacters==='function'){const playerCharacters=await provider.listPlayerCharacters(),catalog={};for(const character of playerCharacters){const id=text(character?.id);if(!id)continue;const linked=linkedIds.has(id);catalog[id]={ownerUid:text(character.ownerUid),ownerUsername:username(character.ownerUsername),ownerDisplayName:text(character.ownerDisplayName)||text(character.ownerUsername),linked,updatedAt:text(character.updatedAt)};characters=linked?replaceRemote(characters,[character]):replaceRemote(characters,[character])}cache.playerCharacters=catalog}
 writeCampaigns(campaigns,storage);writeAdventures(adventures,storage);storage.setItem(CHARACTER_KEY,JSON.stringify(characters));writeCollaborationCache(cache,storage);return{memberships,privateCampaigns:campaigns.length,cache,characters}
}
export async function syncAll(provider,{storage=globalThis.localStorage}={}){const collaboration=await pullCollaborations(provider,{storage}),characters=await syncOwnCharacters(provider,{storage,memberships:collaboration.memberships});for(const membership of collaboration.memberships.filter(m=>m.role==='player'&&m.characterId)){const character=characters.characters.find(c=>c.id===membership.characterId);if(character)await provider.saveCampaignCharacter(membership.campaignId,character)}return{characters,collaboration,at:now()}}
