import{createFirebaseCollaborationProvider,loadFirebaseConfig}from'./firebase-collaboration-provider.js?v=20260905-membership-access1';
import{readCampaigns}from'./campaign-state.js?v=20260902-encounters1';
import{read as readCharacters}from'./character-builder/state.js';
import{syncAll,publishLocalCampaign}from'./collaboration-sync.js?v=20260905-membership-access1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let provider=null,user=null,memberships=[],knownUsers=[],isMaster=false;
function feedback(message,ok=true){const box=$('collab-feedback');box.hidden=false;box.className=`status ${ok?'ok':'warning'}`;box.textContent=message}
function localCampaignOptions(){const campaigns=readCampaigns();return campaigns.length?campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''):'<option value="">Nenhuma Mesa local</option>'}
function roleName(role){return({dm:'Mestre',player:'Jogador',observer:'Observador'}[role]||role)}
function characterRowsForCampaign(){const campaign=readCampaigns().find(c=>c.id===$('membership-campaign')?.value),characters=readCharacters(),preferred=new Set((campaign?.members||[]).map(m=>m.characterId).filter(Boolean));return[...characters].sort((a,b)=>Number(preferred.has(b.id))-Number(preferred.has(a.id))||String(a.name||a.id).localeCompare(String(b.name||b.id),'pt-BR'))}
function fillMembershipCharacters(){const select=$('membership-character');if(!select)return;const role=$('membership-role')?.value||'player';if(role==='dm'){select.innerHTML='<option value="">— Mestre não precisa de personagem —</option>';select.disabled=true;return}select.disabled=false;const rows=characterRowsForCampaign();select.innerHTML='<option value="">— Sem personagem —</option>'+rows.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.id)}</option>`).join('')}
function fillCampaigns(){$('publish-campaign').innerHTML=localCampaignOptions();if($('membership-campaign'))$('membership-campaign').innerHTML=localCampaignOptions();fillMembershipCharacters()}
function renderMasterTools(){const connected=!!user;$('master-publish-tools').hidden=!(connected&&isMaster);$('membership-tools').hidden=!(connected&&isMaster);if(connected&&isMaster)refreshParticipants().catch(e=>feedback(e.message,false))}
async function refreshRemote(){if(!user)return;memberships=await provider.listMemberships();isMaster=user.username===(provider.config.ownerUsername||'rafael')||memberships.some(m=>m.role==='dm');$('membership-list').innerHTML=memberships.length?memberships.map(m=>`<div class="row"><strong>${esc(m.campaignId)}</strong> <span class="badge">${esc(roleName(m.role))}</span><div class="mini">${m.characterId?`Personagem atribuído: ${esc(m.characterId)}`:m.role==='dm'?'Acesso de Mestre.':'Nenhum personagem atribuído ainda.'}</div></div>`).join(''):'<div class="muted">Nenhuma Mesa online atribuída.</div>';renderMasterTools()}
async function refreshParticipants(){if(!user||!isMaster)return;knownUsers=await provider.listUsers();$('known-user-list').innerHTML=knownUsers.length?knownUsers.map(row=>`<div class="row"><strong>${esc(row.username)}</strong></div>`).join(''):'<div class="muted">Nenhum outro usuário entrou no Hub ainda.</div>';$('membership-user').innerHTML=knownUsers.map(row=>`<option value="${esc(row.uid)}">${esc(row.username)}</option>`).join('')||'<option value="">Nenhum usuário disponível</option>'}
function renderAccount(){const connected=!!user;$('account-card').hidden=false;$('login-form').hidden=connected;$('sign-out').hidden=!connected;$('online-tools').hidden=!connected;$('master-publish-tools').hidden=true;$('membership-tools').hidden=true;$('account-state').innerHTML=connected?`<strong>${esc(user.username)}</strong>`:'Não conectado.';if(connected){fillCampaigns();refreshRemote().catch(e=>feedback(e.message,false))}}
async function login(event){event.preventDefault();const username=$('login-username').value.trim(),password=$('login-password').value;try{const result=await provider.signInUsername({username,password});user=result;$('login-password').value='';renderAccount();feedback('Login realizado.')}catch(e){$('login-password').value='';feedback(e.message,false)}}
async function init(){try{const config=await loadFirebaseConfig();if(!config.configured){$('provider-status').className='status warning';$('provider-status').innerHTML='<strong>Firebase ainda não está conectado.</strong><br>O Hub usa site web no GitHub Pages, Firebase Authentication por usuário e senha e Cloud Firestore.';return}provider=await createFirebaseCollaborationProvider({config});$('provider-status').className='status ok';$('provider-status').textContent=`Sincronização web configurada · projeto ${config.projectId} · login por usuário e senha · acesso por Mesa/personagem · Spark / No-cost.`;$('login-form').addEventListener('submit',login);$('sign-out').addEventListener('click',async()=>{await provider.signOut();feedback('Sessão encerrada.')});$('sync-all').addEventListener('click',async()=>{try{$('sync-state').textContent='Sincronizando...';const r=await syncAll(provider);$('sync-state').textContent=`Sincronizado em ${new Date(r.at).toLocaleString('pt-BR')}.`;feedback('Sua ficha e o conteúdo atribuído foram sincronizados.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('publish-campaign-button').addEventListener('click',async()=>{try{if(!isMaster)throw new Error('Somente Mestre pode publicar Mesas.');const id=$('publish-campaign').value;if(!id)throw new Error('Selecione uma Mesa local.');await publishLocalCampaign(provider,id);feedback('Mesa publicada/sincronizada como Mestre.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('membership-campaign').addEventListener('change',fillMembershipCharacters);$('membership-role').addEventListener('change',fillMembershipCharacters);$('membership-form').addEventListener('submit',async event=>{event.preventDefault();try{if(!isMaster)throw new Error('Somente Mestre pode atribuir participantes.');const membership=await provider.upsertMembership({campaignId:$('membership-campaign').value,uid:$('membership-user').value,role:$('membership-role').value,characterId:$('membership-character').value||null});feedback(`${membership.displayName} vinculado à Mesa como ${roleName(membership.role)}${membership.characterId?' com personagem atribuído.':'.'}`);await refreshParticipants();await refreshRemote()}catch(e){feedback(e.message,false)}});provider.onAuthChanged(account=>{user=account;isMaster=false;renderAccount()});renderAccount()}catch(e){$('provider-status').className='status warning';$('provider-status').textContent=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();