import{KEY as CHARACTER_KEY,read as readCharacters}from'./character-builder/state.js';
import{readCampaigns,writeCampaigns}from'./campaign-state.js?v=20260910-realtime1';
import{readAdventures,writeAdventures}from'./adventure-state.js?v=20260910-realtime1';
import{COLLAB_CACHE_KEY}from'./storage-registry.js?v=20260902-collab1';
import{mergeNewest}from'./collaboration-model.js?v=20260914-login-context1';
const arr=v=>Array.isArray(v)?v:[],now=()=>new Date().toISOString(),text=v=>String(v??'').trim();
export function readCollaborationCache(storage=globalThis.localStorage){if(!storage)return{schema:'hub-rpg/collaboration-cache/v1',campaigns:{},updatedAt:null};try{const value=JSON.parse(storage.getItem(COLLAB_CACHE_KEY)||'{}');return{schema:'hub-rpg/collaboration-cache/v1',campaigns:value?.campaigns&&typeof value.campaigns==='object'?value.campaigns:{},updatedAt:value?.updatedAt||null}}catch{return{schema:'hub-rpg/collaboration-cache/v1',campaigns:{},updatedAt:null}}}
export function writeCollaborationCache(cache,storage=globalThis.localStorage){const clean={schema:'hub-rpg/collaboration-cache/v1',campaigns:cache?.campaigns&&typeof cache.campaigns==='object'?cache.campaigns:{},updatedAt:now()};storage?.setItem(COLLAB_CACHE_KEY,JSON.stringify(clean));return clean}
function isPlayerAccount(memberships=[]){return memberships.some(m=>m?.active!==false&&m?.role==='player')&&!memberships.some(m=>m?.active!==false&&m?.role==='dm')}
function sharedCharacterIds(cache){return new Set(Object.values(cache?.campaigns||{}).flatMap(row=>arr(row?.characterIds)).map(text).filter(Boolean))}
export async function syncOwnCharacters(provider,{storage=globalThis.localStorage,memberships=null}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const rows=memberships||await provider.listMemberships(),local=readCharacters(),remote=await provider.listOwnCharacters();if(!isPlayerAccount(rows)){const merged=mergeNewest(local,remote);storage.setItem(CHARACTER_KEY,JSON.stringify(merged));for(const character of merged)await provider.saveOwnCharacter(character);return{characters:merged,ownCharacters:merged,pushed:merged.length,remote:remote.length}}const cache=readCollaborationCache(storage),sharedIds=sharedCharacterIds(cache),ownAssigned=new Set(rows.filter(m=>m?.active!==false&&m?.role==='player').map(m=>text(m.characterId)).filter(Boolean)),localOwn=local.filter(character=>ownAssigned.has(text(character?.id))),mergedOwn=mergeNewest(localOwn,remote),merged=mergeNewest(local,mergedOwn);storage.setItem(CHARACTER_KEY,JSON.stringify(merged));for(const character of mergedOwn)await provider.saveOwnCharacter(character);return{characters:merged,ownCharacters:mergedOwn,pushed:mergedOwn.length,remote:remote.length,shared:sharedIds.size}}
export async function publishLocalCampaign(provider,campaignId,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const campaign=readCampaigns(storage).find(c=>c.id===campaignId);if(!campaign)throw new Error('Campanha local não encontrada.');const adventures=readAdventures(storage).filter(a=>a.campaignId===campaignId),characters=readCharacters();return provider.saveCampaignBundle(campaign,adventures,characters)}
export async function pullCollaborations(provider,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const memberships=await provider.listMemberships(),cache=readCollaborationCache(storage),localCampaigns=readCampaigns(storage),localAdventures=readAdventures(storage),playerAccount=isPlayerAccount(memberships);let campaigns=localCampaigns,adventures=localAdventures,characters=readCharacters();if(playerAccount){const activeIds=new Set(memberships.filter(m=>m?.active!==false&&m?.role==='player').map(m=>text(m.campaignId)).filter(Boolean));for(const id of Object.keys(cache.campaigns))if(!activeIds.has(id))delete cache.campaigns[id]}for(const membership of memberships){const bundle=await provider.getCampaignBundle(membership.campaignId);if(!bundle?.payload)continue;if(bundle.mode==='private'){const remoteCampaign=bundle.payload.campaign,remoteAdventures=arr(bundle.payload.adventures),linked=await provider.listCampaignCharacters(membership.campaignId);campaigns=mergeNewest(campaigns,[remoteCampaign]);adventures=mergeNewest(adventures,remoteAdventures);characters=mergeNewest(characters,linked)}else{const linked=await provider.listCampaignCharacters(membership.campaignId);cache.campaigns[membership.campaignId]={membership,payload:bundle.payload,characterIds:linked.map(c=>text(c?.id)).filter(Boolean),updatedAt:now()};characters=mergeNewest(characters,linked)}}writeCampaigns(campaigns,storage);writeAdventures(adventures,storage);storage.setItem(CHARACTER_KEY,JSON.stringify(characters));writeCollaborationCache(cache,storage);return{memberships,privateCampaigns:campaigns.length,cache,characters}}
export async function syncAll(provider,{storage=globalThis.localStorage}={}){const collaboration=await pullCollaborations(provider,{storage}),characters=await syncOwnCharacters(provider,{storage,memberships:collaboration.memberships});for(const membership of collaboration.memberships.filter(m=>m.role==='player'&&m.characterId)){const character=characters.characters.find(c=>c.id===membership.characterId);if(character)await provider.saveCampaignCharacter(membership.campaignId,character)}return{characters,collaboration,at:now()}}
