export const COLLAB_ROLES=Object.freeze(['dm','player']);
export const COLLAB_PERMISSIONS=Object.freeze({
 'campaign:read-shared':['dm','player'],
 'campaign:write':['dm'],
 'session:write':['dm'],
 'encounter:write':['dm'],
 'adventure:write':['dm'],
 'member:manage':['dm'],
 'member:read-context':['dm','player'],
 'character:read-linked':['dm','player'],
 'character:read-campaign':['dm','player'],
 'character:write-own':['player'],
 'handout:read':['dm','player']
});
const arr=v=>Array.isArray(v)?v:[];
const text=v=>String(v??'').trim();
const role=v=>COLLAB_ROLES.includes(v)?v:'player';
const unique=rows=>[...new Set(arr(rows).map(text).filter(Boolean))];
export function normalizeUsername(value=''){return text(value).toLowerCase()}
export function usernameFromTechnicalEmail(email='',domain='teias.invalid'){const raw=text(email).toLowerCase(),suffix=`@${String(domain||'teias.invalid').toLowerCase()}`;return raw.endsWith(suffix)?normalizeUsername(raw.slice(0,-suffix.length)):normalizeUsername(raw.split('@')[0])}
export function normalizeAccount(user={},options={}){const username=normalizeUsername(options.username)||usernameFromTechnicalEmail(user.email,options.domain||'teias.invalid');return{uid:text(user.uid),username,displayName:username||'Usuário'}}
export function normalizeMembership(row={}){const username=normalizeUsername(row.username||row.displayName);return{id:text(row.id),campaignId:text(row.campaignId),uid:text(row.uid),username,email:text(row.email).toLowerCase(),role:role(row.role),characterId:text(row.characterId)||null,sessionIds:unique(row.sessionIds),adventureIds:unique(row.adventureIds),displayName:text(row.displayName)||username,active:row.active!==false,updatedAt:text(row.updatedAt)}}
function mediaRef(row){if(!row||typeof row!=='object'||!text(row.id))return null;return{id:text(row.id),campaignId:text(row.campaignId)||null,entityType:text(row.entityType),entityId:text(row.entityId),mime:text(row.mime)||'image/webp',width:Number(row.width)||0,height:Number(row.height)||0,size:Number(row.size)||0}}
export function participantSharedProjection(row={}){const m=normalizeMembership(row);return{username:m.username,displayName:m.displayName,role:m.role,characterId:m.characterId,sessionIds:m.sessionIds,adventureIds:m.adventureIds,active:m.active}}
export function canCollaborate({ownerId='',uid='',membership=null},permission){if(text(ownerId)&&text(ownerId)===text(uid))return true;const m=membership?normalizeMembership(membership):null;if(!m?.active||(m.uid&&m.uid!==text(uid)))return false;return arr(COLLAB_PERMISSIONS[permission]).includes(m.role)}
export function sessionSharedProjection(session={}){return{id:text(session.id),number:Number(session.number)||1,title:String(session.title??''),date:String(session.date??''),status:String(session.status??'planned'),adventureId:text(session.adventureId)||null,location:String(session.location??''),objective:String(session.objective??''),summary:String(session.summary??''),sharedNotes:String(session.sharedNotes??''),finalSummary:String(session.finalSummary??''),coverImage:mediaRef(session.coverImage),coverImageUrl:String(session.coverImageUrl??''),participantUsernames:unique(session.participantUsernames).map(normalizeUsername),participantCharacterIds:unique(session.participantCharacterIds),scenes:arr(session.scenes).map(scene=>({id:text(scene.id),title:String(scene.title??''),status:String(scene.status??'planned'),order:Number(scene.order)||1,adventureSceneId:text(scene.adventureSceneId)||null}))}}
export function campaignSharedProjection(campaign={}){return{id:text(campaign.id),name:String(campaign.name??''),status:String(campaign.status??'active'),system:String(campaign.system??''),setting:String(campaign.setting??''),description:String(campaign.description??''),coverImage:mediaRef(campaign.coverImage),coverImageUrl:String(campaign.coverImageUrl??''),historySummary:String(campaign.historySummary??''),importantNpcs:String(campaign.importantNpcs??''),importantLocations:String(campaign.importantLocations??''),activeMissions:String(campaign.activeMissions??''),campaignMaterials:String(campaign.campaignMaterials??''),timeline:String(campaign.timeline??''),dmName:String(campaign.dmName??''),schedule:String(campaign.schedule??''),currentArc:String(campaign.currentArc??''),currentLocation:String(campaign.currentLocation??''),partyGoal:String(campaign.partyGoal??''),sharedNotes:String(campaign.sharedNotes??''),partyTreasure:String(campaign.partyTreasure??''),members:arr(campaign.members).map(m=>({id:text(m.id),username:normalizeUsername(m.username),name:String(m.name??''),role:m.role==='dm'?'dm':'player',characterId:text(m.characterId)||null,active:m.active!==false})),sessions:arr(campaign.sessions).map(sessionSharedProjection),activeSessionId:text(campaign.activeSessionId)||null,updatedAt:text(campaign.updatedAt)}}
export function campaignSharedCoreProjection(campaign={}){return{...campaignSharedProjection(campaign),sessions:[],activeSessionId:null}}
export function revealedAdventureProjection(adventure={},campaign={}){
 const revealedMaterialIds=new Set(arr(adventure.handouts).filter(h=>h.revealed===true).map(h=>h.id)),visibleClueIds=new Set(arr(adventure.clues).filter(c=>['discovered','resolved'].includes(c.status)).map(c=>c.id)),visibleMissions=arr(adventure.missions).filter(m=>m.status!=='hidden'),npcIds=new Set(unique(adventure.npcIds)),locationIds=new Set(unique(adventure.locationIds)),sessionIds=unique([...arr(campaign.sessions).filter(s=>text(s.adventureId)===text(adventure.id)).map(s=>s.id),...arr(adventure.scenes).map(s=>s.sessionId)]);
 return{id:text(adventure.id),campaignId:text(adventure.campaignId),title:String(adventure.title??''),coverImage:mediaRef(adventure.coverImage),coverImageUrl:String(adventure.coverImageUrl??''),description:String(adventure.description??''),status:String(adventure.status??'planned'),type:String(adventure.type??'main'),arc:String(adventure.arc??''),summary:String(adventure.summary??''),currentSituation:String(adventure.currentSituation??''),nextStep:String(adventure.nextStep??''),participantUsernames:unique(adventure.participantUsernames).map(normalizeUsername),characterIds:unique(adventure.characterIds),sessionIds,missions:visibleMissions.map(m=>({id:text(m.id),title:String(m.title??''),kind:String(m.kind??'side'),status:String(m.status??'active'),description:String(m.description??''),reward:String(m.reward??''),consequence:String(m.consequence??'')})),materials:arr(adventure.handouts).filter(h=>revealedMaterialIds.has(h.id)).map(h=>({id:h.id,title:String(h.title??''),type:String(h.type??'text'),content:String(h.content??''),url:String(h.url??'')})),handouts:arr(adventure.handouts).filter(h=>revealedMaterialIds.has(h.id)).map(h=>({id:h.id,title:String(h.title??''),type:String(h.type??'text'),content:String(h.content??''),url:String(h.url??'')})),clues:arr(adventure.clues).filter(c=>visibleClueIds.has(c.id)).map(c=>({id:c.id,title:String(c.title??''),text:String(c.text??''),status:c.status})),npcs:arr(campaign.npcs).filter(n=>npcIds.has(text(n.id))).map(n=>({id:text(n.id),name:String(n.name??''),role:String(n.role??''),faction:String(n.faction??''),relationship:String(n.relationship??''),status:String(n.status??''),portraitUrl:String(n.portraitUrl??''),description:String(n.description??'')})),locations:arr(campaign.locations).filter(l=>locationIds.has(text(l.id))).map(l=>({id:text(l.id),name:String(l.name??''),type:String(l.type??''),imageUrl:String(l.imageUrl??''),description:String(l.description??''),state:String(l.state??'')}))}
}
export function adventureParticipantCharacterIds(adventure={},campaign={}){const sessions=new Map(arr(campaign.sessions).map(s=>[text(s.id),s])),ids=[...arr(adventure.characterIds)];for(const session of arr(campaign.sessions).filter(s=>text(s.adventureId)===text(adventure.id)))ids.push(...arr(session.participantCharacterIds));for(const scene of arr(adventure.scenes)){const session=sessions.get(text(scene.sessionId));if(session)ids.push(...arr(session.participantCharacterIds))}return unique(ids)}
export function adventureSharedRecord(adventure={},campaign={}){return{payload:revealedAdventureProjection(adventure,campaign),participantCharacterIds:adventureParticipantCharacterIds(adventure,campaign)}}
export function collaborationSharedBundle(campaign={},adventures=[]){return{campaign:campaignSharedProjection(campaign),revealedAdventures:arr(adventures).filter(a=>a.campaignId===campaign.id).map(a=>revealedAdventureProjection(a,campaign))}}
export function collaborationMemberBundle(corePayload={},sessions=[],adventures=[],participants=[]){const campaign={...(corePayload?.campaign||{}),sessions:arr(sessions).map(s=>s?.payload||s).filter(Boolean)};const activeSessionId=campaign.activeSessionId&&campaign.sessions.some(s=>s.id===campaign.activeSessionId)?campaign.activeSessionId:null;return{campaign:{...campaign,activeSessionId},revealedAdventures:arr(adventures).map(a=>a?.payload||a).filter(Boolean),participants:arr(participants).map(participantSharedProjection).filter(p=>p.active)}}
export function mergeNewest(localRows=[],remoteRows=[]){const map=new Map(arr(localRows).filter(x=>x?.id).map(row=>[row.id,row]));for(const row of arr(remoteRows).filter(x=>x?.id)){const old=map.get(row.id),oldAt=Date.parse(old?.updatedAt||old?.createdAt||'')||0,newAt=Date.parse(row?.updatedAt||row?.createdAt||'')||0;if(!old||newAt>=oldAt)map.set(row.id,row)}return[...map.values()]}
