import{createFirebaseCollaborationProvider,loadFirebaseConfig}from'./firebase-collaboration-provider.js?v=20260909-player-access2';
import{readCampaigns}from'./campaign-state.js?v=20260902-encounters1';
import{readAdventures}from'./adventure-state.js?v=20260902-adventures1';
import{read as readCharacters}from'./character-builder/state.js';
import{syncAll,publishLocalCampaign}from'./collaboration-sync.js?v=20260905-membership-access1';
import{writeCollaborationSession,clearCollaborationSession}from'./collaboration-view.js?v=20260909-player-access2';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),username=v=>String(v??'').trim().toLowerCase();
let provider=null,user=null,memberships=[],knownUsers=[],managedMemberships=[],isMaster=false;
function feedback(message,ok=true){const box=$('collab-feedback');box.hidden=false;box.className=`status ${ok?'ok':'warning'}`;box.textContent=message}
function localCampaignOptions(){const campaigns=readCampaigns();return campaigns.length?campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(''):'<option value="">Nenhuma Mesa local</option>'}
function roleName(role){return role==='dm'?'Mestre':'Jogador'}
function selectedValues(id){const select=$(id);return select?[...select.selectedOptions].map(o=>o.value).filter(Boolean):[]}
function applySelected(id,values=[]){const wanted=new Set(values);const select=$(id);if(select)for(const option of select.options)option.selected=wanted.has(option.value)}
function currentCampaign(){return readCampaigns().find(c=>c.id===$('membership-campaign')?.value)||null}
function characterRowsForCampaign(){const campaign=currentCampaign(),characters=readCharacters(),preferred=new Set((campaign?.members||[]).map(m=>m.characterId).filter(Boolean));return[...characters].sort((a,b)=>Number(preferred.has(b.id))-Number(preferred.has(a.id))||String(a.name||a.id).localeCompare(String(b.name||b.id),'pt-BR'))}
function fillCampaignAccessOptions(){const campaign=currentCampaign(),cid=campaign?.id||'';const character=$('membership-character'),sessions=$('membership-sessions'),adventures=$('membership-adventures');if(character)character.innerHTML='<option value="">— Sem personagem —</option>'+characterRowsForCampaign().map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.id)}</option>`).join('');if(sessions)sessions.innerHTML=(campaign?.sessions||[]).map(s=>`<option value="${esc(s.id)}">${esc(`Sessão ${s.number} · ${s.title}`)}</option>`).join('')||'<option value="" disabled>Nenhuma Sessão nesta Campanha</option>';if(adventures)adventures.innerHTML=readAdventures().filter(a=>a.campaignId===cid).map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('')||'<option value="" disabled>Nenhuma Aventura nesta Campanha</option>'}
async function hydrateCurrentAccess(){if(!user||!isMaster)return;const cid=$('membership-campaign')?.value||'',player=username($('membership-user')?.value);fillCampaignAccessOptions();if(!cid){managedMemberships=[];return}try{managedMemberships=await provider.listCampaignMemberships(cid)}catch{managedMemberships=[]}const current=managedMemberships.find(m=>m.username===player&&m.role==='player'&&m.active!==false)||null;if($('membership-character'))$('membership-character').value=current?.characterId||'';applySelected('membership-sessions',current?.sessionIds||[]);applySelected('membership-adventures',current?.adventureIds||[])}
function fillCampaigns(){$('publish-campaign').innerHTML=localCampaignOptions();if($('membership-campaign'))$('membership-campaign').innerHTML=localCampaignOptions();fillCampaignAccessOptions()}
function renderMasterTools(){const connected=!!user;$('master-publish-tools').hidden=!(connected&&isMaster);$('membership-tools').hidden=!(connected&&isMaster);if(connected&&isMaster)refreshParticipants().catch(e=>feedback(e.message,false))}
function persistSession(){if(!user)return clearCollaborationSession();writeCollaborationSession({uid:user.uid,username:user.username,isMaster,memberships})}
async function refreshRemote(){if(!user)return;memberships=await provider.listMemberships();isMaster=user.username===(provider.config.ownerUsername||'rafael');persistSession();$('membership-list').innerHTML=memberships.length?memberships.map(m=>`<div class="row"><strong>${esc(m.campaignId)}</strong> <span class="badge">${esc(roleName(m.role))}</span><div class="mini">${m.role==='dm'?'Mestre':`${m.characterId?`Personagem: ${esc(m.characterId)} · `:''}Sessões: ${(m.sessionIds||[]).length} · Aventuras: ${(m.adventureIds||[]).length}`}</div></div>`).join(''):'<div class="muted">Nenhuma Mesa atribuída.</div>';renderMasterTools()}
async function refreshParticipants(){if(!user||!isMaster)return;const owner=provider.config.ownerUsername||'rafael',configured=(provider.config.playerUsernames||[]).map(username);knownUsers=(await provider.listUsers()).filter(row=>row.username!==owner);const names=[...new Set([...configured,...knownUsers.map(row=>row.username),...managedMemberships.filter(m=>m.role==='player').map(m=>m.username)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('known-user-list').innerHTML=names.length?names.map(name=>`<div class="row"><strong>${esc(name)}</strong></div>`).join(''):'<div class="muted">Nenhum jogador cadastrado.</div>';$('known-user-options').innerHTML=names.map(name=>`<option value="${esc(name)}"></option>`).join('');await hydrateCurrentAccess()}
function renderAccount(){const connected=!!user;$('account-card').hidden=false;$('login-form').hidden=connected;$('sign-out').hidden=!connected;$('online-tools').hidden=!connected;$('master-publish-tools').hidden=true;$('membership-tools').hidden=true;$('account-state').innerHTML=connected?`<strong>${esc(user.username)}</strong>`:'Não conectado.';if(connected){isMaster=user.username===(provider?.config?.ownerUsername||'rafael');persistSession();fillCampaigns();refreshRemote().catch(e=>feedback(e.message,false))}else clearCollaborationSession()}
async function login(event){event.preventDefault();const value=$('login-username').value.trim(),password=$('login-password').value;try{const result=await provider.signInUsername({username:value,password});user=result;$('login-password').value='';renderAccount();feedback('Login realizado.')}catch(e){$('login-password').value='';feedback(e.message,false)}}
async function init(){try{const config=await loadFirebaseConfig();if(!config.configured){$('provider-status').className='status warning';$('provider-status').textContent='Acesso online indisponível.';return}provider=await createFirebaseCollaborationProvider({config});$('provider-status').className='status ok';$('provider-status').textContent='Acesso online disponível.';$('login-form').addEventListener('submit',login);$('sign-out').addEventListener('click',async()=>{await provider.signOut();clearCollaborationSession();feedback('Sessão encerrada.')});$('sync-all').addEventListener('click',async()=>{try{$('sync-state').textContent='Sincronizando...';const r=await syncAll(provider);$('sync-state').textContent=`Sincronizado em ${new Date(r.at).toLocaleString('pt-BR')}.`;feedback('Dados sincronizados.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('publish-campaign-button').addEventListener('click',async()=>{try{if(!isMaster)throw new Error('Somente Mestre pode publicar Mesas.');const id=$('publish-campaign').value;if(!id)throw new Error('Selecione uma Mesa.');await publishLocalCampaign(provider,id);feedback('Mesa sincronizada.');await refreshRemote()}catch(e){feedback(e.message,false)}});$('membership-campaign').addEventListener('change',()=>hydrateCurrentAccess().catch(e=>feedback(e.message,false)));$('membership-user').addEventListener('change',()=>hydrateCurrentAccess().catch(e=>feedback(e.message,false)));$('membership-form').addEventListener('submit',async event=>{event.preventDefault();try{if(!isMaster)throw new Error('Somente Mestre pode atribuir acessos.');const campaignId=$('membership-campaign').value,player=username($('membership-user').value);if(!campaignId||!player)throw new Error('Informe um jogador e selecione uma Campanha.');await publishLocalCampaign(provider,campaignId);const membership=await provider.upsertMembership({campaignId,username:player,characterId:$('membership-character').value||null,sessionIds:selectedValues('membership-sessions'),adventureIds:selectedValues('membership-adventures')});feedback(`${membership.displayName}: acessos salvos.`);managedMemberships=await provider.listCampaignMemberships(campaignId);await refreshParticipants();await refreshRemote()}catch(e){feedback(e.message,false)}});provider.onAuthChanged(account=>{user=account;isMaster=false;renderAccount()});renderAccount()}catch(e){$('provider-status').className='status warning';$('provider-status').textContent=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();