import{KEY as CHARACTER_KEY,read as readCharacters}from'./character-builder/state.js';
import{readCampaigns,writeCampaigns}from'./campaign-state.js?v=20260902-encounters1';
import{readAdventures,writeAdventures}from'./adventure-state.js?v=20260902-adventures1';
import{COLLAB_CACHE_KEY}from'./storage-registry.js?v=20260902-collab1';
import{mergeNewest}from'./collaboration-model.js?v=20260902-collab1';
const arr=v=>Array.isArray(v)?v:[],now=()=>new Date().toISOString();
export function readCollaborationCache(storage=globalThis.localStorage){if(!storage)return{schema:'hub-rpg/collaboration-cache/v1',campaigns:{},updatedAt:null};try{const value=JSON.parse(storage.getItem(COLLAB_CACHE_KEY)||'{}');return{schema:'hub-rpg/collaboration-cache/v1',campaigns:value?.campaigns&&typeof value.campaigns==='object'?value.campaigns:{},updatedAt:value?.updatedAt||null}}catch{return{schema:'hub-rpg/collaboration-cache/v1',campaigns:{},updatedAt:null}}}
export function writeCollaborationCache(cache,storage=globalThis.localStorage){const clean={schema:'hub-rpg/collaboration-cache/v1',campaigns:cache?.campaigns&&typeof cache.campaigns==='object'?cache.campaigns:{},updatedAt:now()};storage?.setItem(COLLAB_CACHE_KEY,JSON.stringify(clean));return clean}
export async function syncOwnCharacters(provider,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const local=readCharacters(),remote=await provider.listOwnCharacters(),merged=mergeNewest(local,remote);storage.setItem(CHARACTER_KEY,JSON.stringify(merged));for(const character of merged)await provider.saveOwnCharacter(character);return{characters:merged,pushed:merged.length,remote:remote.length}}
export async function publishLocalCampaign(provider,campaignId,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const campaign=readCampaigns(storage).find(c=>c.id===campaignId);if(!campaign)throw new Error('Campanha local não encontrada.');const adventures=readAdventures(storage).filter(a=>a.campaignId===campaignId);return provider.saveCampaignBundle(campaign,adventures)}
export async function pullCollaborations(provider,{storage=globalThis.localStorage}={}){if(!provider?.configured)throw new Error('Sincronização remota não configurada.');const memberships=await provider.listMemberships(),cache=readCollaborationCache(storage),localCampaigns=readCampaigns(storage),localAdventures=readAdventures(storage);let campaigns=localCampaigns,adventures=localAdventures;for(const membership of memberships){const bundle=await provider.getCampaignBundle(membership.campaignId);if(!bundle?.payload)continue;if(bundle.mode==='private'){const remoteCampaign=bundle.payload.campaign,remoteAdventures=arr(bundle.payload.adventures);campaigns=mergeNewest(campaigns,[remoteCampaign]);adventures=mergeNewest(adventures,remoteAdventures)}else cache.campaigns[membership.campaignId]={membership,payload:bundle.payload,updatedAt:now()}}writeCampaigns(campaigns,storage);writeAdventures(adventures,storage);writeCollaborationCache(cache,storage);return{memberships,privateCampaigns:campaigns.length,cache}}
export async function syncAll(provider,{storage=globalThis.localStorage}={}){const characters=await syncOwnCharacters(provider,{storage}),collaboration=await pullCollaborations(provider,{storage});return{characters,collaboration,at:now()}}
export async function publishMembershipCharacter(provider,campaignId,characterId){const character=readCharacters().find(c=>c.id===characterId);if(!character)throw new Error('Personagem local não encontrado.');await provider.linkMembershipCharacter(campaignId,characterId);await provider.saveCampaignCharacter(campaignId,character);return character}
