import{read as readCharacters}from'./character-builder/state.js';
import{readCampaigns}from'./campaign-state.js?v=20260901-campaign1';
import{readAdventures}from'./adventure-state.js?v=20260902-adventures1';
import{characterSummary,summarizeDashboard}from'./dashboard-state.js?v=20260904-dashboard1';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusName=s=>({active:'Ativa',paused:'Pausada',finished:'Encerrada'}[s]||s);
const sessionStatus=s=>({planned:'Planejada',active:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}[s]||s);
const fmtDate=v=>{if(!v)return'Sem data';const d=String(v).slice(0,10),m=d.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v)};
const fmtTime=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})};
function metric(id,value,label){$(id).innerHTML=`<strong>${esc(value)}</strong><span>${esc(label)}</span>`}
function renderFocus(summary){const play=$('character-in-play'),next=$('next-session');if(summary.characterInPlay){const {character,campaign,session}=summary.characterInPlay,s=characterSummary(character);play.innerHTML=`<div><span class="badge">Em jogo</span><h2>${esc(s.name)}</h2><p>${esc([s.className&&`${s.className} ${s.level}`,s.speciesName].filter(Boolean).join(' · ')||`Nível ${s.level}`)}</p><p class="mini">${esc(campaign.name)} · ${esc(session.title)}</p></div><a class="btn" href="ficha-personagem.html?id=${encodeURIComponent(s.id)}">Abrir Ficha</a>`}else play.innerHTML='<div><h2>Nenhum personagem em jogo agora</h2><p class="muted">Inicie uma sessão em uma Mesa e vincule um personagem para destacá-lo aqui.</p></div><a class="btn secondary" href="personagens.html">Personagens</a>';
 if(summary.nextSession){const {campaign,session}=summary.nextSession;next.innerHTML=`<div><span class="badge">Próxima sessão</span><h2>${esc(session.title)}</h2><p>${esc(campaign.name)}</p><p class="mini">${esc(fmtDate(session.date))} · ${esc(sessionStatus(session.status))}${session.location?` · ${esc(session.location)}`:''}</p></div><a class="btn" href="mesa.html?id=${encodeURIComponent(campaign.id)}">Abrir Mesa</a>`}else next.innerHTML='<div><h2>Nenhuma próxima sessão</h2><p class="muted">Planeje uma sessão em uma Mesa ativa para ela aparecer aqui.</p></div><a class="btn secondary" href="campanhas.html">Mesas</a>'}
function renderCampaigns(rows){$('campaign-dashboard-list').innerHTML=rows.length?rows.map(c=>{const active=c.sessions?.find(s=>s.id===c.activeSessionId),planned=(c.sessions||[]).filter(s=>s.status==='planned').length;return`<a class="dash-row" href="mesa.html?id=${encodeURIComponent(c.id)}"><div><strong>${esc(c.name)}</strong><div class="mini">${esc(c.setting||c.system||'Mesa')} · ${(c.members||[]).length} participante(s)</div></div><div class="row-meta"><span class="badge">${esc(statusName(c.status))}</span>${active?'<span class="badge live">Em jogo</span>':planned?`<span class="mini">${planned} planejada(s)</span>`:''}</div></a>`}).join(''):'<div class="empty">Nenhuma Mesa criada ainda.</div>'}
function renderPending(rows){$('pending-list').innerHTML=rows.length?rows.map(x=>`<a class="dash-row" href="${esc(x.href)}"><div><strong>${esc(x.title)}</strong><div class="mini">${esc(x.detail)}</div></div><span aria-hidden="true">→</span></a>`).join(''):'<div class="empty ok">Nenhuma pendência detectada.</div>'}
function renderActivity(rows){$('activity-list').innerHTML=rows.length?rows.map(x=>`<a class="dash-row" href="${esc(x.href)}"><div><strong>${esc(x.title)}</strong><div class="mini">${esc(x.detail)}</div></div><time class="mini">${esc(fmtTime(x.at))}</time></a>`).join(''):'<div class="empty">Ainda não há atividade registrada.</div>'}
function init(){const summary=summarizeDashboard({characters:readCharacters(),campaigns:readCampaigns(),adventures:readAdventures(),now:new Date()});metric('metric-characters',summary.metrics.characters,'Personagens');metric('metric-campaigns',summary.metrics.activeCampaigns,'Mesas ativas');metric('metric-sessions',summary.metrics.upcomingSessions,'Sessões planejadas');metric('metric-pending',summary.metrics.pending,'Pendências');renderFocus(summary);renderCampaigns(summary.campaigns);renderPending(summary.pending);renderActivity(summary.activity);$('dashboard-status').textContent=`Painel atualizado em ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}.`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
