import{applyDamageDefenses}from'./character-sheet-resolution-rules.js?v=20260902-resolution1';

export const ENCOUNTER_SCHEMA='hub-rpg/encounter/v1';
export const ENCOUNTER_STATUS=Object.freeze(['planned','active','completed','cancelled']);
export const COMBATANT_KINDS=Object.freeze(['character','monster','npc']);
const STATUS=new Set(ENCOUNTER_STATUS),KINDS=new Set(COMBATANT_KINDS);
const arr=v=>Array.isArray(v)?v:[];
const text=v=>String(v??'').trim();
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const now=()=>new Date().toISOString();
const uniq=v=>[...new Set(arr(v).map(text).filter(Boolean))];
const uid=prefix=>globalThis.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const clampHp=(value,max)=>Math.max(0,Math.min(Math.max(0,Math.floor(num(max))),Math.floor(num(value))));
const saves=value=>{const source=value&&typeof value==='object'&&!Array.isArray(value)?value:{};return Object.fromEntries(Object.entries(source).filter(([,v])=>Number.isFinite(Number(v))).map(([k,v])=>[text(k),Number(v)]))};

export function sanitizeCombatant(row={}){
 const kind=KINDS.has(row.kind)?row.kind:'npc',base={id:text(row.id)||uid('combatant'),kind,name:text(row.name)||(kind==='character'?'Personagem':kind==='monster'?'Monstro':'NPC'),initiative:Number.isFinite(Number(row.initiative))?Number(row.initiative):null,initiativeModifier:Number.isFinite(Number(row.initiativeModifier))?Number(row.initiativeModifier):0,notes:String(row.notes??'')};
 if(kind==='character')return{...base,characterId:text(row.characterId)||null};
 const maxHp=Math.max(1,Math.floor(num(row.maxHp)||1));
 return{...base,monsterId:kind==='monster'?text(row.monsterId)||null:null,source:text(row.source),ruleset:text(row.ruleset),ac:Math.max(0,Math.floor(num(row.ac))),maxHp,currentHp:row.currentHp==null?maxHp:clampHp(row.currentHp,maxHp),tempHp:Math.max(0,Math.floor(num(row.tempHp))),conditions:uniq(row.conditions),resistances:uniq(row.resistances),immunities:uniq(row.immunities),vulnerabilities:uniq(row.vulnerabilities),conditionImmunities:uniq(row.conditionImmunities),saveModifiers:saves(row.saveModifiers),cr:text(row.cr),xp:Math.max(0,Math.floor(num(row.xp))),defeated:row.defeated===true||clampHp(row.currentHp==null?maxHp:row.currentHp,maxHp)===0}
}
export function sanitizeEncounter(row={},index=0){
 const combatants=arr(row.combatants).map(sanitizeCombatant),ids=new Set(combatants.map(c=>c.id)),status=STATUS.has(row.status)?row.status:'planned';let activeCombatantId=text(row.activeCombatantId)||null;if(!ids.has(activeCombatantId))activeCombatantId=null;
 const rewards=row.rewards&&typeof row.rewards==='object'&&!Array.isArray(row.rewards)?row.rewards:{};
 return{schema:ENCOUNTER_SCHEMA,id:text(row.id)||uid('encounter'),title:text(row.title)||`Encontro ${index+1}`,status,round:Math.max(1,Math.floor(num(row.round)||1)),activeCombatantId,combatants,rewards:{xp:Math.max(0,Math.floor(num(rewards.xp))),coinsCp:Math.max(0,Math.floor(num(rewards.coinsCp))),items:String(rewards.items??''),notes:String(rewards.notes??'')},summary:String(row.summary??''),createdAt:text(row.createdAt)||now(),updatedAt:text(row.updatedAt)||now()}
}
export function sanitizeEncounterList(rows=[]){return arr(rows).map(sanitizeEncounter)}
export function sanitizeEncounterSessionFields(row={}){const encounters=sanitizeEncounterList(row.encounters);let activeEncounterId=text(row.activeEncounterId)||null;const active=encounters.filter(e=>e.status==='active');if(activeEncounterId&&!encounters.some(e=>e.id===activeEncounterId&&e.status==='active'))activeEncounterId=null;if(!activeEncounterId&&active.length)activeEncounterId=active[0].id;for(const encounter of encounters)if(encounter.status==='active'&&encounter.id!==activeEncounterId)encounter.status='planned';return{encounters,activeEncounterId}}

function result(session,encounter){return{ok:true,session,encounter}}
export function createEncounter(session,data={}){if(!session)return{ok:false,reason:'Sessão indisponível.'};const fields=sanitizeEncounterSessionFields(session),encounter=sanitizeEncounter({...data,id:data.id||uid('encounter'),createdAt:now(),updatedAt:now()},fields.encounters.length);session.encounters=[...fields.encounters,encounter];session.activeEncounterId=fields.activeEncounterId;return result(session,encounter)}
export function encounterById(session,encounterId){return sanitizeEncounterList(session?.encounters).find(e=>e.id===text(encounterId))||null}
export function updateEncounter(session,encounterId,patch={}){if(!session)return{ok:false,reason:'Sessão indisponível.'};const fields=sanitizeEncounterSessionFields(session),index=fields.encounters.findIndex(e=>e.id===text(encounterId));if(index<0)return{ok:false,reason:'Encontro não encontrado.'};const old=fields.encounters[index],encounter=sanitizeEncounter({...old,...patch,id:old.id,createdAt:old.createdAt,updatedAt:now()},index);fields.encounters[index]=encounter;if(fields.activeEncounterId===encounter.id&&encounter.status!=='active')fields.activeEncounterId=null;session.encounters=fields.encounters;session.activeEncounterId=fields.activeEncounterId;return result(session,encounter)}
export function removeEncounter(session,encounterId){if(!session)return{ok:false,reason:'Sessão indisponível.'};const fields=sanitizeEncounterSessionFields(session),id=text(encounterId),before=fields.encounters.length;fields.encounters=fields.encounters.filter(e=>e.id!==id);if(fields.encounters.length===before)return{ok:false,reason:'Encontro não encontrado.'};if(fields.activeEncounterId===id)fields.activeEncounterId=null;session.encounters=fields.encounters;session.activeEncounterId=fields.activeEncounterId;return{ok:true,session}}
export function startEncounter(session,encounterId){if(!session)return{ok:false,reason:'Sessão indisponível.'};const fields=sanitizeEncounterSessionFields(session),encounter=fields.encounters.find(e=>e.id===text(encounterId));if(!encounter)return{ok:false,reason:'Encontro não encontrado.'};const other=fields.encounters.find(e=>e.status==='active'&&e.id!==encounter.id);if(other)return{ok:false,reason:`Finalize o encontro ativo (${other.title}) antes de iniciar outro.`};if(!encounter.combatants.length)return{ok:false,reason:'Adicione ao menos um combatente antes de iniciar.'};encounter.status='active';encounter.round=1;encounter.updatedAt=now();sortInitiative(encounter);encounter.activeCombatantId=encounter.combatants[0]?.id||null;session.encounters=fields.encounters;session.activeEncounterId=encounter.id;return result(session,encounter)}
export function finishEncounter(session,encounterId,patch={}){const found=encounterById(session,encounterId);if(!found)return{ok:false,reason:'Encontro não encontrado.'};const result=updateEncounter(session,encounterId,{...patch,status:'completed',activeCombatantId:null});if(result.ok)session.activeEncounterId=null;return result}
export function cancelEncounter(session,encounterId){const result=updateEncounter(session,encounterId,{status:'cancelled',activeCombatantId:null});if(result.ok&&session.activeEncounterId===encounterId)session.activeEncounterId=null;return result}

export function addCharacterCombatant(encounter,{characterId,name,initiative=null,initiativeModifier=0}={}){if(!encounter)return{ok:false,reason:'Encontro indisponível.'};const id=text(characterId);if(!id)return{ok:false,reason:'Personagem inválido.'};if(encounter.combatants.some(c=>c.kind==='character'&&c.characterId===id))return{ok:false,reason:'Personagem já está no encontro.'};const combatant=sanitizeCombatant({kind:'character',characterId:id,name,initiative,initiativeModifier});encounter.combatants.push(combatant);encounter.updatedAt=now();return{ok:true,encounter,combatant}}
export function addCreatureCombatant(encounter,data={}){if(!encounter)return{ok:false,reason:'Encontro indisponível.'};const kind=data.kind==='monster'?'monster':'npc',combatant=sanitizeCombatant({...data,kind,id:data.id||uid(kind)});encounter.combatants.push(combatant);encounter.updatedAt=now();return{ok:true,encounter,combatant}}
export function updateCombatant(encounter,combatantId,patch={}){if(!encounter)return{ok:false,reason:'Encontro indisponível.'};const index=encounter.combatants.findIndex(c=>c.id===text(combatantId));if(index<0)return{ok:false,reason:'Combatente não encontrado.'};const old=encounter.combatants[index],combatant=sanitizeCombatant({...old,...patch,id:old.id,kind:old.kind,characterId:old.characterId,monsterId:old.monsterId});encounter.combatants[index]=combatant;encounter.updatedAt=now();return{ok:true,encounter,combatant}}
export function removeCombatant(encounter,combatantId){if(!encounter)return{ok:false,reason:'Encontro indisponível.'};const id=text(combatantId),before=encounter.combatants.length;encounter.combatants=encounter.combatants.filter(c=>c.id!==id);if(encounter.combatants.length===before)return{ok:false,reason:'Combatente não encontrado.'};if(encounter.activeCombatantId===id)encounter.activeCombatantId=encounter.combatants[0]?.id||null;encounter.updatedAt=now();return{ok:true,encounter}}

export function initiativeOrder(encounter){return arr(encounter?.combatants).map(sanitizeCombatant).sort((a,b)=>{const ai=a.initiative==null?-Infinity:a.initiative,bi=b.initiative==null?-Infinity:b.initiative;return bi-ai||b.initiativeModifier-a.initiativeModifier||a.name.localeCompare(b.name,'pt-BR')||a.id.localeCompare(b.id)})}
export function sortInitiative(encounter){if(!encounter)return[];encounter.combatants=initiativeOrder(encounter);return encounter.combatants}
export function setCombatantInitiative(encounter,combatantId,value){const result=updateCombatant(encounter,combatantId,{initiative:Number.isFinite(Number(value))?Number(value):null});if(result.ok)sortInitiative(encounter);return result}
export function nextEncounterTurn(encounter){if(!encounter?.combatants?.length)return{ok:false,reason:'Encontro sem combatentes.'};sortInitiative(encounter);let index=encounter.combatants.findIndex(c=>c.id===encounter.activeCombatantId);if(index<0)index=0;else{index+=1;if(index>=encounter.combatants.length){index=0;encounter.round=Math.max(1,Math.floor(num(encounter.round)||1)+1)}}encounter.activeCombatantId=encounter.combatants[index].id;encounter.updatedAt=now();return{ok:true,encounter,combatant:encounter.combatants[index],round:encounter.round}}
export function previousEncounterTurn(encounter){if(!encounter?.combatants?.length)return{ok:false,reason:'Encontro sem combatentes.'};sortInitiative(encounter);let index=encounter.combatants.findIndex(c=>c.id===encounter.activeCombatantId);if(index<0)index=0;else{index-=1;if(index<0){index=encounter.combatants.length-1;encounter.round=Math.max(1,Math.floor(num(encounter.round)||1)-1)}}encounter.activeCombatantId=encounter.combatants[index].id;encounter.updatedAt=now();return{ok:true,encounter,combatant:encounter.combatants[index],round:encounter.round}}

export function creatureTargetForResolution(combatant){const c=sanitizeCombatant(combatant);if(c.kind==='character')return null;return{name:c.name,ac:c.ac,saveModifier:0,saveModifiers:{...c.saveModifiers},resistances:[...c.resistances],immunities:[...c.immunities],vulnerabilities:[...c.vulnerabilities],conditionImmunities:[...c.conditionImmunities],combatantId:c.id,monsterId:c.monsterId||null}}
export function applyEncounterDamage(encounter,combatantId,amount,{type=''}={}){const c=encounter?.combatants?.find(row=>row.id===text(combatantId));if(!c||c.kind==='character')return{ok:false,reason:'PV de personagens são administrados pela Ficha Digital.'};const defense=applyDamageDefenses(amount,type,c),before={currentHp:c.currentHp,tempHp:c.tempHp},absorbed=Math.min(c.tempHp,defense.effective),remaining=defense.effective-absorbed;c.tempHp-=absorbed;c.currentHp=Math.max(0,c.currentHp-remaining);c.defeated=c.currentHp===0;encounter.updatedAt=now();return{ok:true,...defense,absorbedByTempHp:absorbed,before,after:{currentHp:c.currentHp,tempHp:c.tempHp},combatant:c}}
export function applyEncounterHealing(encounter,combatantId,amount){const c=encounter?.combatants?.find(row=>row.id===text(combatantId));if(!c||c.kind==='character')return{ok:false,reason:'PV de personagens são administrados pela Ficha Digital.'};const healing=Math.max(0,Math.floor(num(amount))),before=c.currentHp;c.currentHp=Math.min(c.maxHp,c.currentHp+healing);if(c.currentHp>0)c.defeated=false;encounter.updatedAt=now();return{ok:true,rolled:healing,applied:c.currentHp-before,before,after:c.currentHp,combatant:c}}
export function setEncounterRewards(encounter,rewards={}){if(!encounter)return null;encounter.rewards=sanitizeEncounter({...encounter,rewards:{...encounter.rewards,...rewards}}).rewards;encounter.updatedAt=now();return encounter.rewards}
export function encounterSummary(encounter){const e=sanitizeEncounter(encounter),defeated=e.combatants.filter(c=>c.kind!=='character'&&c.defeated),participants=e.combatants.filter(c=>c.kind==='character');return{title:e.title,status:e.status,rounds:e.round,participants:participants.map(c=>({characterId:c.characterId,name:c.name})),defeated:defeated.map(c=>({monsterId:c.monsterId,name:c.name})),rewards:{...e.rewards},summary:e.summary}}
