const SRD='https://apisearch.thedmstoolkit.com/api/2024/monsters';
const SOURCES=[
 ['efa','Eberron: Forge of the Artificer',2025,'5.5e',90],
 ['fraif','Forgotten Realms: Adventures in Faerûn',2025,'5.5e',85],
 ['xdmg',"Dungeon Master's Guide (2024)",2024,'5.5e',75],
 ['mpmm','Mordenkainen Presents: Monsters of the Multiverse',2022,'5e',60],
 ['tce',"Tasha's Cauldron of Everything",2020,'5e',50],
 ['erlw','Eberron: Rising from the Last War',2019,'5e',40],
 ['xge',"Xanathar's Guide to Everything",2017,'5e',30]
];
const SOURCE_BY_ID=Object.fromEntries(SOURCES.map(([id,title,year,ruleset,priority])=>[id,{id,title,year,ruleset,priority}]));
const ABILITY_PT={str:'Força',dex:'Destreza',con:'Constituição',int:'Inteligência',wis:'Sabedoria',cha:'Carisma'};
const XP_BY_CR={'0':10,'1/8':25,'1/4':50,'1/2':100,'1':200,'2':450,'3':700,'4':1100,'5':1800,'6':2300,'7':2900,'8':3900,'9':5000,'10':5900,'11':7200,'12':8400,'13':10000,'14':11500,'15':13000,'16':15000,'17':18000,'18':20000,'19':22000,'20':25000,'21':33000,'22':41000,'23':50000,'24':62000,'25':75000,'26':90000,'27':105000,'28':120000,'29':135000,'30':155000};
const arr=v=>Array.isArray(v)?v:[];
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const text=v=>String(v??'').trim();
const fold=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const cleanMarkup=v=>text(v).replace(/\{@[^ ]+\s+([^}|]+)(?:\|[^}]*)?\}/g,'$1').replace(/[{}]/g,'');
const listText=v=>arr(v).flatMap(row=>typeof row==='string'?[cleanMarkup(row)]:row&&typeof row==='object'?[cleanMarkup(row.special||row.note||row.name||JSON.stringify(row))]:[]).filter(Boolean);
const mod=score=>Math.floor((num(score)-10)/2);
const parseFirstNumber=v=>{const match=text(v).match(/-?\d+/);return match?Number(match[0]):0};
function acValue(value){for(const row of arr(value)){if(Number.isFinite(Number(row)))return Number(row);if(Number.isFinite(Number(row?.ac)))return Number(row.ac)}return Number.isFinite(Number(value))?Number(value):parseFirstNumber(value)}
function hpValue(value){if(Number.isFinite(Number(value)))return Number(value);if(Number.isFinite(Number(value?.average)))return Number(value.average);return parseFirstNumber(value)}
function crValue(value){if(typeof value==='string'||typeof value==='number')return text(value);return text(value?.cr||value?.rating||'')}
function saveMap(value={}){const source=value&&typeof value==='object'&&!Array.isArray(value)?value:{},out={};for(const[key,v]of Object.entries(source)){const ability=ABILITY_PT[fold(key).slice(0,3)]||key;out[ability]=parseFirstNumber(v)}return out}
function initiativeFromRecord(m){const raw=m?.initiative;if(Number.isFinite(Number(raw)))return Number(raw);if(Array.isArray(raw)&&raw.length){const first=raw[0];if(Number.isFinite(Number(first)))return Number(first);if(Number.isFinite(Number(first?.initiative)))return Number(first.initiative);if(Number.isFinite(Number(first?.bonus)))return Number(first.bonus)}return mod(m?.dex)}
function normalizeCrXp(cr,xp=0){const key=text(cr);return Math.max(0,Math.floor(num(xp)||XP_BY_CR[key]||0))}

export function normalizeStructuredMonster(record={},meta={}){
 const cr=crValue(record.cr),maxHp=Math.max(1,Math.floor(hpValue(record.hp)||1));
 return{id:text(meta.id)||`monster:${meta.sourceId||record.source||'source'}:${fold(record.name).replace(/[^a-z0-9]+/g,'-')}`,name:text(record.name)||'Monstro',sourceId:text(meta.sourceId||record.source),source:text(meta.sourceTitle||meta.source||record.source||'Fonte de monstro'),year:num(meta.year),ruleset:text(meta.ruleset),kind:'monster',ac:Math.max(0,Math.floor(acValue(record.ac))),maxHp,initiativeModifier:initiativeFromRecord(record),saveModifiers:saveMap(record.save),resistances:listText(record.resist),immunities:listText(record.immune),vulnerabilities:listText(record.vulnerable),conditionImmunities:listText(record.conditionImmune),cr,xp:normalizeCrXp(cr,record.xp),raw:record}
}
function field(textValue,label,nextLabels){const source=String(textValue||''),end=nextLabels.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),re=new RegExp(`${label}\\s*[:.]?\\s*([^\\n]+?)(?=\\n(?:${end})\\b|$)`,'i'),match=source.match(re);return match?.[1]?.trim()||''}
function splitTypes(value){return text(value).split(/[,;]/).map(x=>x.replace(/\([^)]*\)/g,'').trim()).filter(Boolean)}
export function normalizeRawMonster({name,raw,text:rawText,source,sourceTitle,sourceId,source_year,year,ruleset,id}={}){
 const block=String(raw||rawText||''),ac=parseFirstNumber(field(block,'Armou?r Class',['Hit Points','Speed','STR'])),maxHp=Math.max(1,parseFirstNumber(field(block,'Hit Points',['Speed','STR']))||1),dexMatch=block.match(/DEX\s*\n?\s*(\d+)\s*\(([+-]?\d+)\)/i),cr=field(block,'Challenge',['Proficiency Bonus','Traits','Actions']).match(/^([^ (]+)/)?.[1]||'';
 const saveLine=field(block,'Saving Throws',['Skills','Damage Vulnerabilities','Damage Resistances','Damage Immunities','Condition Immunities','Senses','Languages','Challenge']),saveModifiers={};for(const m of saveLine.matchAll(/(Str|Dex|Con|Int|Wis|Cha)\s*([+-]\d+)/gi))saveModifiers[ABILITY_PT[fold(m[1])]]=Number(m[2]);
 return{id:text(id)||`monster:pdf:${fold(name).replace(/[^a-z0-9]+/g,'-')}`,name:text(name)||'Monstro',sourceId:text(sourceId||source)||'pdf',source:text(sourceTitle||source)||'PDF',year:num(year||source_year),ruleset:text(ruleset),kind:'monster',ac,maxHp,initiativeModifier:dexMatch?Number(dexMatch[2]):0,saveModifiers,resistances:splitTypes(field(block,'Damage Resistances',['Damage Immunities','Condition Immunities','Senses','Languages','Challenge'])),immunities:splitTypes(field(block,'Damage Immunities',['Condition Immunities','Senses','Languages','Challenge'])),vulnerabilities:splitTypes(field(block,'Damage Vulnerabilities',['Damage Resistances','Damage Immunities','Condition Immunities','Senses','Languages','Challenge'])),conditionImmunities:splitTypes(field(block,'Condition Immunities',['Senses','Languages','Challenge'])),cr,xp:normalizeCrXp(cr,parseFirstNumber((block.match(/Challenge[^\n]*\(([^)]+XP)/i)||[])[1])),raw:block}
}
function propertyLookup(properties,key){if(!properties)return null;if(Array.isArray(properties)){const wanted=fold(key);const row=properties.find(p=>fold(p?.name||p?.label||p?.key)===wanted);return row?.value??row?.values??row?.text??row}if(typeof properties==='object'){const direct=properties[key]??properties[fold(key)]??properties[key.replace(/ /g,'_')];if(direct!=null)return direct;for(const[k,v]of Object.entries(properties))if(fold(k)===fold(key))return v}return null}
export function normalizeSrdMonsterDetail(detail={},meta={}){
 const properties=detail.properties||detail,description=String(detail.description_md||detail.description||''),name=text(detail.name||meta.name)||'Monstro';
 const ac=acValue(propertyLookup(properties,'Armor Class')??propertyLookup(properties,'AC')),maxHp=Math.max(1,hpValue(propertyLookup(properties,'Hit Points')??propertyLookup(properties,'HP'))||1),dex=propertyLookup(properties,'DEX')??propertyLookup(properties,'Dexterity'),cr=text(propertyLookup(properties,'Challenge')??propertyLookup(properties,'Challenge Rating'));
 const structured={id:text(meta.id)||`srd:${meta.slug||fold(name).replace(/[^a-z0-9]+/g,'-')}`,name,sourceId:'srd',source:'SRD 5.2.1',year:2025,ruleset:'5.5e',kind:'monster',ac:Math.max(0,Math.floor(ac)),maxHp,initiativeModifier:Number.isFinite(Number(propertyLookup(properties,'Initiative')))?Number(propertyLookup(properties,'Initiative')):mod(parseFirstNumber(dex)),saveModifiers:{},resistances:splitTypes(propertyLookup(properties,'Damage Resistances')),immunities:splitTypes(propertyLookup(properties,'Damage Immunities')),vulnerabilities:splitTypes(propertyLookup(properties,'Damage Vulnerabilities')),conditionImmunities:splitTypes(propertyLookup(properties,'Condition Immunities')),cr,xp:normalizeCrXp(cr),raw:detail};
 if(!structured.ac||structured.maxHp<=1){const raw=normalizeRawMonster({name,raw:description,source:'SRD 5.2.1',sourceId:'srd',year:2025,ruleset:'5.5e',id:structured.id});for(const key of['ac','maxHp','initiativeModifier','saveModifiers','resistances','immunities','vulnerabilities','conditionImmunities','cr','xp'])if((Array.isArray(structured[key])&&!structured[key].length)||(!structured[key]&&structured[key]!==0))structured[key]=raw[key]}
 return structured
}

function complete5(m){return!!(m&&m.name&&(m._copy||(m.size&&m.type&&m.ac&&m.hp&&m.speed&&m.str!=null&&m.dex!=null&&m.con!=null&&m.int!=null&&m.wis!=null&&m.cha!=null)))}
export async function loadEncounterMonsterIndex(fetcher=globalThis.fetch){if(typeof fetcher!=='function')throw new Error('Fetch indisponível para carregar monstros.');const[srdIndex,extras,...sets]=await Promise.all([fetcher(`${SRD}?fields=name,slug,source`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`SRD HTTP ${r.status}`);return r.json()}),fetcher('dados/monstros-pdf-extras.json').then(r=>r.json()),...SOURCES.map(([id])=>fetcher(`dados/monstros-fontes/${id}.json`).then(r=>r.json()))]);const rows=[],srdRows=Array.isArray(srdIndex.data)?srdIndex.data:[];for(const item of srdRows)rows.push({id:`srd:${item.slug}`,kind:'srd',name:item.name,slug:item.slug,sourceId:'srd',sourceTitle:'SRD 5.2.1',year:2025,ruleset:'5.5e',priority:70});sets.forEach((data,index)=>{const source=SOURCE_BY_ID[SOURCES[index][0]];for(const[recordIndex,record]of arr(data.monster).entries())if(complete5(record))rows.push({id:`${source.id}:${recordIndex}:${fold(record.name).replace(/[^a-z0-9]+/g,'-')}`,kind:'structured',name:record.name,sourceId:source.id,sourceTitle:source.title,year:source.year,ruleset:source.ruleset,priority:source.priority,record})});for(const[index,item]of arr(extras.items).entries())rows.push({id:`pdf:${index}:${fold(item.name).replace(/[^a-z0-9]+/g,'-')}`,kind:'pdf',name:item.name,sourceId:item.source||'pdf',sourceTitle:item.source||'PDF',year:item.source_year||item.year||0,ruleset:item.ruleset||'5e',priority:55,record:item});const chosen=new Map;for(const row of rows){const key=fold(row.name),old=chosen.get(key);if(!old||row.priority>old.priority)chosen.set(key,row)}return[...chosen.values()].sort((a,b)=>a.name.localeCompare(b.name,'en'))}
export async function loadEncounterMonsterDetail(row,fetcher=globalThis.fetch){if(!row)throw new Error('Monstro inválido.');if(row.kind==='structured')return normalizeStructuredMonster(row.record,row);if(row.kind==='pdf')return normalizeRawMonster({...row.record,...row,id:row.id});if(row.kind==='srd'){const response=await fetcher(`${SRD}/${encodeURIComponent(row.slug)}`,{cache:'force-cache'});if(!response.ok)throw new Error(`SRD HTTP ${response.status}`);const payload=await response.json();return normalizeSrdMonsterDetail(payload.data||payload,row)}throw new Error('Formato de monstro não suportado.')}
export const ENCOUNTER_MONSTER_SOURCES=Object.freeze(SOURCES.map(row=>Object.freeze([...row])));
